create table SPAgency (
	uuid_ VARCHAR(75) null,
	spAgencyId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	number_ VARCHAR(200) null,
	country VARCHAR(200) null,
	name VARCHAR(200) null,
	reference VARCHAR(200) null,
	startDate VARCHAR(200) null,
	endDate VARCHAR(200) null,
	address LONGTEXT null,
	remarks LONGTEXT null,
	status VARCHAR(200) null,
	customField1 VARCHAR(200) null,
	customField2 VARCHAR(200) null,
	customField3 VARCHAR(200) null,
	customDate1 DATETIME null,
	customDate2 DATETIME null,
	customDate3 DATETIME null,
	version VARCHAR(75) null,
	rootSpAgencyId BIGINT(20)
);

create table SPClassMaster (
	uuid_ VARCHAR(75) null,
	spClassId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	code_ VARCHAR(75) null,
	country VARCHAR(75) null,
	filedBy VARCHAR(75) null,
	customField1 VARCHAR(75) null,
	customField2 VARCHAR(75) null,
	customDate1 DATETIME null,
	customDate2 DATETIME null,
	version VARCHAR(75) null,
	rootSpClassId BIGINT(20)
);

create table SPLitigationDetails (
	uuid_ VARCHAR(75) null,
	spLitigationId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	country VARCHAR(200) null,
	filedBy VARCHAR(200) null,
	filedOn DATETIME null,
	filedAtCountry VARCHAR(200) null,
	claimsRemarks LONGTEXT null,
	responseDeadline DATETIME null,
	actualResponseDate DATETIME null,
	status VARCHAR(200) null,
	customField1 VARCHAR(200) null,
	customField2 VARCHAR(200) null,
	customField3 VARCHAR(200) null,
	customDate1 DATETIME null,
	customDate2 DATETIME null,
	customDate3 DATETIME null,
	legalConfRemarks LONGTEXT null,
	version VARCHAR(75) null,
	spTrademarksId BIGINT(20),
	rootSpLitigationId BIGINT(20)
);

create table SPLitigationRDL (
	uuid_ VARCHAR(75) null,
	spRdlId BIGINT(20) not null primary key,
	spLitigationId BIGINT(20),
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	responseDeadline DATETIME null,
	claimsRemarks LONGTEXT null,
	alertBefore BIGINT(20)
);

create table SPTrademarksMaster (
	uuid_ VARCHAR(75) null,
	spTrademarksId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	registrationNumber VARCHAR(200) null,
	applicationNo VARCHAR(200) null,
	country VARCHAR(200) null,
	trademark VARCHAR(200) null,
	trademarkLocalized VARCHAR(200) null,
	registeredOwner VARCHAR(200) null,
	applicationDate DATETIME null,
	firstRegistrationDate DATETIME null,
	renewalDate DATETIME null,
	goodsServices LONGTEXT null,
	pendingComments LONGTEXT null,
	spAgencyId BIGINT(20),
	classDescription LONGTEXT null,
	legalConfRemarks LONGTEXT null,
	workflowStatus BIGINT(20),
	customField1 LONGTEXT null,
	customField2 VARCHAR(200) null,
	customField3 LONGTEXT null,
	customDate1 DATETIME null,
	customDate2 DATETIME null,
	customDate3 DATETIME null,
	classCodes LONGTEXT null,
	version VARCHAR(75) null,
	trademarkType VARCHAR(200) null,
	rootSpTrademarksId BIGINT(20)
);