/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.model.CourseDurationType;
import com.sambaash.platform.srv.model.CourseDurationTypeModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CourseDurationType service. Represents a row in the &quot;SPCourseDurationType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.model.CourseDurationTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CourseDurationTypeImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see CourseDurationTypeImpl
 * @see com.sambaash.platform.srv.model.CourseDurationType
 * @see com.sambaash.platform.srv.model.CourseDurationTypeModel
 * @generated
 */
public class CourseDurationTypeModelImpl extends BaseModelImpl<CourseDurationType>
	implements CourseDurationTypeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course duration type model instance should use the {@link com.sambaash.platform.srv.model.CourseDurationType} interface instead.
	 */
	public static final String TABLE_NAME = "SPCourseDurationType";
	public static final Object[][] TABLE_COLUMNS = {
			{ "spCourseDurationTypeId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "spCourseDurationId", Types.BIGINT },
			{ "spCourseId", Types.BIGINT },
			{ "title1", Types.VARCHAR },
			{ "duration1", Types.VARCHAR },
			{ "title2", Types.VARCHAR },
			{ "duration2", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SPCourseDurationType (spCourseDurationTypeId BIGINT(20) not null primary key,groupId BIGINT(20),companyId BIGINT(20),userId BIGINT(20),userName VARCHAR(75) null,createDate DATETIME null,modifiedDate DATETIME null,spCourseDurationId BIGINT(20),spCourseId BIGINT(20),title1 VARCHAR(500) null,duration1 VARCHAR(75) null,title2 VARCHAR(500) null,duration2 VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SPCourseDurationType";
	public static final String ORDER_BY_JPQL = " ORDER BY courseDurationType.spCourseDurationTypeId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPCourseDurationType.spCourseDurationTypeId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.model.CourseDurationType"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.model.CourseDurationType"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.model.CourseDurationType"),
			true);
	public static long SPCOURSEDURATIONID_COLUMN_BITMASK = 1L;
	public static long SPCOURSEID_COLUMN_BITMASK = 2L;
	public static long SPCOURSEDURATIONTYPEID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.model.CourseDurationType"));

	public CourseDurationTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _spCourseDurationTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSpCourseDurationTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _spCourseDurationTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CourseDurationType.class;
	}

	@Override
	public String getModelClassName() {
		return CourseDurationType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("spCourseDurationTypeId", getSpCourseDurationTypeId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("spCourseDurationId", getSpCourseDurationId());
		attributes.put("spCourseId", getSpCourseId());
		attributes.put("title1", getTitle1());
		attributes.put("duration1", getDuration1());
		attributes.put("title2", getTitle2());
		attributes.put("duration2", getDuration2());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long spCourseDurationTypeId = (Long)attributes.get(
				"spCourseDurationTypeId");

		if (spCourseDurationTypeId != null) {
			setSpCourseDurationTypeId(spCourseDurationTypeId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long spCourseDurationId = (Long)attributes.get("spCourseDurationId");

		if (spCourseDurationId != null) {
			setSpCourseDurationId(spCourseDurationId);
		}

		Long spCourseId = (Long)attributes.get("spCourseId");

		if (spCourseId != null) {
			setSpCourseId(spCourseId);
		}

		String title1 = (String)attributes.get("title1");

		if (title1 != null) {
			setTitle1(title1);
		}

		String duration1 = (String)attributes.get("duration1");

		if (duration1 != null) {
			setDuration1(duration1);
		}

		String title2 = (String)attributes.get("title2");

		if (title2 != null) {
			setTitle2(title2);
		}

		String duration2 = (String)attributes.get("duration2");

		if (duration2 != null) {
			setDuration2(duration2);
		}
	}

	@Override
	public long getSpCourseDurationTypeId() {
		return _spCourseDurationTypeId;
	}

	@Override
	public void setSpCourseDurationTypeId(long spCourseDurationTypeId) {
		_spCourseDurationTypeId = spCourseDurationTypeId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getSpCourseDurationId() {
		return _spCourseDurationId;
	}

	@Override
	public void setSpCourseDurationId(long spCourseDurationId) {
		_columnBitmask |= SPCOURSEDURATIONID_COLUMN_BITMASK;

		if (!_setOriginalSpCourseDurationId) {
			_setOriginalSpCourseDurationId = true;

			_originalSpCourseDurationId = _spCourseDurationId;
		}

		_spCourseDurationId = spCourseDurationId;
	}

	public long getOriginalSpCourseDurationId() {
		return _originalSpCourseDurationId;
	}

	@Override
	public long getSpCourseId() {
		return _spCourseId;
	}

	@Override
	public void setSpCourseId(long spCourseId) {
		_columnBitmask |= SPCOURSEID_COLUMN_BITMASK;

		if (!_setOriginalSpCourseId) {
			_setOriginalSpCourseId = true;

			_originalSpCourseId = _spCourseId;
		}

		_spCourseId = spCourseId;
	}

	public long getOriginalSpCourseId() {
		return _originalSpCourseId;
	}

	@Override
	public String getTitle1() {
		if (_title1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _title1;
		}
	}

	@Override
	public void setTitle1(String title1) {
		_title1 = title1;
	}

	@Override
	public String getDuration1() {
		if (_duration1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _duration1;
		}
	}

	@Override
	public void setDuration1(String duration1) {
		_duration1 = duration1;
	}

	@Override
	public String getTitle2() {
		if (_title2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _title2;
		}
	}

	@Override
	public void setTitle2(String title2) {
		_title2 = title2;
	}

	@Override
	public String getDuration2() {
		if (_duration2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _duration2;
		}
	}

	@Override
	public void setDuration2(String duration2) {
		_duration2 = duration2;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CourseDurationType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CourseDurationType toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CourseDurationType)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CourseDurationTypeImpl courseDurationTypeImpl = new CourseDurationTypeImpl();

		courseDurationTypeImpl.setSpCourseDurationTypeId(getSpCourseDurationTypeId());
		courseDurationTypeImpl.setGroupId(getGroupId());
		courseDurationTypeImpl.setCompanyId(getCompanyId());
		courseDurationTypeImpl.setUserId(getUserId());
		courseDurationTypeImpl.setUserName(getUserName());
		courseDurationTypeImpl.setCreateDate(getCreateDate());
		courseDurationTypeImpl.setModifiedDate(getModifiedDate());
		courseDurationTypeImpl.setSpCourseDurationId(getSpCourseDurationId());
		courseDurationTypeImpl.setSpCourseId(getSpCourseId());
		courseDurationTypeImpl.setTitle1(getTitle1());
		courseDurationTypeImpl.setDuration1(getDuration1());
		courseDurationTypeImpl.setTitle2(getTitle2());
		courseDurationTypeImpl.setDuration2(getDuration2());

		courseDurationTypeImpl.resetOriginalValues();

		return courseDurationTypeImpl;
	}

	@Override
	public int compareTo(CourseDurationType courseDurationType) {
		long primaryKey = courseDurationType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CourseDurationType)) {
			return false;
		}

		CourseDurationType courseDurationType = (CourseDurationType)obj;

		long primaryKey = courseDurationType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CourseDurationTypeModelImpl courseDurationTypeModelImpl = this;

		courseDurationTypeModelImpl._originalSpCourseDurationId = courseDurationTypeModelImpl._spCourseDurationId;

		courseDurationTypeModelImpl._setOriginalSpCourseDurationId = false;

		courseDurationTypeModelImpl._originalSpCourseId = courseDurationTypeModelImpl._spCourseId;

		courseDurationTypeModelImpl._setOriginalSpCourseId = false;

		courseDurationTypeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CourseDurationType> toCacheModel() {
		CourseDurationTypeCacheModel courseDurationTypeCacheModel = new CourseDurationTypeCacheModel();

		courseDurationTypeCacheModel.spCourseDurationTypeId = getSpCourseDurationTypeId();

		courseDurationTypeCacheModel.groupId = getGroupId();

		courseDurationTypeCacheModel.companyId = getCompanyId();

		courseDurationTypeCacheModel.userId = getUserId();

		courseDurationTypeCacheModel.userName = getUserName();

		String userName = courseDurationTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			courseDurationTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			courseDurationTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			courseDurationTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			courseDurationTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			courseDurationTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		courseDurationTypeCacheModel.spCourseDurationId = getSpCourseDurationId();

		courseDurationTypeCacheModel.spCourseId = getSpCourseId();

		courseDurationTypeCacheModel.title1 = getTitle1();

		String title1 = courseDurationTypeCacheModel.title1;

		if ((title1 != null) && (title1.length() == 0)) {
			courseDurationTypeCacheModel.title1 = null;
		}

		courseDurationTypeCacheModel.duration1 = getDuration1();

		String duration1 = courseDurationTypeCacheModel.duration1;

		if ((duration1 != null) && (duration1.length() == 0)) {
			courseDurationTypeCacheModel.duration1 = null;
		}

		courseDurationTypeCacheModel.title2 = getTitle2();

		String title2 = courseDurationTypeCacheModel.title2;

		if ((title2 != null) && (title2.length() == 0)) {
			courseDurationTypeCacheModel.title2 = null;
		}

		courseDurationTypeCacheModel.duration2 = getDuration2();

		String duration2 = courseDurationTypeCacheModel.duration2;

		if ((duration2 != null) && (duration2.length() == 0)) {
			courseDurationTypeCacheModel.duration2 = null;
		}

		return courseDurationTypeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{spCourseDurationTypeId=");
		sb.append(getSpCourseDurationTypeId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", spCourseDurationId=");
		sb.append(getSpCourseDurationId());
		sb.append(", spCourseId=");
		sb.append(getSpCourseId());
		sb.append(", title1=");
		sb.append(getTitle1());
		sb.append(", duration1=");
		sb.append(getDuration1());
		sb.append(", title2=");
		sb.append(getTitle2());
		sb.append(", duration2=");
		sb.append(getDuration2());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.sambaash.platform.srv.model.CourseDurationType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>spCourseDurationTypeId</column-name><column-value><![CDATA[");
		sb.append(getSpCourseDurationTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>spCourseDurationId</column-name><column-value><![CDATA[");
		sb.append(getSpCourseDurationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>spCourseId</column-name><column-value><![CDATA[");
		sb.append(getSpCourseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title1</column-name><column-value><![CDATA[");
		sb.append(getTitle1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>duration1</column-name><column-value><![CDATA[");
		sb.append(getDuration1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title2</column-name><column-value><![CDATA[");
		sb.append(getTitle2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>duration2</column-name><column-value><![CDATA[");
		sb.append(getDuration2());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CourseDurationType.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CourseDurationType.class
		};
	private long _spCourseDurationTypeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _spCourseDurationId;
	private long _originalSpCourseDurationId;
	private boolean _setOriginalSpCourseDurationId;
	private long _spCourseId;
	private long _originalSpCourseId;
	private boolean _setOriginalSpCourseId;
	private String _title1;
	private String _duration1;
	private String _title2;
	private String _duration2;
	private long _columnBitmask;
	private CourseDurationType _escapedModel;
}