/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.model.CourseDuration;
import com.sambaash.platform.srv.model.CourseDurationModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CourseDuration service. Represents a row in the &quot;SPCourseDuration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.model.CourseDurationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CourseDurationImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see CourseDurationImpl
 * @see com.sambaash.platform.srv.model.CourseDuration
 * @see com.sambaash.platform.srv.model.CourseDurationModel
 * @generated
 */
public class CourseDurationModelImpl extends BaseModelImpl<CourseDuration>
	implements CourseDurationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course duration model instance should use the {@link com.sambaash.platform.srv.model.CourseDuration} interface instead.
	 */
	public static final String TABLE_NAME = "SPCourseDuration";
	public static final Object[][] TABLE_COLUMNS = {
			{ "spCourseDurationId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "spCourseId", Types.BIGINT },
			{ "spCourseLearningId", Types.BIGINT },
			{ "title", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SPCourseDuration (spCourseDurationId BIGINT(20) not null primary key,groupId BIGINT(20),companyId BIGINT(20),userId BIGINT(20),userName VARCHAR(75) null,createDate DATETIME null,modifiedDate DATETIME null,spCourseId BIGINT(20),spCourseLearningId BIGINT(20),title VARCHAR(500) null)";
	public static final String TABLE_SQL_DROP = "drop table SPCourseDuration";
	public static final String ORDER_BY_JPQL = " ORDER BY courseDuration.spCourseDurationId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPCourseDuration.spCourseDurationId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.model.CourseDuration"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.model.CourseDuration"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.model.CourseDuration"),
			true);
	public static long SPCOURSEID_COLUMN_BITMASK = 1L;
	public static long SPCOURSEDURATIONID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.model.CourseDuration"));

	public CourseDurationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _spCourseDurationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSpCourseDurationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _spCourseDurationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CourseDuration.class;
	}

	@Override
	public String getModelClassName() {
		return CourseDuration.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("spCourseDurationId", getSpCourseDurationId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("spCourseId", getSpCourseId());
		attributes.put("spCourseLearningId", getSpCourseLearningId());
		attributes.put("title", getTitle());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long spCourseDurationId = (Long)attributes.get("spCourseDurationId");

		if (spCourseDurationId != null) {
			setSpCourseDurationId(spCourseDurationId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long spCourseId = (Long)attributes.get("spCourseId");

		if (spCourseId != null) {
			setSpCourseId(spCourseId);
		}

		Long spCourseLearningId = (Long)attributes.get("spCourseLearningId");

		if (spCourseLearningId != null) {
			setSpCourseLearningId(spCourseLearningId);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}
	}

	@Override
	public long getSpCourseDurationId() {
		return _spCourseDurationId;
	}

	@Override
	public void setSpCourseDurationId(long spCourseDurationId) {
		_spCourseDurationId = spCourseDurationId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getSpCourseId() {
		return _spCourseId;
	}

	@Override
	public void setSpCourseId(long spCourseId) {
		_columnBitmask |= SPCOURSEID_COLUMN_BITMASK;

		if (!_setOriginalSpCourseId) {
			_setOriginalSpCourseId = true;

			_originalSpCourseId = _spCourseId;
		}

		_spCourseId = spCourseId;
	}

	public long getOriginalSpCourseId() {
		return _originalSpCourseId;
	}

	@Override
	public long getSpCourseLearningId() {
		return _spCourseLearningId;
	}

	@Override
	public void setSpCourseLearningId(long spCourseLearningId) {
		_spCourseLearningId = spCourseLearningId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CourseDuration.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CourseDuration toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CourseDuration)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CourseDurationImpl courseDurationImpl = new CourseDurationImpl();

		courseDurationImpl.setSpCourseDurationId(getSpCourseDurationId());
		courseDurationImpl.setGroupId(getGroupId());
		courseDurationImpl.setCompanyId(getCompanyId());
		courseDurationImpl.setUserId(getUserId());
		courseDurationImpl.setUserName(getUserName());
		courseDurationImpl.setCreateDate(getCreateDate());
		courseDurationImpl.setModifiedDate(getModifiedDate());
		courseDurationImpl.setSpCourseId(getSpCourseId());
		courseDurationImpl.setSpCourseLearningId(getSpCourseLearningId());
		courseDurationImpl.setTitle(getTitle());

		courseDurationImpl.resetOriginalValues();

		return courseDurationImpl;
	}

	@Override
	public int compareTo(CourseDuration courseDuration) {
		long primaryKey = courseDuration.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CourseDuration)) {
			return false;
		}

		CourseDuration courseDuration = (CourseDuration)obj;

		long primaryKey = courseDuration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CourseDurationModelImpl courseDurationModelImpl = this;

		courseDurationModelImpl._originalSpCourseId = courseDurationModelImpl._spCourseId;

		courseDurationModelImpl._setOriginalSpCourseId = false;

		courseDurationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CourseDuration> toCacheModel() {
		CourseDurationCacheModel courseDurationCacheModel = new CourseDurationCacheModel();

		courseDurationCacheModel.spCourseDurationId = getSpCourseDurationId();

		courseDurationCacheModel.groupId = getGroupId();

		courseDurationCacheModel.companyId = getCompanyId();

		courseDurationCacheModel.userId = getUserId();

		courseDurationCacheModel.userName = getUserName();

		String userName = courseDurationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			courseDurationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			courseDurationCacheModel.createDate = createDate.getTime();
		}
		else {
			courseDurationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			courseDurationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			courseDurationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		courseDurationCacheModel.spCourseId = getSpCourseId();

		courseDurationCacheModel.spCourseLearningId = getSpCourseLearningId();

		courseDurationCacheModel.title = getTitle();

		String title = courseDurationCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			courseDurationCacheModel.title = null;
		}

		return courseDurationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{spCourseDurationId=");
		sb.append(getSpCourseDurationId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", spCourseId=");
		sb.append(getSpCourseId());
		sb.append(", spCourseLearningId=");
		sb.append(getSpCourseLearningId());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.sambaash.platform.srv.model.CourseDuration");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>spCourseDurationId</column-name><column-value><![CDATA[");
		sb.append(getSpCourseDurationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>spCourseId</column-name><column-value><![CDATA[");
		sb.append(getSpCourseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>spCourseLearningId</column-name><column-value><![CDATA[");
		sb.append(getSpCourseLearningId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CourseDuration.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CourseDuration.class
		};
	private long _spCourseDurationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _spCourseId;
	private long _originalSpCourseId;
	private boolean _setOriginalSpCourseId;
	private long _spCourseLearningId;
	private String _title;
	private long _columnBitmask;
	private CourseDuration _escapedModel;
}