/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.model.ProductCourse;
import com.sambaash.platform.srv.model.ProductCourseModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ProductCourse service. Represents a row in the &quot;SPProductCourse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.model.ProductCourseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductCourseImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see ProductCourseImpl
 * @see com.sambaash.platform.srv.model.ProductCourse
 * @see com.sambaash.platform.srv.model.ProductCourseModel
 * @generated
 */
public class ProductCourseModelImpl extends BaseModelImpl<ProductCourse>
	implements ProductCourseModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a product course model instance should use the {@link com.sambaash.platform.srv.model.ProductCourse} interface instead.
	 */
	public static final String TABLE_NAME = "SPProductCourse";
	public static final Object[][] TABLE_COLUMNS = {
			{ "spProductCourseId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "spProductId", Types.BIGINT },
			{ "spCourseId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table SPProductCourse (spProductCourseId BIGINT(20) not null primary key,groupId BIGINT(20),companyId BIGINT(20),userId BIGINT(20),userName VARCHAR(75) null,createDate DATETIME null,modifiedDate DATETIME null,spProductId BIGINT(20),spCourseId BIGINT(20))";
	public static final String TABLE_SQL_DROP = "drop table SPProductCourse";
	public static final String ORDER_BY_JPQL = " ORDER BY productCourse.spProductId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPProductCourse.spProductId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.model.ProductCourse"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.model.ProductCourse"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.model.ProductCourse"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long SPCOURSEID_COLUMN_BITMASK = 2L;
	public static long SPPRODUCTID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.model.ProductCourse"));

	public ProductCourseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _spProductCourseId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSpProductCourseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _spProductCourseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProductCourse.class;
	}

	@Override
	public String getModelClassName() {
		return ProductCourse.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("spProductCourseId", getSpProductCourseId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("spProductId", getSpProductId());
		attributes.put("spCourseId", getSpCourseId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long spProductCourseId = (Long)attributes.get("spProductCourseId");

		if (spProductCourseId != null) {
			setSpProductCourseId(spProductCourseId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long spProductId = (Long)attributes.get("spProductId");

		if (spProductId != null) {
			setSpProductId(spProductId);
		}

		Long spCourseId = (Long)attributes.get("spCourseId");

		if (spCourseId != null) {
			setSpCourseId(spCourseId);
		}
	}

	@Override
	public long getSpProductCourseId() {
		return _spProductCourseId;
	}

	@Override
	public void setSpProductCourseId(long spProductCourseId) {
		_spProductCourseId = spProductCourseId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getSpProductId() {
		return _spProductId;
	}

	@Override
	public void setSpProductId(long spProductId) {
		_columnBitmask = -1L;

		if (!_setOriginalSpProductId) {
			_setOriginalSpProductId = true;

			_originalSpProductId = _spProductId;
		}

		_spProductId = spProductId;
	}

	public long getOriginalSpProductId() {
		return _originalSpProductId;
	}

	@Override
	public long getSpCourseId() {
		return _spCourseId;
	}

	@Override
	public void setSpCourseId(long spCourseId) {
		_columnBitmask |= SPCOURSEID_COLUMN_BITMASK;

		if (!_setOriginalSpCourseId) {
			_setOriginalSpCourseId = true;

			_originalSpCourseId = _spCourseId;
		}

		_spCourseId = spCourseId;
	}

	public long getOriginalSpCourseId() {
		return _originalSpCourseId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ProductCourse.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProductCourse toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ProductCourse)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProductCourseImpl productCourseImpl = new ProductCourseImpl();

		productCourseImpl.setSpProductCourseId(getSpProductCourseId());
		productCourseImpl.setGroupId(getGroupId());
		productCourseImpl.setCompanyId(getCompanyId());
		productCourseImpl.setUserId(getUserId());
		productCourseImpl.setUserName(getUserName());
		productCourseImpl.setCreateDate(getCreateDate());
		productCourseImpl.setModifiedDate(getModifiedDate());
		productCourseImpl.setSpProductId(getSpProductId());
		productCourseImpl.setSpCourseId(getSpCourseId());

		productCourseImpl.resetOriginalValues();

		return productCourseImpl;
	}

	@Override
	public int compareTo(ProductCourse productCourse) {
		int value = 0;

		if (getSpProductId() < productCourse.getSpProductId()) {
			value = -1;
		}
		else if (getSpProductId() > productCourse.getSpProductId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ProductCourse)) {
			return false;
		}

		ProductCourse productCourse = (ProductCourse)obj;

		long primaryKey = productCourse.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ProductCourseModelImpl productCourseModelImpl = this;

		productCourseModelImpl._originalGroupId = productCourseModelImpl._groupId;

		productCourseModelImpl._setOriginalGroupId = false;

		productCourseModelImpl._originalSpProductId = productCourseModelImpl._spProductId;

		productCourseModelImpl._setOriginalSpProductId = false;

		productCourseModelImpl._originalSpCourseId = productCourseModelImpl._spCourseId;

		productCourseModelImpl._setOriginalSpCourseId = false;

		productCourseModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ProductCourse> toCacheModel() {
		ProductCourseCacheModel productCourseCacheModel = new ProductCourseCacheModel();

		productCourseCacheModel.spProductCourseId = getSpProductCourseId();

		productCourseCacheModel.groupId = getGroupId();

		productCourseCacheModel.companyId = getCompanyId();

		productCourseCacheModel.userId = getUserId();

		productCourseCacheModel.userName = getUserName();

		String userName = productCourseCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			productCourseCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			productCourseCacheModel.createDate = createDate.getTime();
		}
		else {
			productCourseCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			productCourseCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			productCourseCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		productCourseCacheModel.spProductId = getSpProductId();

		productCourseCacheModel.spCourseId = getSpCourseId();

		return productCourseCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{spProductCourseId=");
		sb.append(getSpProductCourseId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", spProductId=");
		sb.append(getSpProductId());
		sb.append(", spCourseId=");
		sb.append(getSpCourseId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.sambaash.platform.srv.model.ProductCourse");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>spProductCourseId</column-name><column-value><![CDATA[");
		sb.append(getSpProductCourseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>spProductId</column-name><column-value><![CDATA[");
		sb.append(getSpProductId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>spCourseId</column-name><column-value><![CDATA[");
		sb.append(getSpCourseId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ProductCourse.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ProductCourse.class
		};
	private long _spProductCourseId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _spProductId;
	private long _originalSpProductId;
	private boolean _setOriginalSpProductId;
	private long _spCourseId;
	private long _originalSpCourseId;
	private boolean _setOriginalSpCourseId;
	private long _columnBitmask;
	private ProductCourse _escapedModel;
}