/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.model.StudyOption;
import com.sambaash.platform.srv.model.StudyOptionModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the StudyOption service. Represents a row in the &quot;SPCourseStudyOption&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.model.StudyOptionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StudyOptionImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see StudyOptionImpl
 * @see com.sambaash.platform.srv.model.StudyOption
 * @see com.sambaash.platform.srv.model.StudyOptionModel
 * @generated
 */
public class StudyOptionModelImpl extends BaseModelImpl<StudyOption>
	implements StudyOptionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a study option model instance should use the {@link com.sambaash.platform.srv.model.StudyOption} interface instead.
	 */
	public static final String TABLE_NAME = "SPCourseStudyOption";
	public static final Object[][] TABLE_COLUMNS = {
			{ "spStudyOptionId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "spCourseId", Types.BIGINT },
			{ "title", Types.VARCHAR },
			{ "desc_", Types.VARCHAR },
			{ "coverImageFileEntryId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table SPCourseStudyOption (spStudyOptionId BIGINT(20) not null primary key,groupId BIGINT(20),companyId BIGINT(20),userId BIGINT(20),userName VARCHAR(75) null,createDate DATETIME null,modifiedDate DATETIME null,spCourseId BIGINT(20),title VARCHAR(500) null,desc_ LONGTEXT null,coverImageFileEntryId BIGINT(20))";
	public static final String TABLE_SQL_DROP = "drop table SPCourseStudyOption";
	public static final String ORDER_BY_JPQL = " ORDER BY studyOption.spStudyOptionId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPCourseStudyOption.spStudyOptionId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.model.StudyOption"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.model.StudyOption"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.model.StudyOption"),
			true);
	public static long SPCOURSEID_COLUMN_BITMASK = 1L;
	public static long SPSTUDYOPTIONID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.model.StudyOption"));

	public StudyOptionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _spStudyOptionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSpStudyOptionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _spStudyOptionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StudyOption.class;
	}

	@Override
	public String getModelClassName() {
		return StudyOption.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("spStudyOptionId", getSpStudyOptionId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("spCourseId", getSpCourseId());
		attributes.put("title", getTitle());
		attributes.put("desc", getDesc());
		attributes.put("coverImageFileEntryId", getCoverImageFileEntryId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long spStudyOptionId = (Long)attributes.get("spStudyOptionId");

		if (spStudyOptionId != null) {
			setSpStudyOptionId(spStudyOptionId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long spCourseId = (Long)attributes.get("spCourseId");

		if (spCourseId != null) {
			setSpCourseId(spCourseId);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String desc = (String)attributes.get("desc");

		if (desc != null) {
			setDesc(desc);
		}

		Long coverImageFileEntryId = (Long)attributes.get(
				"coverImageFileEntryId");

		if (coverImageFileEntryId != null) {
			setCoverImageFileEntryId(coverImageFileEntryId);
		}
	}

	@Override
	public long getSpStudyOptionId() {
		return _spStudyOptionId;
	}

	@Override
	public void setSpStudyOptionId(long spStudyOptionId) {
		_spStudyOptionId = spStudyOptionId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getSpCourseId() {
		return _spCourseId;
	}

	@Override
	public void setSpCourseId(long spCourseId) {
		_columnBitmask |= SPCOURSEID_COLUMN_BITMASK;

		if (!_setOriginalSpCourseId) {
			_setOriginalSpCourseId = true;

			_originalSpCourseId = _spCourseId;
		}

		_spCourseId = spCourseId;
	}

	public long getOriginalSpCourseId() {
		return _originalSpCourseId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public String getDesc() {
		if (_desc == null) {
			return StringPool.BLANK;
		}
		else {
			return _desc;
		}
	}

	@Override
	public void setDesc(String desc) {
		_desc = desc;
	}

	@Override
	public long getCoverImageFileEntryId() {
		return _coverImageFileEntryId;
	}

	@Override
	public void setCoverImageFileEntryId(long coverImageFileEntryId) {
		_coverImageFileEntryId = coverImageFileEntryId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			StudyOption.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StudyOption toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (StudyOption)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StudyOptionImpl studyOptionImpl = new StudyOptionImpl();

		studyOptionImpl.setSpStudyOptionId(getSpStudyOptionId());
		studyOptionImpl.setGroupId(getGroupId());
		studyOptionImpl.setCompanyId(getCompanyId());
		studyOptionImpl.setUserId(getUserId());
		studyOptionImpl.setUserName(getUserName());
		studyOptionImpl.setCreateDate(getCreateDate());
		studyOptionImpl.setModifiedDate(getModifiedDate());
		studyOptionImpl.setSpCourseId(getSpCourseId());
		studyOptionImpl.setTitle(getTitle());
		studyOptionImpl.setDesc(getDesc());
		studyOptionImpl.setCoverImageFileEntryId(getCoverImageFileEntryId());

		studyOptionImpl.resetOriginalValues();

		return studyOptionImpl;
	}

	@Override
	public int compareTo(StudyOption studyOption) {
		long primaryKey = studyOption.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StudyOption)) {
			return false;
		}

		StudyOption studyOption = (StudyOption)obj;

		long primaryKey = studyOption.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		StudyOptionModelImpl studyOptionModelImpl = this;

		studyOptionModelImpl._originalSpCourseId = studyOptionModelImpl._spCourseId;

		studyOptionModelImpl._setOriginalSpCourseId = false;

		studyOptionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<StudyOption> toCacheModel() {
		StudyOptionCacheModel studyOptionCacheModel = new StudyOptionCacheModel();

		studyOptionCacheModel.spStudyOptionId = getSpStudyOptionId();

		studyOptionCacheModel.groupId = getGroupId();

		studyOptionCacheModel.companyId = getCompanyId();

		studyOptionCacheModel.userId = getUserId();

		studyOptionCacheModel.userName = getUserName();

		String userName = studyOptionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			studyOptionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			studyOptionCacheModel.createDate = createDate.getTime();
		}
		else {
			studyOptionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			studyOptionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			studyOptionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		studyOptionCacheModel.spCourseId = getSpCourseId();

		studyOptionCacheModel.title = getTitle();

		String title = studyOptionCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			studyOptionCacheModel.title = null;
		}

		studyOptionCacheModel.desc = getDesc();

		String desc = studyOptionCacheModel.desc;

		if ((desc != null) && (desc.length() == 0)) {
			studyOptionCacheModel.desc = null;
		}

		studyOptionCacheModel.coverImageFileEntryId = getCoverImageFileEntryId();

		return studyOptionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{spStudyOptionId=");
		sb.append(getSpStudyOptionId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", spCourseId=");
		sb.append(getSpCourseId());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", desc=");
		sb.append(getDesc());
		sb.append(", coverImageFileEntryId=");
		sb.append(getCoverImageFileEntryId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.sambaash.platform.srv.model.StudyOption");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>spStudyOptionId</column-name><column-value><![CDATA[");
		sb.append(getSpStudyOptionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>spCourseId</column-name><column-value><![CDATA[");
		sb.append(getSpCourseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>desc</column-name><column-value><![CDATA[");
		sb.append(getDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>coverImageFileEntryId</column-name><column-value><![CDATA[");
		sb.append(getCoverImageFileEntryId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = StudyOption.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			StudyOption.class
		};
	private long _spStudyOptionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _spCourseId;
	private long _originalSpCourseId;
	private boolean _setOriginalSpCourseId;
	private String _title;
	private String _desc;
	private long _coverImageFileEntryId;
	private long _columnBitmask;
	private StudyOption _escapedModel;
}