/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.spservices.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.spservices.model.MembershipSubscribedServices;
import com.sambaash.platform.srv.spservices.model.MembershipSubscribedServicesModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the MembershipSubscribedServices service. Represents a row in the &quot;SPMembershipSubscribedServices&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.spservices.model.MembershipSubscribedServicesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MembershipSubscribedServicesImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see MembershipSubscribedServicesImpl
 * @see com.sambaash.platform.srv.spservices.model.MembershipSubscribedServices
 * @see com.sambaash.platform.srv.spservices.model.MembershipSubscribedServicesModel
 * @generated
 */
public class MembershipSubscribedServicesModelImpl extends BaseModelImpl<MembershipSubscribedServices>
	implements MembershipSubscribedServicesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a membership subscribed services model instance should use the {@link com.sambaash.platform.srv.spservices.model.MembershipSubscribedServices} interface instead.
	 */
	public static final String TABLE_NAME = "SPMembershipSubscribedServices";
	public static final Object[][] TABLE_COLUMNS = {
			{ "mssId", Types.BIGINT },
			{ "userid", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "scId", Types.VARCHAR },
			{ "scName", Types.VARCHAR },
			{ "count", Types.VARCHAR },
			{ "status", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "dateAdded", Types.TIMESTAMP },
			{ "dateModified", Types.TIMESTAMP },
			{ "createdBy", Types.VARCHAR },
			{ "modifiedBy", Types.VARCHAR },
			{ "effectiveFromDate", Types.TIMESTAMP },
			{ "effectiveToDate", Types.TIMESTAMP },
			{ "paramFrom", Types.VARCHAR },
			{ "paramUpto", Types.VARCHAR },
			{ "duration", Types.VARCHAR },
			{ "durationType", Types.VARCHAR },
			{ "serviceCharges", Types.FLOAT },
			{ "serviceChargesCurrency", Types.VARCHAR },
			{ "serviceChargesPeriod", Types.VARCHAR },
			{ "serviceChargesPeriodType", Types.VARCHAR },
			{ "extra1", Types.VARCHAR },
			{ "extra2", Types.VARCHAR },
			{ "extra3", Types.VARCHAR },
			{ "extra4", Types.VARCHAR },
			{ "extra5", Types.TIMESTAMP },
			{ "extra6", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table SPMembershipSubscribedServices (mssId BIGINT(20) not null primary key,userid BIGINT(20),companyId BIGINT(20),scId VARCHAR(75) null,scName VARCHAR(75) null,count VARCHAR(75) null,status VARCHAR(75) null,description VARCHAR(75) null,dateAdded DATETIME null,dateModified DATETIME null,createdBy VARCHAR(75) null,modifiedBy VARCHAR(75) null,effectiveFromDate DATETIME null,effectiveToDate DATETIME null,paramFrom VARCHAR(75) null,paramUpto VARCHAR(75) null,duration VARCHAR(75) null,durationType VARCHAR(75) null,serviceCharges DOUBLE,serviceChargesCurrency VARCHAR(75) null,serviceChargesPeriod VARCHAR(75) null,serviceChargesPeriodType VARCHAR(75) null,extra1 VARCHAR(75) null,extra2 VARCHAR(75) null,extra3 VARCHAR(75) null,extra4 VARCHAR(75) null,extra5 DATETIME null,extra6 DATETIME null)";
	public static final String TABLE_SQL_DROP = "drop table SPMembershipSubscribedServices";
	public static final String ORDER_BY_JPQL = " ORDER BY membershipSubscribedServices.scName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPMembershipSubscribedServices.scName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.spservices.model.MembershipSubscribedServices"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.spservices.model.MembershipSubscribedServices"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.spservices.model.MembershipSubscribedServices"),
			true);
	public static long CREATEDBY_COLUMN_BITMASK = 1L;
	public static long SCID_COLUMN_BITMASK = 2L;
	public static long SCNAME_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.spservices.model.MembershipSubscribedServices"));

	public MembershipSubscribedServicesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mssId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMssId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mssId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MembershipSubscribedServices.class;
	}

	@Override
	public String getModelClassName() {
		return MembershipSubscribedServices.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("mssId", getMssId());
		attributes.put("userid", getUserid());
		attributes.put("companyId", getCompanyId());
		attributes.put("scId", getScId());
		attributes.put("scName", getScName());
		attributes.put("count", getCount());
		attributes.put("status", getStatus());
		attributes.put("description", getDescription());
		attributes.put("dateAdded", getDateAdded());
		attributes.put("dateModified", getDateModified());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("modifiedBy", getModifiedBy());
		attributes.put("effectiveFromDate", getEffectiveFromDate());
		attributes.put("effectiveToDate", getEffectiveToDate());
		attributes.put("paramFrom", getParamFrom());
		attributes.put("paramUpto", getParamUpto());
		attributes.put("duration", getDuration());
		attributes.put("durationType", getDurationType());
		attributes.put("serviceCharges", getServiceCharges());
		attributes.put("serviceChargesCurrency", getServiceChargesCurrency());
		attributes.put("serviceChargesPeriod", getServiceChargesPeriod());
		attributes.put("serviceChargesPeriodType", getServiceChargesPeriodType());
		attributes.put("extra1", getExtra1());
		attributes.put("extra2", getExtra2());
		attributes.put("extra3", getExtra3());
		attributes.put("extra4", getExtra4());
		attributes.put("extra5", getExtra5());
		attributes.put("extra6", getExtra6());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long mssId = (Long)attributes.get("mssId");

		if (mssId != null) {
			setMssId(mssId);
		}

		Long userid = (Long)attributes.get("userid");

		if (userid != null) {
			setUserid(userid);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		String scId = (String)attributes.get("scId");

		if (scId != null) {
			setScId(scId);
		}

		String scName = (String)attributes.get("scName");

		if (scName != null) {
			setScName(scName);
		}

		String count = (String)attributes.get("count");

		if (count != null) {
			setCount(count);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Date dateAdded = (Date)attributes.get("dateAdded");

		if (dateAdded != null) {
			setDateAdded(dateAdded);
		}

		Date dateModified = (Date)attributes.get("dateModified");

		if (dateModified != null) {
			setDateModified(dateModified);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		String modifiedBy = (String)attributes.get("modifiedBy");

		if (modifiedBy != null) {
			setModifiedBy(modifiedBy);
		}

		Date effectiveFromDate = (Date)attributes.get("effectiveFromDate");

		if (effectiveFromDate != null) {
			setEffectiveFromDate(effectiveFromDate);
		}

		Date effectiveToDate = (Date)attributes.get("effectiveToDate");

		if (effectiveToDate != null) {
			setEffectiveToDate(effectiveToDate);
		}

		String paramFrom = (String)attributes.get("paramFrom");

		if (paramFrom != null) {
			setParamFrom(paramFrom);
		}

		String paramUpto = (String)attributes.get("paramUpto");

		if (paramUpto != null) {
			setParamUpto(paramUpto);
		}

		String duration = (String)attributes.get("duration");

		if (duration != null) {
			setDuration(duration);
		}

		String durationType = (String)attributes.get("durationType");

		if (durationType != null) {
			setDurationType(durationType);
		}

		Float serviceCharges = (Float)attributes.get("serviceCharges");

		if (serviceCharges != null) {
			setServiceCharges(serviceCharges);
		}

		String serviceChargesCurrency = (String)attributes.get(
				"serviceChargesCurrency");

		if (serviceChargesCurrency != null) {
			setServiceChargesCurrency(serviceChargesCurrency);
		}

		String serviceChargesPeriod = (String)attributes.get(
				"serviceChargesPeriod");

		if (serviceChargesPeriod != null) {
			setServiceChargesPeriod(serviceChargesPeriod);
		}

		String serviceChargesPeriodType = (String)attributes.get(
				"serviceChargesPeriodType");

		if (serviceChargesPeriodType != null) {
			setServiceChargesPeriodType(serviceChargesPeriodType);
		}

		String extra1 = (String)attributes.get("extra1");

		if (extra1 != null) {
			setExtra1(extra1);
		}

		String extra2 = (String)attributes.get("extra2");

		if (extra2 != null) {
			setExtra2(extra2);
		}

		String extra3 = (String)attributes.get("extra3");

		if (extra3 != null) {
			setExtra3(extra3);
		}

		String extra4 = (String)attributes.get("extra4");

		if (extra4 != null) {
			setExtra4(extra4);
		}

		Date extra5 = (Date)attributes.get("extra5");

		if (extra5 != null) {
			setExtra5(extra5);
		}

		Date extra6 = (Date)attributes.get("extra6");

		if (extra6 != null) {
			setExtra6(extra6);
		}
	}

	@Override
	public long getMssId() {
		return _mssId;
	}

	@Override
	public void setMssId(long mssId) {
		_mssId = mssId;
	}

	@Override
	public long getUserid() {
		return _userid;
	}

	@Override
	public void setUserid(long userid) {
		_userid = userid;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public String getScId() {
		if (_scId == null) {
			return StringPool.BLANK;
		}
		else {
			return _scId;
		}
	}

	@Override
	public void setScId(String scId) {
		_columnBitmask |= SCID_COLUMN_BITMASK;

		if (_originalScId == null) {
			_originalScId = _scId;
		}

		_scId = scId;
	}

	public String getOriginalScId() {
		return GetterUtil.getString(_originalScId);
	}

	@Override
	public String getScName() {
		if (_scName == null) {
			return StringPool.BLANK;
		}
		else {
			return _scName;
		}
	}

	@Override
	public void setScName(String scName) {
		_columnBitmask = -1L;

		_scName = scName;
	}

	@Override
	public String getCount() {
		if (_count == null) {
			return StringPool.BLANK;
		}
		else {
			return _count;
		}
	}

	@Override
	public void setCount(String count) {
		_count = count;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public Date getDateAdded() {
		return _dateAdded;
	}

	@Override
	public void setDateAdded(Date dateAdded) {
		_dateAdded = dateAdded;
	}

	@Override
	public Date getDateModified() {
		return _dateModified;
	}

	@Override
	public void setDateModified(Date dateModified) {
		_dateModified = dateModified;
	}

	@Override
	public String getCreatedBy() {
		if (_createdBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdBy;
		}
	}

	@Override
	public void setCreatedBy(String createdBy) {
		_columnBitmask |= CREATEDBY_COLUMN_BITMASK;

		if (_originalCreatedBy == null) {
			_originalCreatedBy = _createdBy;
		}

		_createdBy = createdBy;
	}

	public String getOriginalCreatedBy() {
		return GetterUtil.getString(_originalCreatedBy);
	}

	@Override
	public String getModifiedBy() {
		if (_modifiedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _modifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getEffectiveFromDate() {
		return _effectiveFromDate;
	}

	@Override
	public void setEffectiveFromDate(Date effectiveFromDate) {
		_effectiveFromDate = effectiveFromDate;
	}

	@Override
	public Date getEffectiveToDate() {
		return _effectiveToDate;
	}

	@Override
	public void setEffectiveToDate(Date effectiveToDate) {
		_effectiveToDate = effectiveToDate;
	}

	@Override
	public String getParamFrom() {
		if (_paramFrom == null) {
			return StringPool.BLANK;
		}
		else {
			return _paramFrom;
		}
	}

	@Override
	public void setParamFrom(String paramFrom) {
		_paramFrom = paramFrom;
	}

	@Override
	public String getParamUpto() {
		if (_paramUpto == null) {
			return StringPool.BLANK;
		}
		else {
			return _paramUpto;
		}
	}

	@Override
	public void setParamUpto(String paramUpto) {
		_paramUpto = paramUpto;
	}

	@Override
	public String getDuration() {
		if (_duration == null) {
			return StringPool.BLANK;
		}
		else {
			return _duration;
		}
	}

	@Override
	public void setDuration(String duration) {
		_duration = duration;
	}

	@Override
	public String getDurationType() {
		if (_durationType == null) {
			return StringPool.BLANK;
		}
		else {
			return _durationType;
		}
	}

	@Override
	public void setDurationType(String durationType) {
		_durationType = durationType;
	}

	@Override
	public float getServiceCharges() {
		return _serviceCharges;
	}

	@Override
	public void setServiceCharges(float serviceCharges) {
		_serviceCharges = serviceCharges;
	}

	@Override
	public String getServiceChargesCurrency() {
		if (_serviceChargesCurrency == null) {
			return StringPool.BLANK;
		}
		else {
			return _serviceChargesCurrency;
		}
	}

	@Override
	public void setServiceChargesCurrency(String serviceChargesCurrency) {
		_serviceChargesCurrency = serviceChargesCurrency;
	}

	@Override
	public String getServiceChargesPeriod() {
		if (_serviceChargesPeriod == null) {
			return StringPool.BLANK;
		}
		else {
			return _serviceChargesPeriod;
		}
	}

	@Override
	public void setServiceChargesPeriod(String serviceChargesPeriod) {
		_serviceChargesPeriod = serviceChargesPeriod;
	}

	@Override
	public String getServiceChargesPeriodType() {
		if (_serviceChargesPeriodType == null) {
			return StringPool.BLANK;
		}
		else {
			return _serviceChargesPeriodType;
		}
	}

	@Override
	public void setServiceChargesPeriodType(String serviceChargesPeriodType) {
		_serviceChargesPeriodType = serviceChargesPeriodType;
	}

	@Override
	public String getExtra1() {
		if (_extra1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _extra1;
		}
	}

	@Override
	public void setExtra1(String extra1) {
		_extra1 = extra1;
	}

	@Override
	public String getExtra2() {
		if (_extra2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _extra2;
		}
	}

	@Override
	public void setExtra2(String extra2) {
		_extra2 = extra2;
	}

	@Override
	public String getExtra3() {
		if (_extra3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _extra3;
		}
	}

	@Override
	public void setExtra3(String extra3) {
		_extra3 = extra3;
	}

	@Override
	public String getExtra4() {
		if (_extra4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _extra4;
		}
	}

	@Override
	public void setExtra4(String extra4) {
		_extra4 = extra4;
	}

	@Override
	public Date getExtra5() {
		return _extra5;
	}

	@Override
	public void setExtra5(Date extra5) {
		_extra5 = extra5;
	}

	@Override
	public Date getExtra6() {
		return _extra6;
	}

	@Override
	public void setExtra6(Date extra6) {
		_extra6 = extra6;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MembershipSubscribedServices.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MembershipSubscribedServices toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MembershipSubscribedServices)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MembershipSubscribedServicesImpl membershipSubscribedServicesImpl = new MembershipSubscribedServicesImpl();

		membershipSubscribedServicesImpl.setMssId(getMssId());
		membershipSubscribedServicesImpl.setUserid(getUserid());
		membershipSubscribedServicesImpl.setCompanyId(getCompanyId());
		membershipSubscribedServicesImpl.setScId(getScId());
		membershipSubscribedServicesImpl.setScName(getScName());
		membershipSubscribedServicesImpl.setCount(getCount());
		membershipSubscribedServicesImpl.setStatus(getStatus());
		membershipSubscribedServicesImpl.setDescription(getDescription());
		membershipSubscribedServicesImpl.setDateAdded(getDateAdded());
		membershipSubscribedServicesImpl.setDateModified(getDateModified());
		membershipSubscribedServicesImpl.setCreatedBy(getCreatedBy());
		membershipSubscribedServicesImpl.setModifiedBy(getModifiedBy());
		membershipSubscribedServicesImpl.setEffectiveFromDate(getEffectiveFromDate());
		membershipSubscribedServicesImpl.setEffectiveToDate(getEffectiveToDate());
		membershipSubscribedServicesImpl.setParamFrom(getParamFrom());
		membershipSubscribedServicesImpl.setParamUpto(getParamUpto());
		membershipSubscribedServicesImpl.setDuration(getDuration());
		membershipSubscribedServicesImpl.setDurationType(getDurationType());
		membershipSubscribedServicesImpl.setServiceCharges(getServiceCharges());
		membershipSubscribedServicesImpl.setServiceChargesCurrency(getServiceChargesCurrency());
		membershipSubscribedServicesImpl.setServiceChargesPeriod(getServiceChargesPeriod());
		membershipSubscribedServicesImpl.setServiceChargesPeriodType(getServiceChargesPeriodType());
		membershipSubscribedServicesImpl.setExtra1(getExtra1());
		membershipSubscribedServicesImpl.setExtra2(getExtra2());
		membershipSubscribedServicesImpl.setExtra3(getExtra3());
		membershipSubscribedServicesImpl.setExtra4(getExtra4());
		membershipSubscribedServicesImpl.setExtra5(getExtra5());
		membershipSubscribedServicesImpl.setExtra6(getExtra6());

		membershipSubscribedServicesImpl.resetOriginalValues();

		return membershipSubscribedServicesImpl;
	}

	@Override
	public int compareTo(
		MembershipSubscribedServices membershipSubscribedServices) {
		int value = 0;

		value = getScName().compareTo(membershipSubscribedServices.getScName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MembershipSubscribedServices)) {
			return false;
		}

		MembershipSubscribedServices membershipSubscribedServices = (MembershipSubscribedServices)obj;

		long primaryKey = membershipSubscribedServices.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		MembershipSubscribedServicesModelImpl membershipSubscribedServicesModelImpl =
			this;

		membershipSubscribedServicesModelImpl._originalScId = membershipSubscribedServicesModelImpl._scId;

		membershipSubscribedServicesModelImpl._originalCreatedBy = membershipSubscribedServicesModelImpl._createdBy;

		membershipSubscribedServicesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MembershipSubscribedServices> toCacheModel() {
		MembershipSubscribedServicesCacheModel membershipSubscribedServicesCacheModel =
			new MembershipSubscribedServicesCacheModel();

		membershipSubscribedServicesCacheModel.mssId = getMssId();

		membershipSubscribedServicesCacheModel.userid = getUserid();

		membershipSubscribedServicesCacheModel.companyId = getCompanyId();

		membershipSubscribedServicesCacheModel.scId = getScId();

		String scId = membershipSubscribedServicesCacheModel.scId;

		if ((scId != null) && (scId.length() == 0)) {
			membershipSubscribedServicesCacheModel.scId = null;
		}

		membershipSubscribedServicesCacheModel.scName = getScName();

		String scName = membershipSubscribedServicesCacheModel.scName;

		if ((scName != null) && (scName.length() == 0)) {
			membershipSubscribedServicesCacheModel.scName = null;
		}

		membershipSubscribedServicesCacheModel.count = getCount();

		String count = membershipSubscribedServicesCacheModel.count;

		if ((count != null) && (count.length() == 0)) {
			membershipSubscribedServicesCacheModel.count = null;
		}

		membershipSubscribedServicesCacheModel.status = getStatus();

		String status = membershipSubscribedServicesCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			membershipSubscribedServicesCacheModel.status = null;
		}

		membershipSubscribedServicesCacheModel.description = getDescription();

		String description = membershipSubscribedServicesCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			membershipSubscribedServicesCacheModel.description = null;
		}

		Date dateAdded = getDateAdded();

		if (dateAdded != null) {
			membershipSubscribedServicesCacheModel.dateAdded = dateAdded.getTime();
		}
		else {
			membershipSubscribedServicesCacheModel.dateAdded = Long.MIN_VALUE;
		}

		Date dateModified = getDateModified();

		if (dateModified != null) {
			membershipSubscribedServicesCacheModel.dateModified = dateModified.getTime();
		}
		else {
			membershipSubscribedServicesCacheModel.dateModified = Long.MIN_VALUE;
		}

		membershipSubscribedServicesCacheModel.createdBy = getCreatedBy();

		String createdBy = membershipSubscribedServicesCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			membershipSubscribedServicesCacheModel.createdBy = null;
		}

		membershipSubscribedServicesCacheModel.modifiedBy = getModifiedBy();

		String modifiedBy = membershipSubscribedServicesCacheModel.modifiedBy;

		if ((modifiedBy != null) && (modifiedBy.length() == 0)) {
			membershipSubscribedServicesCacheModel.modifiedBy = null;
		}

		Date effectiveFromDate = getEffectiveFromDate();

		if (effectiveFromDate != null) {
			membershipSubscribedServicesCacheModel.effectiveFromDate = effectiveFromDate.getTime();
		}
		else {
			membershipSubscribedServicesCacheModel.effectiveFromDate = Long.MIN_VALUE;
		}

		Date effectiveToDate = getEffectiveToDate();

		if (effectiveToDate != null) {
			membershipSubscribedServicesCacheModel.effectiveToDate = effectiveToDate.getTime();
		}
		else {
			membershipSubscribedServicesCacheModel.effectiveToDate = Long.MIN_VALUE;
		}

		membershipSubscribedServicesCacheModel.paramFrom = getParamFrom();

		String paramFrom = membershipSubscribedServicesCacheModel.paramFrom;

		if ((paramFrom != null) && (paramFrom.length() == 0)) {
			membershipSubscribedServicesCacheModel.paramFrom = null;
		}

		membershipSubscribedServicesCacheModel.paramUpto = getParamUpto();

		String paramUpto = membershipSubscribedServicesCacheModel.paramUpto;

		if ((paramUpto != null) && (paramUpto.length() == 0)) {
			membershipSubscribedServicesCacheModel.paramUpto = null;
		}

		membershipSubscribedServicesCacheModel.duration = getDuration();

		String duration = membershipSubscribedServicesCacheModel.duration;

		if ((duration != null) && (duration.length() == 0)) {
			membershipSubscribedServicesCacheModel.duration = null;
		}

		membershipSubscribedServicesCacheModel.durationType = getDurationType();

		String durationType = membershipSubscribedServicesCacheModel.durationType;

		if ((durationType != null) && (durationType.length() == 0)) {
			membershipSubscribedServicesCacheModel.durationType = null;
		}

		membershipSubscribedServicesCacheModel.serviceCharges = getServiceCharges();

		membershipSubscribedServicesCacheModel.serviceChargesCurrency = getServiceChargesCurrency();

		String serviceChargesCurrency = membershipSubscribedServicesCacheModel.serviceChargesCurrency;

		if ((serviceChargesCurrency != null) &&
				(serviceChargesCurrency.length() == 0)) {
			membershipSubscribedServicesCacheModel.serviceChargesCurrency = null;
		}

		membershipSubscribedServicesCacheModel.serviceChargesPeriod = getServiceChargesPeriod();

		String serviceChargesPeriod = membershipSubscribedServicesCacheModel.serviceChargesPeriod;

		if ((serviceChargesPeriod != null) &&
				(serviceChargesPeriod.length() == 0)) {
			membershipSubscribedServicesCacheModel.serviceChargesPeriod = null;
		}

		membershipSubscribedServicesCacheModel.serviceChargesPeriodType = getServiceChargesPeriodType();

		String serviceChargesPeriodType = membershipSubscribedServicesCacheModel.serviceChargesPeriodType;

		if ((serviceChargesPeriodType != null) &&
				(serviceChargesPeriodType.length() == 0)) {
			membershipSubscribedServicesCacheModel.serviceChargesPeriodType = null;
		}

		membershipSubscribedServicesCacheModel.extra1 = getExtra1();

		String extra1 = membershipSubscribedServicesCacheModel.extra1;

		if ((extra1 != null) && (extra1.length() == 0)) {
			membershipSubscribedServicesCacheModel.extra1 = null;
		}

		membershipSubscribedServicesCacheModel.extra2 = getExtra2();

		String extra2 = membershipSubscribedServicesCacheModel.extra2;

		if ((extra2 != null) && (extra2.length() == 0)) {
			membershipSubscribedServicesCacheModel.extra2 = null;
		}

		membershipSubscribedServicesCacheModel.extra3 = getExtra3();

		String extra3 = membershipSubscribedServicesCacheModel.extra3;

		if ((extra3 != null) && (extra3.length() == 0)) {
			membershipSubscribedServicesCacheModel.extra3 = null;
		}

		membershipSubscribedServicesCacheModel.extra4 = getExtra4();

		String extra4 = membershipSubscribedServicesCacheModel.extra4;

		if ((extra4 != null) && (extra4.length() == 0)) {
			membershipSubscribedServicesCacheModel.extra4 = null;
		}

		Date extra5 = getExtra5();

		if (extra5 != null) {
			membershipSubscribedServicesCacheModel.extra5 = extra5.getTime();
		}
		else {
			membershipSubscribedServicesCacheModel.extra5 = Long.MIN_VALUE;
		}

		Date extra6 = getExtra6();

		if (extra6 != null) {
			membershipSubscribedServicesCacheModel.extra6 = extra6.getTime();
		}
		else {
			membershipSubscribedServicesCacheModel.extra6 = Long.MIN_VALUE;
		}

		return membershipSubscribedServicesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(57);

		sb.append("{mssId=");
		sb.append(getMssId());
		sb.append(", userid=");
		sb.append(getUserid());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", scId=");
		sb.append(getScId());
		sb.append(", scName=");
		sb.append(getScName());
		sb.append(", count=");
		sb.append(getCount());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", dateAdded=");
		sb.append(getDateAdded());
		sb.append(", dateModified=");
		sb.append(getDateModified());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", modifiedBy=");
		sb.append(getModifiedBy());
		sb.append(", effectiveFromDate=");
		sb.append(getEffectiveFromDate());
		sb.append(", effectiveToDate=");
		sb.append(getEffectiveToDate());
		sb.append(", paramFrom=");
		sb.append(getParamFrom());
		sb.append(", paramUpto=");
		sb.append(getParamUpto());
		sb.append(", duration=");
		sb.append(getDuration());
		sb.append(", durationType=");
		sb.append(getDurationType());
		sb.append(", serviceCharges=");
		sb.append(getServiceCharges());
		sb.append(", serviceChargesCurrency=");
		sb.append(getServiceChargesCurrency());
		sb.append(", serviceChargesPeriod=");
		sb.append(getServiceChargesPeriod());
		sb.append(", serviceChargesPeriodType=");
		sb.append(getServiceChargesPeriodType());
		sb.append(", extra1=");
		sb.append(getExtra1());
		sb.append(", extra2=");
		sb.append(getExtra2());
		sb.append(", extra3=");
		sb.append(getExtra3());
		sb.append(", extra4=");
		sb.append(getExtra4());
		sb.append(", extra5=");
		sb.append(getExtra5());
		sb.append(", extra6=");
		sb.append(getExtra6());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(88);

		sb.append("<model><model-name>");
		sb.append(
			"com.sambaash.platform.srv.spservices.model.MembershipSubscribedServices");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>mssId</column-name><column-value><![CDATA[");
		sb.append(getMssId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userid</column-name><column-value><![CDATA[");
		sb.append(getUserid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>scId</column-name><column-value><![CDATA[");
		sb.append(getScId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>scName</column-name><column-value><![CDATA[");
		sb.append(getScName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>count</column-name><column-value><![CDATA[");
		sb.append(getCount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dateAdded</column-name><column-value><![CDATA[");
		sb.append(getDateAdded());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dateModified</column-name><column-value><![CDATA[");
		sb.append(getDateModified());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>effectiveFromDate</column-name><column-value><![CDATA[");
		sb.append(getEffectiveFromDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>effectiveToDate</column-name><column-value><![CDATA[");
		sb.append(getEffectiveToDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>paramFrom</column-name><column-value><![CDATA[");
		sb.append(getParamFrom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>paramUpto</column-name><column-value><![CDATA[");
		sb.append(getParamUpto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>duration</column-name><column-value><![CDATA[");
		sb.append(getDuration());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>durationType</column-name><column-value><![CDATA[");
		sb.append(getDurationType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serviceCharges</column-name><column-value><![CDATA[");
		sb.append(getServiceCharges());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serviceChargesCurrency</column-name><column-value><![CDATA[");
		sb.append(getServiceChargesCurrency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serviceChargesPeriod</column-name><column-value><![CDATA[");
		sb.append(getServiceChargesPeriod());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serviceChargesPeriodType</column-name><column-value><![CDATA[");
		sb.append(getServiceChargesPeriodType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extra1</column-name><column-value><![CDATA[");
		sb.append(getExtra1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extra2</column-name><column-value><![CDATA[");
		sb.append(getExtra2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extra3</column-name><column-value><![CDATA[");
		sb.append(getExtra3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extra4</column-name><column-value><![CDATA[");
		sb.append(getExtra4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extra5</column-name><column-value><![CDATA[");
		sb.append(getExtra5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extra6</column-name><column-value><![CDATA[");
		sb.append(getExtra6());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = MembershipSubscribedServices.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			MembershipSubscribedServices.class
		};
	private long _mssId;
	private long _userid;
	private long _companyId;
	private String _scId;
	private String _originalScId;
	private String _scName;
	private String _count;
	private String _status;
	private String _description;
	private Date _dateAdded;
	private Date _dateModified;
	private String _createdBy;
	private String _originalCreatedBy;
	private String _modifiedBy;
	private Date _effectiveFromDate;
	private Date _effectiveToDate;
	private String _paramFrom;
	private String _paramUpto;
	private String _duration;
	private String _durationType;
	private float _serviceCharges;
	private String _serviceChargesCurrency;
	private String _serviceChargesPeriod;
	private String _serviceChargesPeriodType;
	private String _extra1;
	private String _extra2;
	private String _extra3;
	private String _extra4;
	private Date _extra5;
	private Date _extra6;
	private long _columnBitmask;
	private MembershipSubscribedServices _escapedModel;
}