/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.spchallenge.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SPChallengeApplicant service. Represents a row in the &quot;SPChallengeApplicant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.spchallenge.model.impl.SPChallengeApplicantModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.spchallenge.model.impl.SPChallengeApplicantImpl}.
 * </p>
 *
 * @author pradeep
 * @see SPChallengeApplicant
 * @see com.sambaash.platform.srv.spchallenge.model.impl.SPChallengeApplicantImpl
 * @see com.sambaash.platform.srv.spchallenge.model.impl.SPChallengeApplicantModelImpl
 * @generated
 */
public interface SPChallengeApplicantModel extends BaseModel<SPChallengeApplicant>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s p challenge applicant model instance should use the {@link SPChallengeApplicant} interface instead.
	 */

	/**
	 * Returns the primary key of this s p challenge applicant.
	 *
	 * @return the primary key of this s p challenge applicant
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s p challenge applicant.
	 *
	 * @param primaryKey the primary key of this s p challenge applicant
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this s p challenge applicant.
	 *
	 * @return the uuid of this s p challenge applicant
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this s p challenge applicant.
	 *
	 * @param uuid the uuid of this s p challenge applicant
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sp challenge applicant ID of this s p challenge applicant.
	 *
	 * @return the sp challenge applicant ID of this s p challenge applicant
	 */
	public long getSpChallengeApplicantId();

	/**
	 * Sets the sp challenge applicant ID of this s p challenge applicant.
	 *
	 * @param spChallengeApplicantId the sp challenge applicant ID of this s p challenge applicant
	 */
	public void setSpChallengeApplicantId(long spChallengeApplicantId);

	/**
	 * Returns the group ID of this s p challenge applicant.
	 *
	 * @return the group ID of this s p challenge applicant
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this s p challenge applicant.
	 *
	 * @param groupId the group ID of this s p challenge applicant
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this s p challenge applicant.
	 *
	 * @return the company ID of this s p challenge applicant
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this s p challenge applicant.
	 *
	 * @param companyId the company ID of this s p challenge applicant
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this s p challenge applicant.
	 *
	 * @return the user ID of this s p challenge applicant
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this s p challenge applicant.
	 *
	 * @param userId the user ID of this s p challenge applicant
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s p challenge applicant.
	 *
	 * @return the user uuid of this s p challenge applicant
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s p challenge applicant.
	 *
	 * @param userUuid the user uuid of this s p challenge applicant
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this s p challenge applicant.
	 *
	 * @return the user name of this s p challenge applicant
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this s p challenge applicant.
	 *
	 * @param userName the user name of this s p challenge applicant
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this s p challenge applicant.
	 *
	 * @return the create date of this s p challenge applicant
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this s p challenge applicant.
	 *
	 * @param createDate the create date of this s p challenge applicant
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this s p challenge applicant.
	 *
	 * @return the modified date of this s p challenge applicant
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this s p challenge applicant.
	 *
	 * @param modifiedDate the modified date of this s p challenge applicant
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the applicant ref ID of this s p challenge applicant.
	 *
	 * @return the applicant ref ID of this s p challenge applicant
	 */
	public long getApplicantRefId();

	/**
	 * Sets the applicant ref ID of this s p challenge applicant.
	 *
	 * @param applicantRefId the applicant ref ID of this s p challenge applicant
	 */
	public void setApplicantRefId(long applicantRefId);

	/**
	 * Returns the applicant type of this s p challenge applicant.
	 *
	 * @return the applicant type of this s p challenge applicant
	 */
	@AutoEscape
	public String getApplicantType();

	/**
	 * Sets the applicant type of this s p challenge applicant.
	 *
	 * @param applicantType the applicant type of this s p challenge applicant
	 */
	public void setApplicantType(String applicantType);

	/**
	 * Returns the sp challenge ID of this s p challenge applicant.
	 *
	 * @return the sp challenge ID of this s p challenge applicant
	 */
	public long getSpChallengeId();

	/**
	 * Sets the sp challenge ID of this s p challenge applicant.
	 *
	 * @param spChallengeId the sp challenge ID of this s p challenge applicant
	 */
	public void setSpChallengeId(long spChallengeId);

	/**
	 * Returns the q1 of this s p challenge applicant.
	 *
	 * @return the q1 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ1();

	/**
	 * Sets the q1 of this s p challenge applicant.
	 *
	 * @param q1 the q1 of this s p challenge applicant
	 */
	public void setQ1(String q1);

	/**
	 * Returns the q2 of this s p challenge applicant.
	 *
	 * @return the q2 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ2();

	/**
	 * Sets the q2 of this s p challenge applicant.
	 *
	 * @param q2 the q2 of this s p challenge applicant
	 */
	public void setQ2(String q2);

	/**
	 * Returns the q3 of this s p challenge applicant.
	 *
	 * @return the q3 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ3();

	/**
	 * Sets the q3 of this s p challenge applicant.
	 *
	 * @param q3 the q3 of this s p challenge applicant
	 */
	public void setQ3(String q3);

	/**
	 * Returns the q4 of this s p challenge applicant.
	 *
	 * @return the q4 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ4();

	/**
	 * Sets the q4 of this s p challenge applicant.
	 *
	 * @param q4 the q4 of this s p challenge applicant
	 */
	public void setQ4(String q4);

	/**
	 * Returns the q5 of this s p challenge applicant.
	 *
	 * @return the q5 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ5();

	/**
	 * Sets the q5 of this s p challenge applicant.
	 *
	 * @param q5 the q5 of this s p challenge applicant
	 */
	public void setQ5(String q5);

	/**
	 * Returns the q6 of this s p challenge applicant.
	 *
	 * @return the q6 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ6();

	/**
	 * Sets the q6 of this s p challenge applicant.
	 *
	 * @param q6 the q6 of this s p challenge applicant
	 */
	public void setQ6(String q6);

	/**
	 * Returns the q7 of this s p challenge applicant.
	 *
	 * @return the q7 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ7();

	/**
	 * Sets the q7 of this s p challenge applicant.
	 *
	 * @param q7 the q7 of this s p challenge applicant
	 */
	public void setQ7(String q7);

	/**
	 * Returns the q8 of this s p challenge applicant.
	 *
	 * @return the q8 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ8();

	/**
	 * Sets the q8 of this s p challenge applicant.
	 *
	 * @param q8 the q8 of this s p challenge applicant
	 */
	public void setQ8(String q8);

	/**
	 * Returns the q9 of this s p challenge applicant.
	 *
	 * @return the q9 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ9();

	/**
	 * Sets the q9 of this s p challenge applicant.
	 *
	 * @param q9 the q9 of this s p challenge applicant
	 */
	public void setQ9(String q9);

	/**
	 * Returns the q10 of this s p challenge applicant.
	 *
	 * @return the q10 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ10();

	/**
	 * Sets the q10 of this s p challenge applicant.
	 *
	 * @param q10 the q10 of this s p challenge applicant
	 */
	public void setQ10(String q10);

	/**
	 * Returns the q11 of this s p challenge applicant.
	 *
	 * @return the q11 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ11();

	/**
	 * Sets the q11 of this s p challenge applicant.
	 *
	 * @param q11 the q11 of this s p challenge applicant
	 */
	public void setQ11(String q11);

	/**
	 * Returns the q12 of this s p challenge applicant.
	 *
	 * @return the q12 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ12();

	/**
	 * Sets the q12 of this s p challenge applicant.
	 *
	 * @param q12 the q12 of this s p challenge applicant
	 */
	public void setQ12(String q12);

	/**
	 * Returns the q13 of this s p challenge applicant.
	 *
	 * @return the q13 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ13();

	/**
	 * Sets the q13 of this s p challenge applicant.
	 *
	 * @param q13 the q13 of this s p challenge applicant
	 */
	public void setQ13(String q13);

	/**
	 * Returns the q14 of this s p challenge applicant.
	 *
	 * @return the q14 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ14();

	/**
	 * Sets the q14 of this s p challenge applicant.
	 *
	 * @param q14 the q14 of this s p challenge applicant
	 */
	public void setQ14(String q14);

	/**
	 * Returns the q15 of this s p challenge applicant.
	 *
	 * @return the q15 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ15();

	/**
	 * Sets the q15 of this s p challenge applicant.
	 *
	 * @param q15 the q15 of this s p challenge applicant
	 */
	public void setQ15(String q15);

	/**
	 * Returns the q16 of this s p challenge applicant.
	 *
	 * @return the q16 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ16();

	/**
	 * Sets the q16 of this s p challenge applicant.
	 *
	 * @param q16 the q16 of this s p challenge applicant
	 */
	public void setQ16(String q16);

	/**
	 * Returns the q17 of this s p challenge applicant.
	 *
	 * @return the q17 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ17();

	/**
	 * Sets the q17 of this s p challenge applicant.
	 *
	 * @param q17 the q17 of this s p challenge applicant
	 */
	public void setQ17(String q17);

	/**
	 * Returns the q18 of this s p challenge applicant.
	 *
	 * @return the q18 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ18();

	/**
	 * Sets the q18 of this s p challenge applicant.
	 *
	 * @param q18 the q18 of this s p challenge applicant
	 */
	public void setQ18(String q18);

	/**
	 * Returns the q19 of this s p challenge applicant.
	 *
	 * @return the q19 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ19();

	/**
	 * Sets the q19 of this s p challenge applicant.
	 *
	 * @param q19 the q19 of this s p challenge applicant
	 */
	public void setQ19(String q19);

	/**
	 * Returns the q20 of this s p challenge applicant.
	 *
	 * @return the q20 of this s p challenge applicant
	 */
	@AutoEscape
	public String getQ20();

	/**
	 * Sets the q20 of this s p challenge applicant.
	 *
	 * @param q20 the q20 of this s p challenge applicant
	 */
	public void setQ20(String q20);

	/**
	 * Returns the custom status1 of this s p challenge applicant.
	 *
	 * @return the custom status1 of this s p challenge applicant
	 */
	public boolean getCustomStatus1();

	/**
	 * Returns <code>true</code> if this s p challenge applicant is custom status1.
	 *
	 * @return <code>true</code> if this s p challenge applicant is custom status1; <code>false</code> otherwise
	 */
	public boolean isCustomStatus1();

	/**
	 * Sets whether this s p challenge applicant is custom status1.
	 *
	 * @param customStatus1 the custom status1 of this s p challenge applicant
	 */
	public void setCustomStatus1(boolean customStatus1);

	/**
	 * Returns the custom status2 of this s p challenge applicant.
	 *
	 * @return the custom status2 of this s p challenge applicant
	 */
	public boolean getCustomStatus2();

	/**
	 * Returns <code>true</code> if this s p challenge applicant is custom status2.
	 *
	 * @return <code>true</code> if this s p challenge applicant is custom status2; <code>false</code> otherwise
	 */
	public boolean isCustomStatus2();

	/**
	 * Sets whether this s p challenge applicant is custom status2.
	 *
	 * @param customStatus2 the custom status2 of this s p challenge applicant
	 */
	public void setCustomStatus2(boolean customStatus2);

	/**
	 * Returns the active of this s p challenge applicant.
	 *
	 * @return the active of this s p challenge applicant
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this s p challenge applicant is active.
	 *
	 * @return <code>true</code> if this s p challenge applicant is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this s p challenge applicant is active.
	 *
	 * @param active the active of this s p challenge applicant
	 */
	public void setActive(boolean active);

	/**
	 * Returns the application status of this s p challenge applicant.
	 *
	 * @return the application status of this s p challenge applicant
	 */
	public int getApplicationStatus();

	/**
	 * Sets the application status of this s p challenge applicant.
	 *
	 * @param applicationStatus the application status of this s p challenge applicant
	 */
	public void setApplicationStatus(int applicationStatus);

	/**
	 * Returns the notification status of this s p challenge applicant.
	 *
	 * @return the notification status of this s p challenge applicant
	 */
	public int getNotificationStatus();

	/**
	 * Sets the notification status of this s p challenge applicant.
	 *
	 * @param notificationStatus the notification status of this s p challenge applicant
	 */
	public void setNotificationStatus(int notificationStatus);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.spchallenge.model.SPChallengeApplicant spChallengeApplicant);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.spchallenge.model.SPChallengeApplicant> toCacheModel();

	@Override
	public com.sambaash.platform.srv.spchallenge.model.SPChallengeApplicant toEscapedModel();

	@Override
	public com.sambaash.platform.srv.spchallenge.model.SPChallengeApplicant toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}