/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.spdashboard.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SPAnalyticsConfig service. Represents a row in the &quot;SPAnalyticsConfig&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.spdashboard.model.impl.SPAnalyticsConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.spdashboard.model.impl.SPAnalyticsConfigImpl}.
 * </p>
 *
 * @author pradeep
 * @see SPAnalyticsConfig
 * @see com.sambaash.platform.srv.spdashboard.model.impl.SPAnalyticsConfigImpl
 * @see com.sambaash.platform.srv.spdashboard.model.impl.SPAnalyticsConfigModelImpl
 * @generated
 */
public interface SPAnalyticsConfigModel extends BaseModel<SPAnalyticsConfig> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s p analytics config model instance should use the {@link SPAnalyticsConfig} interface instead.
	 */

	/**
	 * Returns the primary key of this s p analytics config.
	 *
	 * @return the primary key of this s p analytics config
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s p analytics config.
	 *
	 * @param primaryKey the primary key of this s p analytics config
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp analytics config ID of this s p analytics config.
	 *
	 * @return the sp analytics config ID of this s p analytics config
	 */
	public long getSpAnalyticsConfigId();

	/**
	 * Sets the sp analytics config ID of this s p analytics config.
	 *
	 * @param spAnalyticsConfigId the sp analytics config ID of this s p analytics config
	 */
	public void setSpAnalyticsConfigId(long spAnalyticsConfigId);

	/**
	 * Returns the name of this s p analytics config.
	 *
	 * @return the name of this s p analytics config
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this s p analytics config.
	 *
	 * @param name the name of this s p analytics config
	 */
	public void setName(String name);

	/**
	 * Returns the config of this s p analytics config.
	 *
	 * @return the config of this s p analytics config
	 */
	@AutoEscape
	public String getConfig();

	/**
	 * Sets the config of this s p analytics config.
	 *
	 * @param config the config of this s p analytics config
	 */
	public void setConfig(String config);

	/**
	 * Returns the type of this s p analytics config.
	 *
	 * @return the type of this s p analytics config
	 */
	public int getType();

	/**
	 * Sets the type of this s p analytics config.
	 *
	 * @param type the type of this s p analytics config
	 */
	public void setType(int type);

	/**
	 * Returns the query of this s p analytics config.
	 *
	 * @return the query of this s p analytics config
	 */
	@AutoEscape
	public String getQuery();

	/**
	 * Sets the query of this s p analytics config.
	 *
	 * @param query the query of this s p analytics config
	 */
	public void setQuery(String query);

	/**
	 * Returns the war ID of this s p analytics config.
	 *
	 * @return the war ID of this s p analytics config
	 */
	@AutoEscape
	public String getWarId();

	/**
	 * Sets the war ID of this s p analytics config.
	 *
	 * @param warId the war ID of this s p analytics config
	 */
	public void setWarId(String warId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.spdashboard.model.SPAnalyticsConfig spAnalyticsConfig);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.spdashboard.model.SPAnalyticsConfig> toCacheModel();

	@Override
	public com.sambaash.platform.srv.spdashboard.model.SPAnalyticsConfig toEscapedModel();

	@Override
	public com.sambaash.platform.srv.spdashboard.model.SPAnalyticsConfig toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}