/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.processbuilder.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.processbuilder.model.PEDummyEntity;
import com.sambaash.platform.srv.processbuilder.model.PEDummyEntityModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PEDummyEntity service. Represents a row in the &quot;SPPEDummyEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.processbuilder.model.PEDummyEntityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PEDummyEntityImpl}.
 * </p>
 *
 * @author nareshchebolu
 * @see PEDummyEntityImpl
 * @see com.sambaash.platform.srv.processbuilder.model.PEDummyEntity
 * @see com.sambaash.platform.srv.processbuilder.model.PEDummyEntityModel
 * @generated
 */
public class PEDummyEntityModelImpl extends BaseModelImpl<PEDummyEntity>
	implements PEDummyEntityModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a p e dummy entity model instance should use the {@link com.sambaash.platform.srv.processbuilder.model.PEDummyEntity} interface instead.
	 */
	public static final String TABLE_NAME = "SPPEDummyEntity";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "spPEDummyEntityId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SPPEDummyEntity (uuid_ VARCHAR(75) null,spPEDummyEntityId BIGINT(20) not null primary key,groupId BIGINT(20),companyId BIGINT(20),userId BIGINT(20),userName VARCHAR(75) null,createDate DATETIME null,modifiedDate DATETIME null,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SPPEDummyEntity";
	public static final String ORDER_BY_JPQL = " ORDER BY peDummyEntity.spPEDummyEntityId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPPEDummyEntity.spPEDummyEntityId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.processbuilder.model.PEDummyEntity"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.processbuilder.model.PEDummyEntity"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.processbuilder.model.PEDummyEntity"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long NAME_COLUMN_BITMASK = 4L;
	public static long SPPEDUMMYENTITYID_COLUMN_BITMASK = 8L;
	public static long UUID_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.processbuilder.model.PEDummyEntity"));

	public PEDummyEntityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _spPEDummyEntityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSpPEDummyEntityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _spPEDummyEntityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PEDummyEntity.class;
	}

	@Override
	public String getModelClassName() {
		return PEDummyEntity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("spPEDummyEntityId", getSpPEDummyEntityId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long spPEDummyEntityId = (Long)attributes.get("spPEDummyEntityId");

		if (spPEDummyEntityId != null) {
			setSpPEDummyEntityId(spPEDummyEntityId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getSpPEDummyEntityId() {
		return _spPEDummyEntityId;
	}

	@Override
	public void setSpPEDummyEntityId(long spPEDummyEntityId) {
		_columnBitmask |= SPPEDUMMYENTITYID_COLUMN_BITMASK;

		if (!_setOriginalSpPEDummyEntityId) {
			_setOriginalSpPEDummyEntityId = true;

			_originalSpPEDummyEntityId = _spPEDummyEntityId;
		}

		_spPEDummyEntityId = spPEDummyEntityId;
	}

	public long getOriginalSpPEDummyEntityId() {
		return _originalSpPEDummyEntityId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				PEDummyEntity.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PEDummyEntity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PEDummyEntity toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PEDummyEntity)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PEDummyEntityImpl peDummyEntityImpl = new PEDummyEntityImpl();

		peDummyEntityImpl.setUuid(getUuid());
		peDummyEntityImpl.setSpPEDummyEntityId(getSpPEDummyEntityId());
		peDummyEntityImpl.setGroupId(getGroupId());
		peDummyEntityImpl.setCompanyId(getCompanyId());
		peDummyEntityImpl.setUserId(getUserId());
		peDummyEntityImpl.setUserName(getUserName());
		peDummyEntityImpl.setCreateDate(getCreateDate());
		peDummyEntityImpl.setModifiedDate(getModifiedDate());
		peDummyEntityImpl.setName(getName());

		peDummyEntityImpl.resetOriginalValues();

		return peDummyEntityImpl;
	}

	@Override
	public int compareTo(PEDummyEntity peDummyEntity) {
		long primaryKey = peDummyEntity.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PEDummyEntity)) {
			return false;
		}

		PEDummyEntity peDummyEntity = (PEDummyEntity)obj;

		long primaryKey = peDummyEntity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PEDummyEntityModelImpl peDummyEntityModelImpl = this;

		peDummyEntityModelImpl._originalUuid = peDummyEntityModelImpl._uuid;

		peDummyEntityModelImpl._originalSpPEDummyEntityId = peDummyEntityModelImpl._spPEDummyEntityId;

		peDummyEntityModelImpl._setOriginalSpPEDummyEntityId = false;

		peDummyEntityModelImpl._originalGroupId = peDummyEntityModelImpl._groupId;

		peDummyEntityModelImpl._setOriginalGroupId = false;

		peDummyEntityModelImpl._originalCompanyId = peDummyEntityModelImpl._companyId;

		peDummyEntityModelImpl._setOriginalCompanyId = false;

		peDummyEntityModelImpl._originalName = peDummyEntityModelImpl._name;

		peDummyEntityModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PEDummyEntity> toCacheModel() {
		PEDummyEntityCacheModel peDummyEntityCacheModel = new PEDummyEntityCacheModel();

		peDummyEntityCacheModel.uuid = getUuid();

		String uuid = peDummyEntityCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			peDummyEntityCacheModel.uuid = null;
		}

		peDummyEntityCacheModel.spPEDummyEntityId = getSpPEDummyEntityId();

		peDummyEntityCacheModel.groupId = getGroupId();

		peDummyEntityCacheModel.companyId = getCompanyId();

		peDummyEntityCacheModel.userId = getUserId();

		peDummyEntityCacheModel.userName = getUserName();

		String userName = peDummyEntityCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			peDummyEntityCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			peDummyEntityCacheModel.createDate = createDate.getTime();
		}
		else {
			peDummyEntityCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			peDummyEntityCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			peDummyEntityCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		peDummyEntityCacheModel.name = getName();

		String name = peDummyEntityCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			peDummyEntityCacheModel.name = null;
		}

		return peDummyEntityCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", spPEDummyEntityId=");
		sb.append(getSpPEDummyEntityId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append(
			"com.sambaash.platform.srv.processbuilder.model.PEDummyEntity");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>spPEDummyEntityId</column-name><column-value><![CDATA[");
		sb.append(getSpPEDummyEntityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PEDummyEntity.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PEDummyEntity.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _spPEDummyEntityId;
	private long _originalSpPEDummyEntityId;
	private boolean _setOriginalSpPEDummyEntityId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _name;
	private String _originalName;
	private long _columnBitmask;
	private PEDummyEntity _escapedModel;
}