/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.processbuilder.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.processbuilder.model.PERuleSet;
import com.sambaash.platform.srv.processbuilder.model.PERuleSetModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PERuleSet service. Represents a row in the &quot;SPPERuleSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.processbuilder.model.PERuleSetModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PERuleSetImpl}.
 * </p>
 *
 * @author nareshchebolu
 * @see PERuleSetImpl
 * @see com.sambaash.platform.srv.processbuilder.model.PERuleSet
 * @see com.sambaash.platform.srv.processbuilder.model.PERuleSetModel
 * @generated
 */
public class PERuleSetModelImpl extends BaseModelImpl<PERuleSet>
	implements PERuleSetModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a p e rule set model instance should use the {@link com.sambaash.platform.srv.processbuilder.model.PERuleSet} interface instead.
	 */
	public static final String TABLE_NAME = "SPPERuleSet";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "spPERuleSetId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "componentType", Types.VARCHAR },
			{ "componentId", Types.VARCHAR },
			{ "status", Types.BIGINT },
			{ "formVersion", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SPPERuleSet (uuid_ VARCHAR(75) null,spPERuleSetId BIGINT(20) not null primary key,groupId BIGINT(20),companyId BIGINT(20),userId BIGINT(20),userName VARCHAR(75) null,createDate DATETIME null,modifiedDate DATETIME null,name VARCHAR(75) null,componentType VARCHAR(75) null,componentId VARCHAR(75) null,status BIGINT(20),formVersion VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SPPERuleSet";
	public static final String ORDER_BY_JPQL = " ORDER BY peRuleSet.spPERuleSetId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPPERuleSet.spPERuleSetId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.processbuilder.model.PERuleSet"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.processbuilder.model.PERuleSet"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.processbuilder.model.PERuleSet"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long COMPONENTTYPE_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;
	public static long SPPERULESETID_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.processbuilder.model.PERuleSet"));

	public PERuleSetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _spPERuleSetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSpPERuleSetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _spPERuleSetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PERuleSet.class;
	}

	@Override
	public String getModelClassName() {
		return PERuleSet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("spPERuleSetId", getSpPERuleSetId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("componentType", getComponentType());
		attributes.put("componentId", getComponentId());
		attributes.put("status", getStatus());
		attributes.put("formVersion", getFormVersion());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long spPERuleSetId = (Long)attributes.get("spPERuleSetId");

		if (spPERuleSetId != null) {
			setSpPERuleSetId(spPERuleSetId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String componentType = (String)attributes.get("componentType");

		if (componentType != null) {
			setComponentType(componentType);
		}

		String componentId = (String)attributes.get("componentId");

		if (componentId != null) {
			setComponentId(componentId);
		}

		Long status = (Long)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String formVersion = (String)attributes.get("formVersion");

		if (formVersion != null) {
			setFormVersion(formVersion);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getSpPERuleSetId() {
		return _spPERuleSetId;
	}

	@Override
	public void setSpPERuleSetId(long spPERuleSetId) {
		_spPERuleSetId = spPERuleSetId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getComponentType() {
		if (_componentType == null) {
			return StringPool.BLANK;
		}
		else {
			return _componentType;
		}
	}

	@Override
	public void setComponentType(String componentType) {
		_columnBitmask |= COMPONENTTYPE_COLUMN_BITMASK;

		if (_originalComponentType == null) {
			_originalComponentType = _componentType;
		}

		_componentType = componentType;
	}

	public String getOriginalComponentType() {
		return GetterUtil.getString(_originalComponentType);
	}

	@Override
	public String getComponentId() {
		if (_componentId == null) {
			return StringPool.BLANK;
		}
		else {
			return _componentId;
		}
	}

	@Override
	public void setComponentId(String componentId) {
		_componentId = componentId;
	}

	@Override
	public long getStatus() {
		return _status;
	}

	@Override
	public void setStatus(long status) {
		_status = status;
	}

	@Override
	public String getFormVersion() {
		if (_formVersion == null) {
			return StringPool.BLANK;
		}
		else {
			return _formVersion;
		}
	}

	@Override
	public void setFormVersion(String formVersion) {
		_formVersion = formVersion;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				PERuleSet.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PERuleSet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PERuleSet toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PERuleSet)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PERuleSetImpl peRuleSetImpl = new PERuleSetImpl();

		peRuleSetImpl.setUuid(getUuid());
		peRuleSetImpl.setSpPERuleSetId(getSpPERuleSetId());
		peRuleSetImpl.setGroupId(getGroupId());
		peRuleSetImpl.setCompanyId(getCompanyId());
		peRuleSetImpl.setUserId(getUserId());
		peRuleSetImpl.setUserName(getUserName());
		peRuleSetImpl.setCreateDate(getCreateDate());
		peRuleSetImpl.setModifiedDate(getModifiedDate());
		peRuleSetImpl.setName(getName());
		peRuleSetImpl.setComponentType(getComponentType());
		peRuleSetImpl.setComponentId(getComponentId());
		peRuleSetImpl.setStatus(getStatus());
		peRuleSetImpl.setFormVersion(getFormVersion());

		peRuleSetImpl.resetOriginalValues();

		return peRuleSetImpl;
	}

	@Override
	public int compareTo(PERuleSet peRuleSet) {
		long primaryKey = peRuleSet.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PERuleSet)) {
			return false;
		}

		PERuleSet peRuleSet = (PERuleSet)obj;

		long primaryKey = peRuleSet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PERuleSetModelImpl peRuleSetModelImpl = this;

		peRuleSetModelImpl._originalUuid = peRuleSetModelImpl._uuid;

		peRuleSetModelImpl._originalGroupId = peRuleSetModelImpl._groupId;

		peRuleSetModelImpl._setOriginalGroupId = false;

		peRuleSetModelImpl._originalCompanyId = peRuleSetModelImpl._companyId;

		peRuleSetModelImpl._setOriginalCompanyId = false;

		peRuleSetModelImpl._originalComponentType = peRuleSetModelImpl._componentType;

		peRuleSetModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PERuleSet> toCacheModel() {
		PERuleSetCacheModel peRuleSetCacheModel = new PERuleSetCacheModel();

		peRuleSetCacheModel.uuid = getUuid();

		String uuid = peRuleSetCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			peRuleSetCacheModel.uuid = null;
		}

		peRuleSetCacheModel.spPERuleSetId = getSpPERuleSetId();

		peRuleSetCacheModel.groupId = getGroupId();

		peRuleSetCacheModel.companyId = getCompanyId();

		peRuleSetCacheModel.userId = getUserId();

		peRuleSetCacheModel.userName = getUserName();

		String userName = peRuleSetCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			peRuleSetCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			peRuleSetCacheModel.createDate = createDate.getTime();
		}
		else {
			peRuleSetCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			peRuleSetCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			peRuleSetCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		peRuleSetCacheModel.name = getName();

		String name = peRuleSetCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			peRuleSetCacheModel.name = null;
		}

		peRuleSetCacheModel.componentType = getComponentType();

		String componentType = peRuleSetCacheModel.componentType;

		if ((componentType != null) && (componentType.length() == 0)) {
			peRuleSetCacheModel.componentType = null;
		}

		peRuleSetCacheModel.componentId = getComponentId();

		String componentId = peRuleSetCacheModel.componentId;

		if ((componentId != null) && (componentId.length() == 0)) {
			peRuleSetCacheModel.componentId = null;
		}

		peRuleSetCacheModel.status = getStatus();

		peRuleSetCacheModel.formVersion = getFormVersion();

		String formVersion = peRuleSetCacheModel.formVersion;

		if ((formVersion != null) && (formVersion.length() == 0)) {
			peRuleSetCacheModel.formVersion = null;
		}

		return peRuleSetCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", spPERuleSetId=");
		sb.append(getSpPERuleSetId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", componentType=");
		sb.append(getComponentType());
		sb.append(", componentId=");
		sb.append(getComponentId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", formVersion=");
		sb.append(getFormVersion());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.sambaash.platform.srv.processbuilder.model.PERuleSet");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>spPERuleSetId</column-name><column-value><![CDATA[");
		sb.append(getSpPERuleSetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>componentType</column-name><column-value><![CDATA[");
		sb.append(getComponentType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>componentId</column-name><column-value><![CDATA[");
		sb.append(getComponentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>formVersion</column-name><column-value><![CDATA[");
		sb.append(getFormVersion());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PERuleSet.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PERuleSet.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _spPERuleSetId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _name;
	private String _componentType;
	private String _originalComponentType;
	private String _componentId;
	private long _status;
	private String _formVersion;
	private long _columnBitmask;
	private PERuleSet _escapedModel;
}