/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.spsocialprofile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExamBodyUser service. Represents a row in the &quot;SPExamBodyUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.spsocialprofile.model.impl.ExamBodyUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.spsocialprofile.model.impl.ExamBodyUserImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see ExamBodyUser
 * @see com.sambaash.platform.srv.spsocialprofile.model.impl.ExamBodyUserImpl
 * @see com.sambaash.platform.srv.spsocialprofile.model.impl.ExamBodyUserModelImpl
 * @generated
 */
public interface ExamBodyUserModel extends BaseModel<ExamBodyUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a exam body user model instance should use the {@link ExamBodyUser} interface instead.
	 */

	/**
	 * Returns the primary key of this exam body user.
	 *
	 * @return the primary key of this exam body user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this exam body user.
	 *
	 * @param primaryKey the primary key of this exam body user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the exam body user ID of this exam body user.
	 *
	 * @return the exam body user ID of this exam body user
	 */
	public long getExamBodyUserId();

	/**
	 * Sets the exam body user ID of this exam body user.
	 *
	 * @param examBodyUserId the exam body user ID of this exam body user
	 */
	public void setExamBodyUserId(long examBodyUserId);

	/**
	 * Returns the exam body user uuid of this exam body user.
	 *
	 * @return the exam body user uuid of this exam body user
	 * @throws SystemException if a system exception occurred
	 */
	public String getExamBodyUserUuid() throws SystemException;

	/**
	 * Sets the exam body user uuid of this exam body user.
	 *
	 * @param examBodyUserUuid the exam body user uuid of this exam body user
	 */
	public void setExamBodyUserUuid(String examBodyUserUuid);

	/**
	 * Returns the group ID of this exam body user.
	 *
	 * @return the group ID of this exam body user
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this exam body user.
	 *
	 * @param groupId the group ID of this exam body user
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this exam body user.
	 *
	 * @return the company ID of this exam body user
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this exam body user.
	 *
	 * @param companyId the company ID of this exam body user
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this exam body user.
	 *
	 * @return the create date of this exam body user
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this exam body user.
	 *
	 * @param createDate the create date of this exam body user
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this exam body user.
	 *
	 * @return the modified date of this exam body user
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this exam body user.
	 *
	 * @param modifiedDate the modified date of this exam body user
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the email address of this exam body user.
	 *
	 * @return the email address of this exam body user
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this exam body user.
	 *
	 * @param emailAddress the email address of this exam body user
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the exam body of this exam body user.
	 *
	 * @return the exam body of this exam body user
	 */
	@AutoEscape
	public String getExamBody();

	/**
	 * Sets the exam body of this exam body user.
	 *
	 * @param examBody the exam body of this exam body user
	 */
	public void setExamBody(String examBody);

	/**
	 * Returns the active of this exam body user.
	 *
	 * @return the active of this exam body user
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this exam body user is active.
	 *
	 * @return <code>true</code> if this exam body user is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this exam body user is active.
	 *
	 * @param active the active of this exam body user
	 */
	public void setActive(boolean active);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.spsocialprofile.model.ExamBodyUser examBodyUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.spsocialprofile.model.ExamBodyUser> toCacheModel();

	@Override
	public com.sambaash.platform.srv.spsocialprofile.model.ExamBodyUser toEscapedModel();

	@Override
	public com.sambaash.platform.srv.spsocialprofile.model.ExamBodyUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}