create table SPChallenge (
	uuid_ VARCHAR(75) null,
	spChallengeId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(100) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	name VARCHAR(200) null,
	openTo VARCHAR(200) null,
	type_ VARCHAR(200) null,
	background LONGTEXT null,
	description LONGTEXT null,
	scope LONGTEXT null,
	benefits LONGTEXT null,
	budget VARCHAR(50) null,
	startDate DATETIME null,
	endDate DATETIME null,
	applyBy DATETIME null,
	extras LONGTEXT null,
	active_ BOOLEAN,
	notifyTo VARCHAR(2000) null,
	scout VARCHAR(300) null,
	logoId BIGINT(20),
	draft BOOLEAN,
	budgetCcySign VARCHAR(4) null,
	brand BIGINT(20),
	vpApprover VARCHAR(200) null,
	budgetApprover VARCHAR(200) null
);

create table SPChallengeApplicant (
	uuid_ VARCHAR(75) null,
	spChallengeApplicantId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	applicantRefId BIGINT(20),
	applicantType VARCHAR(75) null,
	spChallengeId BIGINT(20),
	q1 LONGTEXT null,
	q2 LONGTEXT null,
	q3 LONGTEXT null,
	q4 LONGTEXT null,
	q5 LONGTEXT null,
	q6 LONGTEXT null,
	q7 LONGTEXT null,
	q8 LONGTEXT null,
	q9 LONGTEXT null,
	q10 LONGTEXT null,
	q11 LONGTEXT null,
	q12 LONGTEXT null,
	q13 LONGTEXT null,
	q14 LONGTEXT null,
	q15 LONGTEXT null,
	q16 LONGTEXT null,
	q17 LONGTEXT null,
	q18 LONGTEXT null,
	q19 LONGTEXT null,
	q20 LONGTEXT null,
	customStatus1 BOOLEAN,
	customStatus2 BOOLEAN,
	active_ BOOLEAN,
	applicationStatus INTEGER,
	notificationStatus INTEGER
);