create table SPRsvp (
	uuid_ VARCHAR(75) null,
	spRsvpId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	title VARCHAR(500) null,
	description VARCHAR(1000) null,
	eventId BIGINT(20),
	spAssetTypeId BIGINT(20),
	status BOOLEAN,
	rsvpUrl VARCHAR(75) null,
	processing INTEGER,
	price VARCHAR(75) null,
	currency_ VARCHAR(75) null,
	tax VARCHAR(75) null,
	accountId VARCHAR(75) null,
	paymentFlag BOOLEAN,
	registerFlag BOOLEAN,
	ticketFlag BOOLEAN,
	dynamicSectionName VARCHAR(75) null,
	ccEmail BOOLEAN
);

create table SPRsvpCoParticipantDetail (
	uuid_ VARCHAR(75) null,
	spRsvpCoParticipantDetailId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	spRsvpDetailId BIGINT(20),
	spRsvpPaymentId BIGINT(20),
	userId BIGINT(20),
	firstName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	nric VARCHAR(75) null,
	identificationType VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	rsvpStatus INTEGER,
	attendance INTEGER,
	attendanceBy BIGINT(20),
	attendanceDate DATETIME null,
	ticketNumber VARCHAR(16) null
);

create table SPRsvpDetail (
	uuid_ VARCHAR(75) null,
	spRsvpDetailId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	spRsvpId BIGINT(20),
	userId BIGINT(20),
	firstName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	identifiactionType VARCHAR(75) null,
	nric VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	rsvpStatus INTEGER,
	source INTEGER,
	attendance INTEGER,
	attendanceBy BIGINT(20),
	attendanceDate DATETIME null,
	rsvpStatusDate DATETIME null,
	rsvpStatusBy BIGINT(20),
	numberOfPeople INTEGER,
	streetAddress1 VARCHAR(200) null,
	streetAddress2 VARCHAR(200) null,
	postalCode VARCHAR(75) null,
	city VARCHAR(75) null,
	country VARCHAR(75) null,
	state_ VARCHAR(75) null,
	gender VARCHAR(75) null,
	phoneNumber1 VARCHAR(16) null,
	phoneNumber2 VARCHAR(16) null,
	hearAboutUs VARCHAR(100) null,
	attendedWebinar VARCHAR(75) null,
	ageGroup VARCHAR(75) null,
	termsOfUse BOOLEAN,
	ageRestriction BOOLEAN
);

create table SPRsvpDiscount (
	uuid_ VARCHAR(75) null,
	spRsvpDiscountId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	spRsvpId BIGINT(20),
	spRsvpTicketId BIGINT(20),
	fromDate DATETIME null,
	toDate DATETIME null,
	noOfTickets INTEGER,
	discount DOUBLE,
	modifiedBy BIGINT(20)
);

create table SPRsvpPayment (
	uuid_ VARCHAR(75) null,
	spRsvpPaymentId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	spRsvpDetailId BIGINT(20),
	spRsvpId BIGINT(20),
	spRsvpTicketId BIGINT(20),
	spRsvpDiscountId BIGINT(20),
	spRsvpPromoCodeId BIGINT(20),
	price DOUBLE,
	numberOfPeople INTEGER,
	discount INTEGER,
	netTotal DOUBLE,
	ticketNumber VARCHAR(16) null,
	payerEmailAddress VARCHAR(75) null,
	receiverEmailAddress VARCHAR(75) null,
	transactionId VARCHAR(75) null,
	transactionStatus VARCHAR(75) null,
	transactionAmount DOUBLE,
	transactionDate DATETIME null,
	emailStatus BOOLEAN
);

create table SPRsvpPromoCode (
	uuid_ VARCHAR(75) null,
	spRsvpPromoCodeId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	spRsvpId BIGINT(20),
	spRsvpTicketId BIGINT(20),
	promoCode VARCHAR(75) null,
	fromDate DATETIME null,
	toDate DATETIME null,
	noOfTickets INTEGER,
	discount INTEGER,
	modifiedBy BIGINT(20)
);

create table SPRsvpTicket (
	uuid_ VARCHAR(75) null,
	spRsvpTicketId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	spRsvpId BIGINT(20),
	price DOUBLE,
	quantity INTEGER,
	soldQuantity INTEGER,
	ticketSequence INTEGER,
	lastSequenceNumber INTEGER,
	sequencePrefix VARCHAR(2) null,
	sequenceSuffix VARCHAR(2) null,
	ticketTemplateUrl VARCHAR(250) null,
	modifiedBy BIGINT(20)
);