/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.wtberks.configuration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ConfigurationProperty service. Represents a row in the &quot;ConfigurationProperty&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.wtberks.configuration.model.impl.ConfigurationPropertyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.wtberks.configuration.model.impl.ConfigurationPropertyImpl}.
 * </p>
 *
 * @author liferay
 * @see ConfigurationProperty
 * @see com.wtberks.configuration.model.impl.ConfigurationPropertyImpl
 * @see com.wtberks.configuration.model.impl.ConfigurationPropertyModelImpl
 * @generated
 */
public interface ConfigurationPropertyModel extends BaseModel<ConfigurationProperty>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a configuration property model instance should use the {@link ConfigurationProperty} interface instead.
	 */

	/**
	 * Returns the primary key of this configuration property.
	 *
	 * @return the primary key of this configuration property
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this configuration property.
	 *
	 * @param primaryKey the primary key of this configuration property
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this configuration property.
	 *
	 * @return the uuid of this configuration property
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this configuration property.
	 *
	 * @param uuid the uuid of this configuration property
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the configuration property ID of this configuration property.
	 *
	 * @return the configuration property ID of this configuration property
	 */
	public long getConfigurationPropertyId();

	/**
	 * Sets the configuration property ID of this configuration property.
	 *
	 * @param configurationPropertyId the configuration property ID of this configuration property
	 */
	public void setConfigurationPropertyId(long configurationPropertyId);

	/**
	 * Returns the group ID of this configuration property.
	 *
	 * @return the group ID of this configuration property
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this configuration property.
	 *
	 * @param groupId the group ID of this configuration property
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this configuration property.
	 *
	 * @return the company ID of this configuration property
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this configuration property.
	 *
	 * @param companyId the company ID of this configuration property
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this configuration property.
	 *
	 * @return the user ID of this configuration property
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this configuration property.
	 *
	 * @param userId the user ID of this configuration property
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this configuration property.
	 *
	 * @return the user uuid of this configuration property
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this configuration property.
	 *
	 * @param userUuid the user uuid of this configuration property
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this configuration property.
	 *
	 * @return the user name of this configuration property
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this configuration property.
	 *
	 * @param userName the user name of this configuration property
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this configuration property.
	 *
	 * @return the create date of this configuration property
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this configuration property.
	 *
	 * @param createDate the create date of this configuration property
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this configuration property.
	 *
	 * @return the modified date of this configuration property
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this configuration property.
	 *
	 * @param modifiedDate the modified date of this configuration property
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the key of this configuration property.
	 *
	 * @return the key of this configuration property
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this configuration property.
	 *
	 * @param key the key of this configuration property
	 */
	public void setKey(String key);

	/**
	 * Returns the value of this configuration property.
	 *
	 * @return the value of this configuration property
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this configuration property.
	 *
	 * @param value the value of this configuration property
	 */
	public void setValue(String value);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.wtberks.configuration.model.ConfigurationProperty configurationProperty);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.wtberks.configuration.model.ConfigurationProperty> toCacheModel();

	@Override
	public com.wtberks.configuration.model.ConfigurationProperty toEscapedModel();

	@Override
	public com.wtberks.configuration.model.ConfigurationProperty toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}