/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.template.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SPComponentTemplate service. Represents a row in the &quot;SPComponentTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.template.model.impl.SPComponentTemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.template.model.impl.SPComponentTemplateImpl}.
 * </p>
 *
 * @author WattabyteIT
 * @see SPComponentTemplate
 * @see com.sambaash.platform.srv.template.model.impl.SPComponentTemplateImpl
 * @see com.sambaash.platform.srv.template.model.impl.SPComponentTemplateModelImpl
 * @generated
 */
public interface SPComponentTemplateModel extends BaseModel<SPComponentTemplate>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s p component template model instance should use the {@link SPComponentTemplate} interface instead.
	 */

	/**
	 * Returns the primary key of this s p component template.
	 *
	 * @return the primary key of this s p component template
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s p component template.
	 *
	 * @param primaryKey the primary key of this s p component template
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this s p component template.
	 *
	 * @return the uuid of this s p component template
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this s p component template.
	 *
	 * @param uuid the uuid of this s p component template
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sp component template ID of this s p component template.
	 *
	 * @return the sp component template ID of this s p component template
	 */
	public long getSpComponentTemplateId();

	/**
	 * Sets the sp component template ID of this s p component template.
	 *
	 * @param spComponentTemplateId the sp component template ID of this s p component template
	 */
	public void setSpComponentTemplateId(long spComponentTemplateId);

	/**
	 * Returns the group ID of this s p component template.
	 *
	 * @return the group ID of this s p component template
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this s p component template.
	 *
	 * @param groupId the group ID of this s p component template
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this s p component template.
	 *
	 * @return the company ID of this s p component template
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this s p component template.
	 *
	 * @param companyId the company ID of this s p component template
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this s p component template.
	 *
	 * @return the user ID of this s p component template
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this s p component template.
	 *
	 * @param userId the user ID of this s p component template
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s p component template.
	 *
	 * @return the user uuid of this s p component template
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s p component template.
	 *
	 * @param userUuid the user uuid of this s p component template
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this s p component template.
	 *
	 * @return the user name of this s p component template
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this s p component template.
	 *
	 * @param userName the user name of this s p component template
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this s p component template.
	 *
	 * @return the create date of this s p component template
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this s p component template.
	 *
	 * @param createDate the create date of this s p component template
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this s p component template.
	 *
	 * @return the modified date of this s p component template
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this s p component template.
	 *
	 * @param modifiedDate the modified date of this s p component template
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this s p component template.
	 *
	 * @return the create by of this s p component template
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this s p component template.
	 *
	 * @param createBy the create by of this s p component template
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this s p component template.
	 *
	 * @return the modified by of this s p component template
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this s p component template.
	 *
	 * @param modifiedBy the modified by of this s p component template
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the sp template ID of this s p component template.
	 *
	 * @return the sp template ID of this s p component template
	 */
	public long getSpTemplateId();

	/**
	 * Sets the sp template ID of this s p component template.
	 *
	 * @param spTemplateId the sp template ID of this s p component template
	 */
	public void setSpTemplateId(long spTemplateId);

	/**
	 * Returns the level0 class name ID of this s p component template.
	 *
	 * @return the level0 class name ID of this s p component template
	 */
	public long getLevel0ClassNameId();

	/**
	 * Sets the level0 class name ID of this s p component template.
	 *
	 * @param level0ClassNameId the level0 class name ID of this s p component template
	 */
	public void setLevel0ClassNameId(long level0ClassNameId);

	/**
	 * Returns the level0 form ID of this s p component template.
	 *
	 * @return the level0 form ID of this s p component template
	 */
	public long getLevel0FormId();

	/**
	 * Sets the level0 form ID of this s p component template.
	 *
	 * @param level0FormId the level0 form ID of this s p component template
	 */
	public void setLevel0FormId(long level0FormId);

	/**
	 * Returns the level1 class name ID of this s p component template.
	 *
	 * @return the level1 class name ID of this s p component template
	 */
	public long getLevel1ClassNameId();

	/**
	 * Sets the level1 class name ID of this s p component template.
	 *
	 * @param level1ClassNameId the level1 class name ID of this s p component template
	 */
	public void setLevel1ClassNameId(long level1ClassNameId);

	/**
	 * Returns the level1 form ID of this s p component template.
	 *
	 * @return the level1 form ID of this s p component template
	 */
	public long getLevel1FormId();

	/**
	 * Sets the level1 form ID of this s p component template.
	 *
	 * @param level1FormId the level1 form ID of this s p component template
	 */
	public void setLevel1FormId(long level1FormId);

	/**
	 * Returns the level2 class name ID of this s p component template.
	 *
	 * @return the level2 class name ID of this s p component template
	 */
	public long getLevel2ClassNameId();

	/**
	 * Sets the level2 class name ID of this s p component template.
	 *
	 * @param level2ClassNameId the level2 class name ID of this s p component template
	 */
	public void setLevel2ClassNameId(long level2ClassNameId);

	/**
	 * Returns the level2 form ID of this s p component template.
	 *
	 * @return the level2 form ID of this s p component template
	 */
	public long getLevel2FormId();

	/**
	 * Sets the level2 form ID of this s p component template.
	 *
	 * @param level2FormId the level2 form ID of this s p component template
	 */
	public void setLevel2FormId(long level2FormId);

	/**
	 * Returns the level3 class name ID of this s p component template.
	 *
	 * @return the level3 class name ID of this s p component template
	 */
	public long getLevel3ClassNameId();

	/**
	 * Sets the level3 class name ID of this s p component template.
	 *
	 * @param level3ClassNameId the level3 class name ID of this s p component template
	 */
	public void setLevel3ClassNameId(long level3ClassNameId);

	/**
	 * Returns the level3 form ID of this s p component template.
	 *
	 * @return the level3 form ID of this s p component template
	 */
	public long getLevel3FormId();

	/**
	 * Sets the level3 form ID of this s p component template.
	 *
	 * @param level3FormId the level3 form ID of this s p component template
	 */
	public void setLevel3FormId(long level3FormId);

	/**
	 * Returns the level4 class name ID of this s p component template.
	 *
	 * @return the level4 class name ID of this s p component template
	 */
	public long getLevel4ClassNameId();

	/**
	 * Sets the level4 class name ID of this s p component template.
	 *
	 * @param level4ClassNameId the level4 class name ID of this s p component template
	 */
	public void setLevel4ClassNameId(long level4ClassNameId);

	/**
	 * Returns the level4 form ID of this s p component template.
	 *
	 * @return the level4 form ID of this s p component template
	 */
	public long getLevel4FormId();

	/**
	 * Sets the level4 form ID of this s p component template.
	 *
	 * @param level4FormId the level4 form ID of this s p component template
	 */
	public void setLevel4FormId(long level4FormId);

	/**
	 * Returns the level5 class name ID of this s p component template.
	 *
	 * @return the level5 class name ID of this s p component template
	 */
	public long getLevel5ClassNameId();

	/**
	 * Sets the level5 class name ID of this s p component template.
	 *
	 * @param level5ClassNameId the level5 class name ID of this s p component template
	 */
	public void setLevel5ClassNameId(long level5ClassNameId);

	/**
	 * Returns the level5 form ID of this s p component template.
	 *
	 * @return the level5 form ID of this s p component template
	 */
	public long getLevel5FormId();

	/**
	 * Sets the level5 form ID of this s p component template.
	 *
	 * @param level5FormId the level5 form ID of this s p component template
	 */
	public void setLevel5FormId(long level5FormId);

	/**
	 * Returns the level6 class name ID of this s p component template.
	 *
	 * @return the level6 class name ID of this s p component template
	 */
	public long getLevel6ClassNameId();

	/**
	 * Sets the level6 class name ID of this s p component template.
	 *
	 * @param level6ClassNameId the level6 class name ID of this s p component template
	 */
	public void setLevel6ClassNameId(long level6ClassNameId);

	/**
	 * Returns the level6 form ID of this s p component template.
	 *
	 * @return the level6 form ID of this s p component template
	 */
	public long getLevel6FormId();

	/**
	 * Sets the level6 form ID of this s p component template.
	 *
	 * @param level6FormId the level6 form ID of this s p component template
	 */
	public void setLevel6FormId(long level6FormId);

	/**
	 * Returns the level7 class name ID of this s p component template.
	 *
	 * @return the level7 class name ID of this s p component template
	 */
	public long getLevel7ClassNameId();

	/**
	 * Sets the level7 class name ID of this s p component template.
	 *
	 * @param level7ClassNameId the level7 class name ID of this s p component template
	 */
	public void setLevel7ClassNameId(long level7ClassNameId);

	/**
	 * Returns the level7 form ID of this s p component template.
	 *
	 * @return the level7 form ID of this s p component template
	 */
	public long getLevel7FormId();

	/**
	 * Sets the level7 form ID of this s p component template.
	 *
	 * @param level7FormId the level7 form ID of this s p component template
	 */
	public void setLevel7FormId(long level7FormId);

	/**
	 * Returns the level8 class name ID of this s p component template.
	 *
	 * @return the level8 class name ID of this s p component template
	 */
	public long getLevel8ClassNameId();

	/**
	 * Sets the level8 class name ID of this s p component template.
	 *
	 * @param level8ClassNameId the level8 class name ID of this s p component template
	 */
	public void setLevel8ClassNameId(long level8ClassNameId);

	/**
	 * Returns the level8 form ID of this s p component template.
	 *
	 * @return the level8 form ID of this s p component template
	 */
	public long getLevel8FormId();

	/**
	 * Sets the level8 form ID of this s p component template.
	 *
	 * @param level8FormId the level8 form ID of this s p component template
	 */
	public void setLevel8FormId(long level8FormId);

	/**
	 * Returns the level9 class name ID of this s p component template.
	 *
	 * @return the level9 class name ID of this s p component template
	 */
	public long getLevel9ClassNameId();

	/**
	 * Sets the level9 class name ID of this s p component template.
	 *
	 * @param level9ClassNameId the level9 class name ID of this s p component template
	 */
	public void setLevel9ClassNameId(long level9ClassNameId);

	/**
	 * Returns the level9 form ID of this s p component template.
	 *
	 * @return the level9 form ID of this s p component template
	 */
	public long getLevel9FormId();

	/**
	 * Sets the level9 form ID of this s p component template.
	 *
	 * @param level9FormId the level9 form ID of this s p component template
	 */
	public void setLevel9FormId(long level9FormId);

	/**
	 * Returns the level10 class name ID of this s p component template.
	 *
	 * @return the level10 class name ID of this s p component template
	 */
	public long getLevel10ClassNameId();

	/**
	 * Sets the level10 class name ID of this s p component template.
	 *
	 * @param level10ClassNameId the level10 class name ID of this s p component template
	 */
	public void setLevel10ClassNameId(long level10ClassNameId);

	/**
	 * Returns the level10 form ID of this s p component template.
	 *
	 * @return the level10 form ID of this s p component template
	 */
	public long getLevel10FormId();

	/**
	 * Sets the level10 form ID of this s p component template.
	 *
	 * @param level10FormId the level10 form ID of this s p component template
	 */
	public void setLevel10FormId(long level10FormId);

	/**
	 * Returns the status of this s p component template.
	 *
	 * @return the status of this s p component template
	 */
	public int getStatus();

	/**
	 * Sets the status of this s p component template.
	 *
	 * @param status the status of this s p component template
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.template.model.SPComponentTemplate spComponentTemplate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.template.model.SPComponentTemplate> toCacheModel();

	@Override
	public com.sambaash.platform.srv.template.model.SPComponentTemplate toEscapedModel();

	@Override
	public com.sambaash.platform.srv.template.model.SPComponentTemplate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}