/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.template.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SPTemplate service. Represents a row in the &quot;SPTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.template.model.impl.SPTemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.template.model.impl.SPTemplateImpl}.
 * </p>
 *
 * @author WattabyteIT
 * @see SPTemplate
 * @see com.sambaash.platform.srv.template.model.impl.SPTemplateImpl
 * @see com.sambaash.platform.srv.template.model.impl.SPTemplateModelImpl
 * @generated
 */
public interface SPTemplateModel extends AttachedModel, BaseModel<SPTemplate>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s p template model instance should use the {@link SPTemplate} interface instead.
	 */

	/**
	 * Returns the primary key of this s p template.
	 *
	 * @return the primary key of this s p template
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s p template.
	 *
	 * @param primaryKey the primary key of this s p template
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this s p template.
	 *
	 * @return the uuid of this s p template
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this s p template.
	 *
	 * @param uuid the uuid of this s p template
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sp template ID of this s p template.
	 *
	 * @return the sp template ID of this s p template
	 */
	public long getSpTemplateId();

	/**
	 * Sets the sp template ID of this s p template.
	 *
	 * @param spTemplateId the sp template ID of this s p template
	 */
	public void setSpTemplateId(long spTemplateId);

	/**
	 * Returns the group ID of this s p template.
	 *
	 * @return the group ID of this s p template
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this s p template.
	 *
	 * @param groupId the group ID of this s p template
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this s p template.
	 *
	 * @return the company ID of this s p template
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this s p template.
	 *
	 * @param companyId the company ID of this s p template
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this s p template.
	 *
	 * @return the user ID of this s p template
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this s p template.
	 *
	 * @param userId the user ID of this s p template
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s p template.
	 *
	 * @return the user uuid of this s p template
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s p template.
	 *
	 * @param userUuid the user uuid of this s p template
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this s p template.
	 *
	 * @return the user name of this s p template
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this s p template.
	 *
	 * @param userName the user name of this s p template
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this s p template.
	 *
	 * @return the create date of this s p template
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this s p template.
	 *
	 * @param createDate the create date of this s p template
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this s p template.
	 *
	 * @return the modified date of this s p template
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this s p template.
	 *
	 * @param modifiedDate the modified date of this s p template
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the create by of this s p template.
	 *
	 * @return the create by of this s p template
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this s p template.
	 *
	 * @param createBy the create by of this s p template
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the modified by of this s p template.
	 *
	 * @return the modified by of this s p template
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this s p template.
	 *
	 * @param modifiedBy the modified by of this s p template
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the fully qualified class name of this s p template.
	 *
	 * @return the fully qualified class name of this s p template
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this s p template.
	 *
	 * @return the class name ID of this s p template
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this s p template.
	 *
	 * @param classNameId the class name ID of this s p template
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this s p template.
	 *
	 * @return the class p k of this s p template
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this s p template.
	 *
	 * @param classPK the class p k of this s p template
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the template name of this s p template.
	 *
	 * @return the template name of this s p template
	 */
	@AutoEscape
	public String getTemplateName();

	/**
	 * Sets the template name of this s p template.
	 *
	 * @param templateName the template name of this s p template
	 */
	public void setTemplateName(String templateName);

	/**
	 * Returns the status of this s p template.
	 *
	 * @return the status of this s p template
	 */
	public int getStatus();

	/**
	 * Sets the status of this s p template.
	 *
	 * @param status the status of this s p template
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.template.model.SPTemplate spTemplate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.template.model.SPTemplate> toCacheModel();

	@Override
	public com.sambaash.platform.srv.template.model.SPTemplate toEscapedModel();

	@Override
	public com.sambaash.platform.srv.template.model.SPTemplate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}