create table SPJob (
	uuid_ VARCHAR(75) null,
	jobId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	createdBy BIGINT(20),
	createDate DATETIME null,
	modifiedDate DATETIME null,
	updatedBy BIGINT(20),
	experience VARCHAR(75) null,
	corporateName VARCHAR(75) null,
	corporateId BIGINT(20),
	jobTitle VARCHAR(75) null,
	jobType VARCHAR(75) null,
	jobLocation VARCHAR(75) null,
	jobDescription VARCHAR(75) null,
	status VARCHAR(75) null,
	autoMatch BOOLEAN,
	currency VARCHAR(75) null,
	salary DOUBLE,
	rate VARCHAR(75) null,
	startDate DATETIME null,
	endDate DATETIME null,
	closingDate DATETIME null,
	extra1 VARCHAR(75) null,
	extra2 VARCHAR(75) null,
	extra3 VARCHAR(75) null,
	extra4 VARCHAR(75) null,
	extra5 VARCHAR(75) null,
	notefto VARCHAR(75) null
);

create table SPJobApplicants (
	spJobApplicantsId BIGINT(20) not null primary key,
	jobId BIGINT(20),
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	createdBy BIGINT(20),
	updatedBy BIGINT(20),
	createDate DATETIME null,
	modifiedDate DATETIME null,
	firstName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	contactNumber VARCHAR(75) null,
	experience VARCHAR(75) null,
	resume VARCHAR(75) null,
	coverLetter VARCHAR(75) null,
	briefInfos VARCHAR(75) null,
	extra1 VARCHAR(75) null,
	extra2 VARCHAR(75) null,
	extra3 VARCHAR(75) null,
	extra4 VARCHAR(75) null,
	extra5 VARCHAR(75) null
);

create table SPJobApplicantsCustomizedPortfolio (
	jobApplyId BIGINT(20) not null,
	porfolioId BIGINT(20) not null,
	userId BIGINT(20),
	createdBy BIGINT(20),
	updatedBy BIGINT(20),
	createDate DATETIME null,
	modifiedDate DATETIME null,
	extra1 VARCHAR(75) null,
	extra2 VARCHAR(75) null,
	primary key (jobApplyId, porfolioId)
);