/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.mail.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SPMailCampaign service. Represents a row in the &quot;SPMailCampaign&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.mail.model.impl.SPMailCampaignModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.mail.model.impl.SPMailCampaignImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see SPMailCampaign
 * @see com.sambaash.platform.srv.mail.model.impl.SPMailCampaignImpl
 * @see com.sambaash.platform.srv.mail.model.impl.SPMailCampaignModelImpl
 * @generated
 */
public interface SPMailCampaignModel extends BaseModel<SPMailCampaign> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s p mail campaign model instance should use the {@link SPMailCampaign} interface instead.
	 */

	/**
	 * Returns the primary key of this s p mail campaign.
	 *
	 * @return the primary key of this s p mail campaign
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s p mail campaign.
	 *
	 * @param primaryKey the primary key of this s p mail campaign
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp mail campaign ID of this s p mail campaign.
	 *
	 * @return the sp mail campaign ID of this s p mail campaign
	 */
	public long getSpMailCampaignId();

	/**
	 * Sets the sp mail campaign ID of this s p mail campaign.
	 *
	 * @param spMailCampaignId the sp mail campaign ID of this s p mail campaign
	 */
	public void setSpMailCampaignId(long spMailCampaignId);

	/**
	 * Returns the group ID of this s p mail campaign.
	 *
	 * @return the group ID of this s p mail campaign
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this s p mail campaign.
	 *
	 * @param groupId the group ID of this s p mail campaign
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this s p mail campaign.
	 *
	 * @return the company ID of this s p mail campaign
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this s p mail campaign.
	 *
	 * @param companyId the company ID of this s p mail campaign
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the campaign name of this s p mail campaign.
	 *
	 * @return the campaign name of this s p mail campaign
	 */
	@AutoEscape
	public String getCampaignName();

	/**
	 * Sets the campaign name of this s p mail campaign.
	 *
	 * @param campaignName the campaign name of this s p mail campaign
	 */
	public void setCampaignName(String campaignName);

	/**
	 * Returns the category ID of this s p mail campaign.
	 *
	 * @return the category ID of this s p mail campaign
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this s p mail campaign.
	 *
	 * @param categoryId the category ID of this s p mail campaign
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the main tempalte ID of this s p mail campaign.
	 *
	 * @return the main tempalte ID of this s p mail campaign
	 */
	public long getMainTempalteId();

	/**
	 * Sets the main tempalte ID of this s p mail campaign.
	 *
	 * @param mainTempalteId the main tempalte ID of this s p mail campaign
	 */
	public void setMainTempalteId(long mainTempalteId);

	/**
	 * Returns the rem1 tempalte ID of this s p mail campaign.
	 *
	 * @return the rem1 tempalte ID of this s p mail campaign
	 */
	public long getRem1TempalteId();

	/**
	 * Sets the rem1 tempalte ID of this s p mail campaign.
	 *
	 * @param rem1TempalteId the rem1 tempalte ID of this s p mail campaign
	 */
	public void setRem1TempalteId(long rem1TempalteId);

	/**
	 * Returns the rem2 tempalte ID of this s p mail campaign.
	 *
	 * @return the rem2 tempalte ID of this s p mail campaign
	 */
	public long getRem2TempalteId();

	/**
	 * Sets the rem2 tempalte ID of this s p mail campaign.
	 *
	 * @param rem2TempalteId the rem2 tempalte ID of this s p mail campaign
	 */
	public void setRem2TempalteId(long rem2TempalteId);

	/**
	 * Returns the rem3 tempalte ID of this s p mail campaign.
	 *
	 * @return the rem3 tempalte ID of this s p mail campaign
	 */
	public long getRem3TempalteId();

	/**
	 * Sets the rem3 tempalte ID of this s p mail campaign.
	 *
	 * @param rem3TempalteId the rem3 tempalte ID of this s p mail campaign
	 */
	public void setRem3TempalteId(long rem3TempalteId);

	/**
	 * Returns the thankyou tempalte ID of this s p mail campaign.
	 *
	 * @return the thankyou tempalte ID of this s p mail campaign
	 */
	public long getThankyouTempalteId();

	/**
	 * Sets the thankyou tempalte ID of this s p mail campaign.
	 *
	 * @param thankyouTempalteId the thankyou tempalte ID of this s p mail campaign
	 */
	public void setThankyouTempalteId(long thankyouTempalteId);

	/**
	 * Returns the missedyou tempalte ID of this s p mail campaign.
	 *
	 * @return the missedyou tempalte ID of this s p mail campaign
	 */
	public long getMissedyouTempalteId();

	/**
	 * Sets the missedyou tempalte ID of this s p mail campaign.
	 *
	 * @param missedyouTempalteId the missedyou tempalte ID of this s p mail campaign
	 */
	public void setMissedyouTempalteId(long missedyouTempalteId);

	/**
	 * Returns the main scheduled date of this s p mail campaign.
	 *
	 * @return the main scheduled date of this s p mail campaign
	 */
	public Date getMainScheduledDate();

	/**
	 * Sets the main scheduled date of this s p mail campaign.
	 *
	 * @param mainScheduledDate the main scheduled date of this s p mail campaign
	 */
	public void setMainScheduledDate(Date mainScheduledDate);

	/**
	 * Returns the rem1 scheduled date of this s p mail campaign.
	 *
	 * @return the rem1 scheduled date of this s p mail campaign
	 */
	public Date getRem1ScheduledDate();

	/**
	 * Sets the rem1 scheduled date of this s p mail campaign.
	 *
	 * @param rem1ScheduledDate the rem1 scheduled date of this s p mail campaign
	 */
	public void setRem1ScheduledDate(Date rem1ScheduledDate);

	/**
	 * Returns the rem2 scheduled date of this s p mail campaign.
	 *
	 * @return the rem2 scheduled date of this s p mail campaign
	 */
	public Date getRem2ScheduledDate();

	/**
	 * Sets the rem2 scheduled date of this s p mail campaign.
	 *
	 * @param rem2ScheduledDate the rem2 scheduled date of this s p mail campaign
	 */
	public void setRem2ScheduledDate(Date rem2ScheduledDate);

	/**
	 * Returns the rem3 scheduled date of this s p mail campaign.
	 *
	 * @return the rem3 scheduled date of this s p mail campaign
	 */
	public Date getRem3ScheduledDate();

	/**
	 * Sets the rem3 scheduled date of this s p mail campaign.
	 *
	 * @param rem3ScheduledDate the rem3 scheduled date of this s p mail campaign
	 */
	public void setRem3ScheduledDate(Date rem3ScheduledDate);

	/**
	 * Returns the thank you scheduled date of this s p mail campaign.
	 *
	 * @return the thank you scheduled date of this s p mail campaign
	 */
	public Date getThankYouScheduledDate();

	/**
	 * Sets the thank you scheduled date of this s p mail campaign.
	 *
	 * @param thankYouScheduledDate the thank you scheduled date of this s p mail campaign
	 */
	public void setThankYouScheduledDate(Date thankYouScheduledDate);

	/**
	 * Returns the missedyou scheduled date of this s p mail campaign.
	 *
	 * @return the missedyou scheduled date of this s p mail campaign
	 */
	public Date getMissedyouScheduledDate();

	/**
	 * Sets the missedyou scheduled date of this s p mail campaign.
	 *
	 * @param missedyouScheduledDate the missedyou scheduled date of this s p mail campaign
	 */
	public void setMissedyouScheduledDate(Date missedyouScheduledDate);

	/**
	 * Returns the rsvp ID of this s p mail campaign.
	 *
	 * @return the rsvp ID of this s p mail campaign
	 */
	public long getRsvpId();

	/**
	 * Sets the rsvp ID of this s p mail campaign.
	 *
	 * @param rsvpId the rsvp ID of this s p mail campaign
	 */
	public void setRsvpId(long rsvpId);

	/**
	 * Returns the dl file entry ID of this s p mail campaign.
	 *
	 * @return the dl file entry ID of this s p mail campaign
	 */
	public long getDlFileEntryId();

	/**
	 * Sets the dl file entry ID of this s p mail campaign.
	 *
	 * @param dlFileEntryId the dl file entry ID of this s p mail campaign
	 */
	public void setDlFileEntryId(long dlFileEntryId);

	/**
	 * Returns the sent by of this s p mail campaign.
	 *
	 * @return the sent by of this s p mail campaign
	 */
	public long getSentBy();

	/**
	 * Sets the sent by of this s p mail campaign.
	 *
	 * @param sentBy the sent by of this s p mail campaign
	 */
	public void setSentBy(long sentBy);

	/**
	 * Returns the sent date of this s p mail campaign.
	 *
	 * @return the sent date of this s p mail campaign
	 */
	public Date getSentDate();

	/**
	 * Sets the sent date of this s p mail campaign.
	 *
	 * @param sentDate the sent date of this s p mail campaign
	 */
	public void setSentDate(Date sentDate);

	/**
	 * Returns the create by of this s p mail campaign.
	 *
	 * @return the create by of this s p mail campaign
	 */
	public long getCreateBy();

	/**
	 * Sets the create by of this s p mail campaign.
	 *
	 * @param createBy the create by of this s p mail campaign
	 */
	public void setCreateBy(long createBy);

	/**
	 * Returns the create date of this s p mail campaign.
	 *
	 * @return the create date of this s p mail campaign
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this s p mail campaign.
	 *
	 * @param createDate the create date of this s p mail campaign
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified by of this s p mail campaign.
	 *
	 * @return the modified by of this s p mail campaign
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this s p mail campaign.
	 *
	 * @param modifiedBy the modified by of this s p mail campaign
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the modified date of this s p mail campaign.
	 *
	 * @return the modified date of this s p mail campaign
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this s p mail campaign.
	 *
	 * @param modifiedDate the modified date of this s p mail campaign
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this s p mail campaign.
	 *
	 * @return the status of this s p mail campaign
	 */
	public int getStatus();

	/**
	 * Sets the status of this s p mail campaign.
	 *
	 * @param status the status of this s p mail campaign
	 */
	public void setStatus(int status);

	/**
	 * Returns the archive of this s p mail campaign.
	 *
	 * @return the archive of this s p mail campaign
	 */
	public boolean getArchive();

	/**
	 * Returns <code>true</code> if this s p mail campaign is archive.
	 *
	 * @return <code>true</code> if this s p mail campaign is archive; <code>false</code> otherwise
	 */
	public boolean isArchive();

	/**
	 * Sets whether this s p mail campaign is archive.
	 *
	 * @param archive the archive of this s p mail campaign
	 */
	public void setArchive(boolean archive);

	/**
	 * Returns the campaign type of this s p mail campaign.
	 *
	 * @return the campaign type of this s p mail campaign
	 */
	@AutoEscape
	public String getCampaignType();

	/**
	 * Sets the campaign type of this s p mail campaign.
	 *
	 * @param campaignType the campaign type of this s p mail campaign
	 */
	public void setCampaignType(String campaignType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.mail.model.SPMailCampaign spMailCampaign);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.mail.model.SPMailCampaign> toCacheModel();

	@Override
	public com.sambaash.platform.srv.mail.model.SPMailCampaign toEscapedModel();

	@Override
	public com.sambaash.platform.srv.mail.model.SPMailCampaign toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}