/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.roles.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SPRoles service. Represents a row in the &quot;SPRoles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.roles.model.impl.SPRolesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.roles.model.impl.SPRolesImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see SPRoles
 * @see com.sambaash.platform.srv.roles.model.impl.SPRolesImpl
 * @see com.sambaash.platform.srv.roles.model.impl.SPRolesModelImpl
 * @generated
 */
public interface SPRolesModel extends BaseModel<SPRoles>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s p roles model instance should use the {@link SPRoles} interface instead.
	 */

	/**
	 * Returns the primary key of this s p roles.
	 *
	 * @return the primary key of this s p roles
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s p roles.
	 *
	 * @param primaryKey the primary key of this s p roles
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this s p roles.
	 *
	 * @return the uuid of this s p roles
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this s p roles.
	 *
	 * @param uuid the uuid of this s p roles
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sp role ID of this s p roles.
	 *
	 * @return the sp role ID of this s p roles
	 */
	public long getSpRoleId();

	/**
	 * Sets the sp role ID of this s p roles.
	 *
	 * @param spRoleId the sp role ID of this s p roles
	 */
	public void setSpRoleId(long spRoleId);

	/**
	 * Returns the group ID of this s p roles.
	 *
	 * @return the group ID of this s p roles
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this s p roles.
	 *
	 * @param groupId the group ID of this s p roles
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this s p roles.
	 *
	 * @return the company ID of this s p roles
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this s p roles.
	 *
	 * @param companyId the company ID of this s p roles
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this s p roles.
	 *
	 * @return the user ID of this s p roles
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this s p roles.
	 *
	 * @param userId the user ID of this s p roles
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s p roles.
	 *
	 * @return the user uuid of this s p roles
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s p roles.
	 *
	 * @param userUuid the user uuid of this s p roles
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this s p roles.
	 *
	 * @return the user name of this s p roles
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this s p roles.
	 *
	 * @param userName the user name of this s p roles
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this s p roles.
	 *
	 * @return the create date of this s p roles
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this s p roles.
	 *
	 * @param createDate the create date of this s p roles
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this s p roles.
	 *
	 * @return the modified date of this s p roles
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this s p roles.
	 *
	 * @param modifiedDate the modified date of this s p roles
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the role ID of this s p roles.
	 *
	 * @return the role ID of this s p roles
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this s p roles.
	 *
	 * @param roleId the role ID of this s p roles
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the category id1 of this s p roles.
	 *
	 * @return the category id1 of this s p roles
	 */
	public long getCategoryId1();

	/**
	 * Sets the category id1 of this s p roles.
	 *
	 * @param categoryId1 the category id1 of this s p roles
	 */
	public void setCategoryId1(long categoryId1);

	/**
	 * Returns the category id2 of this s p roles.
	 *
	 * @return the category id2 of this s p roles
	 */
	public long getCategoryId2();

	/**
	 * Sets the category id2 of this s p roles.
	 *
	 * @param categoryId2 the category id2 of this s p roles
	 */
	public void setCategoryId2(long categoryId2);

	/**
	 * Returns the country category ID of this s p roles.
	 *
	 * @return the country category ID of this s p roles
	 */
	public long getCountryCategoryId();

	/**
	 * Sets the country category ID of this s p roles.
	 *
	 * @param countryCategoryId the country category ID of this s p roles
	 */
	public void setCountryCategoryId(long countryCategoryId);

	/**
	 * Returns the department category ID of this s p roles.
	 *
	 * @return the department category ID of this s p roles
	 */
	public long getDepartmentCategoryId();

	/**
	 * Sets the department category ID of this s p roles.
	 *
	 * @param departmentCategoryId the department category ID of this s p roles
	 */
	public void setDepartmentCategoryId(long departmentCategoryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.sambaash.platform.srv.roles.model.SPRoles spRoles);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.roles.model.SPRoles> toCacheModel();

	@Override
	public com.sambaash.platform.srv.roles.model.SPRoles toEscapedModel();

	@Override
	public com.sambaash.platform.srv.roles.model.SPRoles toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}