create table SPATOContacts (
	spATOContactId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	organizationId BIGINT(20),
	userId BIGINT(20),
	firstName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	primaryPrincipalUserId VARCHAR(75) null,
	secondaryPrincipalUserId VARCHAR(75) null
);

create table SPATODocument (
	uuid_ VARCHAR(75) null,
	atoDocumentId BIGINT(20) not null primary key,
	organizationId BIGINT(20),
	documentType VARCHAR(75) null,
	documentFileId VARCHAR(75) null
);

create table SPAccreditation (
	uuid_ VARCHAR(75) null,
	accreditationId BIGINT(20) not null primary key,
	organizationId BIGINT(20),
	aselected BOOLEAN,
	avalue VARCHAR(75) null,
	bselected BOOLEAN,
	bvalue VARCHAR(75) null,
	cselected BOOLEAN,
	cvalue VARCHAR(75) null,
	cCompanyName VARCHAR(75) null,
	csamepolicy BOOLEAN,
	celaborate VARCHAR(75) null,
	dselected BOOLEAN,
	dvalue VARCHAR(75) null,
	accreditationStatus VARCHAR(75) null,
	dateOfAccreditation DATETIME null,
	dateOfExpiry DATETIME null,
	latestPaymentDate DATETIME null,
	startDateOfReaccreditation DATETIME null,
	dateOfReaccdtReview DATETIME null,
	AccreditationBy VARCHAR(75) null
);

create table SPAddress (
	uuid_ VARCHAR(75) null,
	addressId BIGINT(20) not null primary key,
	organizationId BIGINT(20),
	name VARCHAR(100) null,
	street1 VARCHAR(100) null,
	street2 VARCHAR(100) null,
	street3 VARCHAR(75) null,
	street4 VARCHAR(75) null,
	city VARCHAR(100) null,
	region VARCHAR(100) null,
	country VARCHAR(100) null,
	postalCode VARCHAR(16) null,
	hq BOOLEAN,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	active_ BOOLEAN
);

create table SPEmployeeInfo (
	uuid_ VARCHAR(75) null,
	employeeInfoId BIGINT(20) not null primary key,
	organizationId BIGINT(20),
	employees VARCHAR(75) null,
	directors VARCHAR(75) null,
	financeEmployees VARCHAR(75) null,
	professionalCandidates VARCHAR(75) null,
	foundationCandidates VARCHAR(75) null,
	accountancyCandidates VARCHAR(75) null,
	ISCAAccountants VARCHAR(75) null,
	ICASAccountants VARCHAR(75) null,
	ICAEWAccountants VARCHAR(75) null,
	CAIAccountants VARCHAR(75) null,
	ACCAAccountants VARCHAR(75) null,
	CPAAccountants VARCHAR(75) null,
	CAANZAccountants VARCHAR(75) null,
	CPACanadaAccountants VARCHAR(75) null,
	HKCPAAccountants VARCHAR(75) null,
	SAICAAccountants VARCHAR(75) null,
	JICPAAccountants VARCHAR(75) null,
	AICPAAccountants VARCHAR(75) null,
	CIMAAccountants VARCHAR(75) null,
	othersAccountants VARCHAR(75) null
);

create table SPFundingRounds (
	uuid_ VARCHAR(75) null,
	fundingRoundId BIGINT(20) not null primary key,
	organizationId BIGINT(20),
	name VARCHAR(100) null,
	apiPath VARCHAR(120) null,
	imageUrl VARCHAR(200) null,
	announcedOn VARCHAR(15) null,
	moneyRaisedInUsd VARCHAR(20) null,
	fundingType VARCHAR(50) null,
	description LONGTEXT null,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	active_ BOOLEAN
);

create table SPGuidelines (
	uuid_ VARCHAR(75) null,
	guidelineId BIGINT(20) not null primary key,
	organizationId BIGINT(20),
	principleId BIGINT(20),
	guideline1 BOOLEAN,
	guideline2 BOOLEAN,
	guideline3 BOOLEAN,
	guideline4 BOOLEAN,
	guideline5 BOOLEAN,
	guideline6 BOOLEAN,
	guideline7 BOOLEAN,
	guideline8 BOOLEAN,
	moreInfo VARCHAR(75) null
);

create table SPMentors (
	uuid_ VARCHAR(75) null,
	mentorId BIGINT(20) not null primary key,
	organizationId BIGINT(20),
	userId VARCHAR(75) null,
	createDate DATETIME null,
	approvedDate DATETIME null,
	remarks LONGTEXT null,
	status INTEGER
);

create table SPOrgContactUs (
	spContactUsId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	organizationId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	salutation VARCHAR(75) null,
	person VARCHAR(75) null,
	firstName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	designation VARCHAR(75) null,
	qualification VARCHAR(75) null,
	qualificationDate VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	department VARCHAR(75) null,
	mobileNumber BIGINT(20),
	telephoneNumber BIGINT(20),
	faxNumber BIGINT(20),
	billingContact BOOLEAN,
	operationsContact BOOLEAN,
	active_ BOOLEAN
);

create table SPOrganisationRemarks (
	remarksId BIGINT(20) not null primary key,
	organizationId BIGINT(20),
	remarkType VARCHAR(75) null,
	Remarks LONGTEXT null,
	Notes LONGTEXT null,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null
);

create table SPOrganization (
	uuid_ VARCHAR(75) null,
	organizationId BIGINT(20) not null primary key,
	name VARCHAR(100) null,
	corporateCode VARCHAR(75) null,
	corporateType VARCHAR(75) null,
	corporateCategory VARCHAR(75) null,
	apiPath VARCHAR(120) null,
	categories VARCHAR(200) null,
	foundedOn VARCHAR(15) null,
	noOfEmployees INTEGER,
	emailId VARCHAR(200) null,
	website VARCHAR(450) null,
	facebook VARCHAR(450) null,
	twitter VARCHAR(450) null,
	linkedIn VARCHAR(450) null,
	crunchbase VARCHAR(450) null,
	mobile VARCHAR(25) null,
	totalFunds VARCHAR(100) null,
	uen VARCHAR(75) null,
	description LONGTEXT null,
	shortPitch LONGTEXT null,
	lifecycleStage VARCHAR(20) null,
	capitalRaised VARCHAR(20) null,
	isIncorporated BOOLEAN,
	stockSymbol VARCHAR(20) null,
	imageUrl VARCHAR(200) null,
	videos LONGTEXT null,
	profileOutline LONGTEXT null,
	raisingFunds VARCHAR(20) null,
	extras LONGTEXT null,
	uniqueDesc LONGTEXT null,
	links VARCHAR(1000) null,
	isBaseOrg BOOLEAN,
	completeness BOOLEAN,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	active_ BOOLEAN,
	logoId BIGINT(20),
	methodologyType BIGINT(20),
	methodologySubType BIGINT(20),
	stage INTEGER,
	feedback LONGTEXT null,
	videoLinks LONGTEXT null,
	projectsWorkedOn LONGTEXT null,
	showInBlackbook BOOLEAN,
	faxNumber VARCHAR(75) null,
	contactName VARCHAR(75) null,
	contactDesignation VARCHAR(75) null,
	pipelineStatus INTEGER,
	businessDevManager INTEGER,
	prevBusinessDevManager INTEGER,
	isATO BOOLEAN,
	approvalDate DATETIME null,
	status INTEGER,
	listedCo VARCHAR(75) null,
	noOfPotentialCandidates BIGINT(20)
);

create table SPPerson (
	uuid_ VARCHAR(75) null,
	personId BIGINT(20) not null primary key,
	name VARCHAR(200) null,
	title VARCHAR(100) null,
	apiPath VARCHAR(120) null,
	emailId VARCHAR(100) null,
	description LONGTEXT null,
	imageUrl VARCHAR(200) null,
	mobile VARCHAR(25) null,
	skype VARCHAR(50) null,
	memberUserId BIGINT(20),
	extras LONGTEXT null,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	active_ BOOLEAN
);

create table SPPrinciples (
	uuid_ VARCHAR(75) null,
	siteId BIGINT(20),
	principleId BIGINT(20) not null primary key,
	principleText VARCHAR(75) null,
	guideline1 VARCHAR(375) null,
	guideline2 VARCHAR(375) null,
	guideline3 VARCHAR(375) null,
	guideline4 VARCHAR(375) null,
	guideline5 VARCHAR(375) null,
	guideline6 VARCHAR(375) null,
	guideline7 VARCHAR(375) null,
	guideline8 VARCHAR(375) null
);

create table SPQuestionnaire (
	spQuestionnaireId BIGINT(20) not null primary key,
	entryClassPK BIGINT(20),
	entryClassName VARCHAR(75) null,
	answer1 LONGTEXT null,
	answer2 LONGTEXT null,
	answer3 LONGTEXT null,
	answer4 LONGTEXT null,
	answer5 LONGTEXT null,
	answer6 LONGTEXT null,
	answer7 LONGTEXT null,
	answer8 LONGTEXT null,
	answer9 LONGTEXT null,
	answer10 LONGTEXT null,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null
);

create table SPReAccreditation (
	uuid_ VARCHAR(75) null,
	accreditationId BIGINT(20) not null primary key,
	organizationId BIGINT(20),
	accreditationStatus VARCHAR(75) null,
	dateOfAccreditation DATETIME null,
	dateOfExpiry DATETIME null,
	latestPaymentDate DATETIME null,
	startDateOfReaccreditation DATETIME null,
	dateOfReaccdtReview DATETIME null,
	AccreditationBy VARCHAR(75) null
);

create table SPRelationships (
	relationshipId BIGINT(20) not null primary key,
	organizationId BIGINT(20),
	refId BIGINT(20),
	refTypeId BIGINT(20),
	relation BIGINT(20),
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	active_ BOOLEAN
);