/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.legalandcontract.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.legalandcontract.model.Agency;
import com.sambaash.platform.srv.legalandcontract.model.AgencyModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Agency service. Represents a row in the &quot;SPAgency&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.legalandcontract.model.AgencyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AgencyImpl}.
 * </p>
 *
 * @author nareshchebolu
 * @see AgencyImpl
 * @see com.sambaash.platform.srv.legalandcontract.model.Agency
 * @see com.sambaash.platform.srv.legalandcontract.model.AgencyModel
 * @generated
 */
public class AgencyModelImpl extends BaseModelImpl<Agency>
	implements AgencyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a agency model instance should use the {@link com.sambaash.platform.srv.legalandcontract.model.Agency} interface instead.
	 */
	public static final String TABLE_NAME = "SPAgency";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "spAgencyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "number_", Types.VARCHAR },
			{ "country", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "reference", Types.VARCHAR },
			{ "startDate", Types.VARCHAR },
			{ "endDate", Types.VARCHAR },
			{ "address", Types.CLOB },
			{ "remarks", Types.CLOB },
			{ "status", Types.VARCHAR },
			{ "customField1", Types.VARCHAR },
			{ "customField2", Types.VARCHAR },
			{ "customField3", Types.VARCHAR },
			{ "customDate1", Types.TIMESTAMP },
			{ "customDate2", Types.TIMESTAMP },
			{ "customDate3", Types.TIMESTAMP },
			{ "version", Types.VARCHAR },
			{ "rootSpAgencyId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table SPAgency (uuid_ VARCHAR(75) null,spAgencyId BIGINT(20) not null primary key,groupId BIGINT(20),companyId BIGINT(20),userId BIGINT(20),userName VARCHAR(75) null,createDate DATETIME null,modifiedDate DATETIME null,number_ VARCHAR(200) null,country VARCHAR(200) null,name VARCHAR(200) null,reference VARCHAR(200) null,startDate VARCHAR(200) null,endDate VARCHAR(200) null,address LONGTEXT null,remarks LONGTEXT null,status VARCHAR(200) null,customField1 VARCHAR(200) null,customField2 VARCHAR(200) null,customField3 VARCHAR(200) null,customDate1 DATETIME null,customDate2 DATETIME null,customDate3 DATETIME null,version VARCHAR(75) null,rootSpAgencyId BIGINT(20))";
	public static final String TABLE_SQL_DROP = "drop table SPAgency";
	public static final String ORDER_BY_JPQL = " ORDER BY agency.spAgencyId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPAgency.spAgencyId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.legalandcontract.model.Agency"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.legalandcontract.model.Agency"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.legalandcontract.model.Agency"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long COUNTRY_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static long NUMBER_COLUMN_BITMASK = 8L;
	public static long UUID_COLUMN_BITMASK = 16L;
	public static long VERSION_COLUMN_BITMASK = 32L;
	public static long SPAGENCYID_COLUMN_BITMASK = 64L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.legalandcontract.model.Agency"));

	public AgencyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _spAgencyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSpAgencyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _spAgencyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Agency.class;
	}

	@Override
	public String getModelClassName() {
		return Agency.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("spAgencyId", getSpAgencyId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("number", getNumber());
		attributes.put("country", getCountry());
		attributes.put("name", getName());
		attributes.put("reference", getReference());
		attributes.put("startDate", getStartDate());
		attributes.put("endDate", getEndDate());
		attributes.put("address", getAddress());
		attributes.put("remarks", getRemarks());
		attributes.put("status", getStatus());
		attributes.put("customField1", getCustomField1());
		attributes.put("customField2", getCustomField2());
		attributes.put("customField3", getCustomField3());
		attributes.put("customDate1", getCustomDate1());
		attributes.put("customDate2", getCustomDate2());
		attributes.put("customDate3", getCustomDate3());
		attributes.put("version", getVersion());
		attributes.put("rootSpAgencyId", getRootSpAgencyId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long spAgencyId = (Long)attributes.get("spAgencyId");

		if (spAgencyId != null) {
			setSpAgencyId(spAgencyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String number = (String)attributes.get("number");

		if (number != null) {
			setNumber(number);
		}

		String country = (String)attributes.get("country");

		if (country != null) {
			setCountry(country);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String reference = (String)attributes.get("reference");

		if (reference != null) {
			setReference(reference);
		}

		String startDate = (String)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		String endDate = (String)attributes.get("endDate");

		if (endDate != null) {
			setEndDate(endDate);
		}

		String address = (String)attributes.get("address");

		if (address != null) {
			setAddress(address);
		}

		String remarks = (String)attributes.get("remarks");

		if (remarks != null) {
			setRemarks(remarks);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String customField1 = (String)attributes.get("customField1");

		if (customField1 != null) {
			setCustomField1(customField1);
		}

		String customField2 = (String)attributes.get("customField2");

		if (customField2 != null) {
			setCustomField2(customField2);
		}

		String customField3 = (String)attributes.get("customField3");

		if (customField3 != null) {
			setCustomField3(customField3);
		}

		Date customDate1 = (Date)attributes.get("customDate1");

		if (customDate1 != null) {
			setCustomDate1(customDate1);
		}

		Date customDate2 = (Date)attributes.get("customDate2");

		if (customDate2 != null) {
			setCustomDate2(customDate2);
		}

		Date customDate3 = (Date)attributes.get("customDate3");

		if (customDate3 != null) {
			setCustomDate3(customDate3);
		}

		String version = (String)attributes.get("version");

		if (version != null) {
			setVersion(version);
		}

		Long rootSpAgencyId = (Long)attributes.get("rootSpAgencyId");

		if (rootSpAgencyId != null) {
			setRootSpAgencyId(rootSpAgencyId);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getSpAgencyId() {
		return _spAgencyId;
	}

	@Override
	public void setSpAgencyId(long spAgencyId) {
		_spAgencyId = spAgencyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getNumber() {
		if (_number == null) {
			return StringPool.BLANK;
		}
		else {
			return _number;
		}
	}

	@Override
	public void setNumber(String number) {
		_columnBitmask |= NUMBER_COLUMN_BITMASK;

		if (_originalNumber == null) {
			_originalNumber = _number;
		}

		_number = number;
	}

	public String getOriginalNumber() {
		return GetterUtil.getString(_originalNumber);
	}

	@Override
	public String getCountry() {
		if (_country == null) {
			return StringPool.BLANK;
		}
		else {
			return _country;
		}
	}

	@Override
	public void setCountry(String country) {
		_columnBitmask |= COUNTRY_COLUMN_BITMASK;

		if (_originalCountry == null) {
			_originalCountry = _country;
		}

		_country = country;
	}

	public String getOriginalCountry() {
		return GetterUtil.getString(_originalCountry);
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getReference() {
		if (_reference == null) {
			return StringPool.BLANK;
		}
		else {
			return _reference;
		}
	}

	@Override
	public void setReference(String reference) {
		_reference = reference;
	}

	@Override
	public String getStartDate() {
		if (_startDate == null) {
			return StringPool.BLANK;
		}
		else {
			return _startDate;
		}
	}

	@Override
	public void setStartDate(String startDate) {
		_startDate = startDate;
	}

	@Override
	public String getEndDate() {
		if (_endDate == null) {
			return StringPool.BLANK;
		}
		else {
			return _endDate;
		}
	}

	@Override
	public void setEndDate(String endDate) {
		_endDate = endDate;
	}

	@Override
	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		_address = address;
	}

	@Override
	public String getRemarks() {
		if (_remarks == null) {
			return StringPool.BLANK;
		}
		else {
			return _remarks;
		}
	}

	@Override
	public void setRemarks(String remarks) {
		_remarks = remarks;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@Override
	public String getCustomField1() {
		if (_customField1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _customField1;
		}
	}

	@Override
	public void setCustomField1(String customField1) {
		_customField1 = customField1;
	}

	@Override
	public String getCustomField2() {
		if (_customField2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _customField2;
		}
	}

	@Override
	public void setCustomField2(String customField2) {
		_customField2 = customField2;
	}

	@Override
	public String getCustomField3() {
		if (_customField3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _customField3;
		}
	}

	@Override
	public void setCustomField3(String customField3) {
		_customField3 = customField3;
	}

	@Override
	public Date getCustomDate1() {
		return _customDate1;
	}

	@Override
	public void setCustomDate1(Date customDate1) {
		_customDate1 = customDate1;
	}

	@Override
	public Date getCustomDate2() {
		return _customDate2;
	}

	@Override
	public void setCustomDate2(Date customDate2) {
		_customDate2 = customDate2;
	}

	@Override
	public Date getCustomDate3() {
		return _customDate3;
	}

	@Override
	public void setCustomDate3(Date customDate3) {
		_customDate3 = customDate3;
	}

	@Override
	public String getVersion() {
		if (_version == null) {
			return StringPool.BLANK;
		}
		else {
			return _version;
		}
	}

	@Override
	public void setVersion(String version) {
		_columnBitmask |= VERSION_COLUMN_BITMASK;

		if (_originalVersion == null) {
			_originalVersion = _version;
		}

		_version = version;
	}

	public String getOriginalVersion() {
		return GetterUtil.getString(_originalVersion);
	}

	@Override
	public long getRootSpAgencyId() {
		return _rootSpAgencyId;
	}

	@Override
	public void setRootSpAgencyId(long rootSpAgencyId) {
		_rootSpAgencyId = rootSpAgencyId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Agency.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Agency.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Agency toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Agency)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AgencyImpl agencyImpl = new AgencyImpl();

		agencyImpl.setUuid(getUuid());
		agencyImpl.setSpAgencyId(getSpAgencyId());
		agencyImpl.setGroupId(getGroupId());
		agencyImpl.setCompanyId(getCompanyId());
		agencyImpl.setUserId(getUserId());
		agencyImpl.setUserName(getUserName());
		agencyImpl.setCreateDate(getCreateDate());
		agencyImpl.setModifiedDate(getModifiedDate());
		agencyImpl.setNumber(getNumber());
		agencyImpl.setCountry(getCountry());
		agencyImpl.setName(getName());
		agencyImpl.setReference(getReference());
		agencyImpl.setStartDate(getStartDate());
		agencyImpl.setEndDate(getEndDate());
		agencyImpl.setAddress(getAddress());
		agencyImpl.setRemarks(getRemarks());
		agencyImpl.setStatus(getStatus());
		agencyImpl.setCustomField1(getCustomField1());
		agencyImpl.setCustomField2(getCustomField2());
		agencyImpl.setCustomField3(getCustomField3());
		agencyImpl.setCustomDate1(getCustomDate1());
		agencyImpl.setCustomDate2(getCustomDate2());
		agencyImpl.setCustomDate3(getCustomDate3());
		agencyImpl.setVersion(getVersion());
		agencyImpl.setRootSpAgencyId(getRootSpAgencyId());

		agencyImpl.resetOriginalValues();

		return agencyImpl;
	}

	@Override
	public int compareTo(Agency agency) {
		long primaryKey = agency.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Agency)) {
			return false;
		}

		Agency agency = (Agency)obj;

		long primaryKey = agency.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		AgencyModelImpl agencyModelImpl = this;

		agencyModelImpl._originalUuid = agencyModelImpl._uuid;

		agencyModelImpl._originalGroupId = agencyModelImpl._groupId;

		agencyModelImpl._setOriginalGroupId = false;

		agencyModelImpl._originalCompanyId = agencyModelImpl._companyId;

		agencyModelImpl._setOriginalCompanyId = false;

		agencyModelImpl._originalNumber = agencyModelImpl._number;

		agencyModelImpl._originalCountry = agencyModelImpl._country;

		agencyModelImpl._originalVersion = agencyModelImpl._version;

		agencyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Agency> toCacheModel() {
		AgencyCacheModel agencyCacheModel = new AgencyCacheModel();

		agencyCacheModel.uuid = getUuid();

		String uuid = agencyCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			agencyCacheModel.uuid = null;
		}

		agencyCacheModel.spAgencyId = getSpAgencyId();

		agencyCacheModel.groupId = getGroupId();

		agencyCacheModel.companyId = getCompanyId();

		agencyCacheModel.userId = getUserId();

		agencyCacheModel.userName = getUserName();

		String userName = agencyCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			agencyCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			agencyCacheModel.createDate = createDate.getTime();
		}
		else {
			agencyCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			agencyCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			agencyCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		agencyCacheModel.number = getNumber();

		String number = agencyCacheModel.number;

		if ((number != null) && (number.length() == 0)) {
			agencyCacheModel.number = null;
		}

		agencyCacheModel.country = getCountry();

		String country = agencyCacheModel.country;

		if ((country != null) && (country.length() == 0)) {
			agencyCacheModel.country = null;
		}

		agencyCacheModel.name = getName();

		String name = agencyCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			agencyCacheModel.name = null;
		}

		agencyCacheModel.reference = getReference();

		String reference = agencyCacheModel.reference;

		if ((reference != null) && (reference.length() == 0)) {
			agencyCacheModel.reference = null;
		}

		agencyCacheModel.startDate = getStartDate();

		String startDate = agencyCacheModel.startDate;

		if ((startDate != null) && (startDate.length() == 0)) {
			agencyCacheModel.startDate = null;
		}

		agencyCacheModel.endDate = getEndDate();

		String endDate = agencyCacheModel.endDate;

		if ((endDate != null) && (endDate.length() == 0)) {
			agencyCacheModel.endDate = null;
		}

		agencyCacheModel.address = getAddress();

		String address = agencyCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			agencyCacheModel.address = null;
		}

		agencyCacheModel.remarks = getRemarks();

		String remarks = agencyCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			agencyCacheModel.remarks = null;
		}

		agencyCacheModel.status = getStatus();

		String status = agencyCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			agencyCacheModel.status = null;
		}

		agencyCacheModel.customField1 = getCustomField1();

		String customField1 = agencyCacheModel.customField1;

		if ((customField1 != null) && (customField1.length() == 0)) {
			agencyCacheModel.customField1 = null;
		}

		agencyCacheModel.customField2 = getCustomField2();

		String customField2 = agencyCacheModel.customField2;

		if ((customField2 != null) && (customField2.length() == 0)) {
			agencyCacheModel.customField2 = null;
		}

		agencyCacheModel.customField3 = getCustomField3();

		String customField3 = agencyCacheModel.customField3;

		if ((customField3 != null) && (customField3.length() == 0)) {
			agencyCacheModel.customField3 = null;
		}

		Date customDate1 = getCustomDate1();

		if (customDate1 != null) {
			agencyCacheModel.customDate1 = customDate1.getTime();
		}
		else {
			agencyCacheModel.customDate1 = Long.MIN_VALUE;
		}

		Date customDate2 = getCustomDate2();

		if (customDate2 != null) {
			agencyCacheModel.customDate2 = customDate2.getTime();
		}
		else {
			agencyCacheModel.customDate2 = Long.MIN_VALUE;
		}

		Date customDate3 = getCustomDate3();

		if (customDate3 != null) {
			agencyCacheModel.customDate3 = customDate3.getTime();
		}
		else {
			agencyCacheModel.customDate3 = Long.MIN_VALUE;
		}

		agencyCacheModel.version = getVersion();

		String version = agencyCacheModel.version;

		if ((version != null) && (version.length() == 0)) {
			agencyCacheModel.version = null;
		}

		agencyCacheModel.rootSpAgencyId = getRootSpAgencyId();

		return agencyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(51);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", spAgencyId=");
		sb.append(getSpAgencyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", number=");
		sb.append(getNumber());
		sb.append(", country=");
		sb.append(getCountry());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", reference=");
		sb.append(getReference());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", remarks=");
		sb.append(getRemarks());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", customField1=");
		sb.append(getCustomField1());
		sb.append(", customField2=");
		sb.append(getCustomField2());
		sb.append(", customField3=");
		sb.append(getCustomField3());
		sb.append(", customDate1=");
		sb.append(getCustomDate1());
		sb.append(", customDate2=");
		sb.append(getCustomDate2());
		sb.append(", customDate3=");
		sb.append(getCustomDate3());
		sb.append(", version=");
		sb.append(getVersion());
		sb.append(", rootSpAgencyId=");
		sb.append(getRootSpAgencyId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(79);

		sb.append("<model><model-name>");
		sb.append("com.sambaash.platform.srv.legalandcontract.model.Agency");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>spAgencyId</column-name><column-value><![CDATA[");
		sb.append(getSpAgencyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>number</column-name><column-value><![CDATA[");
		sb.append(getNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>country</column-name><column-value><![CDATA[");
		sb.append(getCountry());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>reference</column-name><column-value><![CDATA[");
		sb.append(getReference());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remarks</column-name><column-value><![CDATA[");
		sb.append(getRemarks());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customField1</column-name><column-value><![CDATA[");
		sb.append(getCustomField1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customField2</column-name><column-value><![CDATA[");
		sb.append(getCustomField2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customField3</column-name><column-value><![CDATA[");
		sb.append(getCustomField3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customDate1</column-name><column-value><![CDATA[");
		sb.append(getCustomDate1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customDate2</column-name><column-value><![CDATA[");
		sb.append(getCustomDate2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customDate3</column-name><column-value><![CDATA[");
		sb.append(getCustomDate3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>version</column-name><column-value><![CDATA[");
		sb.append(getVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rootSpAgencyId</column-name><column-value><![CDATA[");
		sb.append(getRootSpAgencyId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Agency.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Agency.class };
	private String _uuid;
	private String _originalUuid;
	private long _spAgencyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _number;
	private String _originalNumber;
	private String _country;
	private String _originalCountry;
	private String _name;
	private String _reference;
	private String _startDate;
	private String _endDate;
	private String _address;
	private String _remarks;
	private String _status;
	private String _customField1;
	private String _customField2;
	private String _customField3;
	private Date _customDate1;
	private Date _customDate2;
	private Date _customDate3;
	private String _version;
	private String _originalVersion;
	private long _rootSpAgencyId;
	private long _columnBitmask;
	private Agency _escapedModel;
}