/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.rsvp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.rsvp.model.RsvpDiscount;
import com.sambaash.platform.srv.rsvp.model.RsvpDiscountModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the RsvpDiscount service. Represents a row in the &quot;SPRsvpDiscount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.rsvp.model.RsvpDiscountModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RsvpDiscountImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see RsvpDiscountImpl
 * @see com.sambaash.platform.srv.rsvp.model.RsvpDiscount
 * @see com.sambaash.platform.srv.rsvp.model.RsvpDiscountModel
 * @generated
 */
public class RsvpDiscountModelImpl extends BaseModelImpl<RsvpDiscount>
	implements RsvpDiscountModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rsvp discount model instance should use the {@link com.sambaash.platform.srv.rsvp.model.RsvpDiscount} interface instead.
	 */
	public static final String TABLE_NAME = "SPRsvpDiscount";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "spRsvpDiscountId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "spRsvpId", Types.BIGINT },
			{ "spRsvpTicketId", Types.BIGINT },
			{ "fromDate", Types.TIMESTAMP },
			{ "toDate", Types.TIMESTAMP },
			{ "noOfTickets", Types.INTEGER },
			{ "discount", Types.DOUBLE },
			{ "modifiedBy", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table SPRsvpDiscount (uuid_ VARCHAR(75) null,spRsvpDiscountId BIGINT(20) not null primary key,groupId BIGINT(20),companyId BIGINT(20),userId BIGINT(20),userName VARCHAR(75) null,createDate DATETIME null,modifiedDate DATETIME null,spRsvpId BIGINT(20),spRsvpTicketId BIGINT(20),fromDate DATETIME null,toDate DATETIME null,noOfTickets INTEGER,discount DOUBLE,modifiedBy BIGINT(20))";
	public static final String TABLE_SQL_DROP = "drop table SPRsvpDiscount";
	public static final String ORDER_BY_JPQL = " ORDER BY rsvpDiscount.rsvpDiscountId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPRsvpDiscount.spRsvpDiscountId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.rsvp.model.RsvpDiscount"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.rsvp.model.RsvpDiscount"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.rsvp.model.RsvpDiscount"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long RSVPID_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;
	public static long RSVPDISCOUNTID_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.rsvp.model.RsvpDiscount"));

	public RsvpDiscountModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _rsvpDiscountId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRsvpDiscountId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _rsvpDiscountId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RsvpDiscount.class;
	}

	@Override
	public String getModelClassName() {
		return RsvpDiscount.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("rsvpDiscountId", getRsvpDiscountId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("rsvpId", getRsvpId());
		attributes.put("rsvpTicketId", getRsvpTicketId());
		attributes.put("fromDate", getFromDate());
		attributes.put("toDate", getToDate());
		attributes.put("noOfTickets", getNoOfTickets());
		attributes.put("discount", getDiscount());
		attributes.put("modifiedBy", getModifiedBy());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long rsvpDiscountId = (Long)attributes.get("rsvpDiscountId");

		if (rsvpDiscountId != null) {
			setRsvpDiscountId(rsvpDiscountId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long rsvpId = (Long)attributes.get("rsvpId");

		if (rsvpId != null) {
			setRsvpId(rsvpId);
		}

		Long rsvpTicketId = (Long)attributes.get("rsvpTicketId");

		if (rsvpTicketId != null) {
			setRsvpTicketId(rsvpTicketId);
		}

		Date fromDate = (Date)attributes.get("fromDate");

		if (fromDate != null) {
			setFromDate(fromDate);
		}

		Date toDate = (Date)attributes.get("toDate");

		if (toDate != null) {
			setToDate(toDate);
		}

		Integer noOfTickets = (Integer)attributes.get("noOfTickets");

		if (noOfTickets != null) {
			setNoOfTickets(noOfTickets);
		}

		Double discount = (Double)attributes.get("discount");

		if (discount != null) {
			setDiscount(discount);
		}

		Long modifiedBy = (Long)attributes.get("modifiedBy");

		if (modifiedBy != null) {
			setModifiedBy(modifiedBy);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getRsvpDiscountId() {
		return _rsvpDiscountId;
	}

	@Override
	public void setRsvpDiscountId(long rsvpDiscountId) {
		_rsvpDiscountId = rsvpDiscountId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getRsvpId() {
		return _rsvpId;
	}

	@Override
	public void setRsvpId(long rsvpId) {
		_columnBitmask |= RSVPID_COLUMN_BITMASK;

		if (!_setOriginalRsvpId) {
			_setOriginalRsvpId = true;

			_originalRsvpId = _rsvpId;
		}

		_rsvpId = rsvpId;
	}

	public long getOriginalRsvpId() {
		return _originalRsvpId;
	}

	@Override
	public long getRsvpTicketId() {
		return _rsvpTicketId;
	}

	@Override
	public void setRsvpTicketId(long rsvpTicketId) {
		_rsvpTicketId = rsvpTicketId;
	}

	@Override
	public Date getFromDate() {
		return _fromDate;
	}

	@Override
	public void setFromDate(Date fromDate) {
		_fromDate = fromDate;
	}

	@Override
	public Date getToDate() {
		return _toDate;
	}

	@Override
	public void setToDate(Date toDate) {
		_toDate = toDate;
	}

	@Override
	public int getNoOfTickets() {
		return _noOfTickets;
	}

	@Override
	public void setNoOfTickets(int noOfTickets) {
		_noOfTickets = noOfTickets;
	}

	@Override
	public double getDiscount() {
		return _discount;
	}

	@Override
	public void setDiscount(double discount) {
		_discount = discount;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				RsvpDiscount.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			RsvpDiscount.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RsvpDiscount toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RsvpDiscount)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RsvpDiscountImpl rsvpDiscountImpl = new RsvpDiscountImpl();

		rsvpDiscountImpl.setUuid(getUuid());
		rsvpDiscountImpl.setRsvpDiscountId(getRsvpDiscountId());
		rsvpDiscountImpl.setGroupId(getGroupId());
		rsvpDiscountImpl.setCompanyId(getCompanyId());
		rsvpDiscountImpl.setUserId(getUserId());
		rsvpDiscountImpl.setUserName(getUserName());
		rsvpDiscountImpl.setCreateDate(getCreateDate());
		rsvpDiscountImpl.setModifiedDate(getModifiedDate());
		rsvpDiscountImpl.setRsvpId(getRsvpId());
		rsvpDiscountImpl.setRsvpTicketId(getRsvpTicketId());
		rsvpDiscountImpl.setFromDate(getFromDate());
		rsvpDiscountImpl.setToDate(getToDate());
		rsvpDiscountImpl.setNoOfTickets(getNoOfTickets());
		rsvpDiscountImpl.setDiscount(getDiscount());
		rsvpDiscountImpl.setModifiedBy(getModifiedBy());

		rsvpDiscountImpl.resetOriginalValues();

		return rsvpDiscountImpl;
	}

	@Override
	public int compareTo(RsvpDiscount rsvpDiscount) {
		long primaryKey = rsvpDiscount.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RsvpDiscount)) {
			return false;
		}

		RsvpDiscount rsvpDiscount = (RsvpDiscount)obj;

		long primaryKey = rsvpDiscount.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		RsvpDiscountModelImpl rsvpDiscountModelImpl = this;

		rsvpDiscountModelImpl._originalUuid = rsvpDiscountModelImpl._uuid;

		rsvpDiscountModelImpl._originalGroupId = rsvpDiscountModelImpl._groupId;

		rsvpDiscountModelImpl._setOriginalGroupId = false;

		rsvpDiscountModelImpl._originalCompanyId = rsvpDiscountModelImpl._companyId;

		rsvpDiscountModelImpl._setOriginalCompanyId = false;

		rsvpDiscountModelImpl._originalRsvpId = rsvpDiscountModelImpl._rsvpId;

		rsvpDiscountModelImpl._setOriginalRsvpId = false;

		rsvpDiscountModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<RsvpDiscount> toCacheModel() {
		RsvpDiscountCacheModel rsvpDiscountCacheModel = new RsvpDiscountCacheModel();

		rsvpDiscountCacheModel.uuid = getUuid();

		String uuid = rsvpDiscountCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			rsvpDiscountCacheModel.uuid = null;
		}

		rsvpDiscountCacheModel.rsvpDiscountId = getRsvpDiscountId();

		rsvpDiscountCacheModel.groupId = getGroupId();

		rsvpDiscountCacheModel.companyId = getCompanyId();

		rsvpDiscountCacheModel.userId = getUserId();

		rsvpDiscountCacheModel.userName = getUserName();

		String userName = rsvpDiscountCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			rsvpDiscountCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			rsvpDiscountCacheModel.createDate = createDate.getTime();
		}
		else {
			rsvpDiscountCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			rsvpDiscountCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			rsvpDiscountCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		rsvpDiscountCacheModel.rsvpId = getRsvpId();

		rsvpDiscountCacheModel.rsvpTicketId = getRsvpTicketId();

		Date fromDate = getFromDate();

		if (fromDate != null) {
			rsvpDiscountCacheModel.fromDate = fromDate.getTime();
		}
		else {
			rsvpDiscountCacheModel.fromDate = Long.MIN_VALUE;
		}

		Date toDate = getToDate();

		if (toDate != null) {
			rsvpDiscountCacheModel.toDate = toDate.getTime();
		}
		else {
			rsvpDiscountCacheModel.toDate = Long.MIN_VALUE;
		}

		rsvpDiscountCacheModel.noOfTickets = getNoOfTickets();

		rsvpDiscountCacheModel.discount = getDiscount();

		rsvpDiscountCacheModel.modifiedBy = getModifiedBy();

		return rsvpDiscountCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", rsvpDiscountId=");
		sb.append(getRsvpDiscountId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", rsvpId=");
		sb.append(getRsvpId());
		sb.append(", rsvpTicketId=");
		sb.append(getRsvpTicketId());
		sb.append(", fromDate=");
		sb.append(getFromDate());
		sb.append(", toDate=");
		sb.append(getToDate());
		sb.append(", noOfTickets=");
		sb.append(getNoOfTickets());
		sb.append(", discount=");
		sb.append(getDiscount());
		sb.append(", modifiedBy=");
		sb.append(getModifiedBy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.sambaash.platform.srv.rsvp.model.RsvpDiscount");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rsvpDiscountId</column-name><column-value><![CDATA[");
		sb.append(getRsvpDiscountId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rsvpId</column-name><column-value><![CDATA[");
		sb.append(getRsvpId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rsvpTicketId</column-name><column-value><![CDATA[");
		sb.append(getRsvpTicketId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fromDate</column-name><column-value><![CDATA[");
		sb.append(getFromDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>toDate</column-name><column-value><![CDATA[");
		sb.append(getToDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noOfTickets</column-name><column-value><![CDATA[");
		sb.append(getNoOfTickets());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>discount</column-name><column-value><![CDATA[");
		sb.append(getDiscount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = RsvpDiscount.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			RsvpDiscount.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _rsvpDiscountId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _rsvpId;
	private long _originalRsvpId;
	private boolean _setOriginalRsvpId;
	private long _rsvpTicketId;
	private Date _fromDate;
	private Date _toDate;
	private int _noOfTickets;
	private double _discount;
	private long _modifiedBy;
	private long _columnBitmask;
	private RsvpDiscount _escapedModel;
}