package com.sambaash.platform.activityhub.constants;


public interface SPActivityHubConstants {

	String PORTLET_ID = "SPActivityHub_WAR_SPActivityHubportlet";
	String ENTITY_ID = "entityId";
	String CLASS_NAME = "className";
	String ENTITY_CLASS_ID = "entityClassId";
	String ENTITY_CLASS_NAME = "entityClassName";
	String CREATE_DATE = "createDate";
	String MODIFIED_DATE = "modifiedDate";
	String SP_CONVERSATION_ID = "spConverationId";
	String SP_NOTE_ID = "spNoteId";
	String SENT_BY_USER_ID = "sentByUserId";
	String SAVED_BY_USER_ID = "savedByUserId";
	String MESSAGE = "message";
	String FILE_ENTRY_ID = "fileEntryId";
	String ASSOCIATED_WITH = "associatedWith";
	String RESTRICTED = "restricted";
	String STATUS = "status";
	String PARENT_CONVERSATION_ID = "parentConverstationId";
	String CONV_UUID = "convUuid";
	String PARENT_NOTE_ID = "parentNoteId";
	String SENT_BY_USER_SCREEN_NAME = "sentByUserScreenName";
	String SENT_BY_USER_EMAIL = "sentByUserEmail";
	String SENT_BY_USER_EMAIL_SEARCHABLE = "sentByUserEmailSearchable";
	String SENT_BY_USER_FULL_NAME_SEARCHABLE = "sentByUserFullNameSearchable";
	String SENT_BY_USER_FULL_NAME ="sentByUserFullName";
	String SAVED_BY_USER_SCREEN_NAME = "savedByUserScreenName";
	String SAVED_BY_USER_EMAIL = "savedByUserEmail";
	String SAVED_BY_USER_EMAIL_SEARCHABLE = "savedByUserEmailSearchable";
	String SAVED_BY_USER_FULL_NAME_SEARCHABLE = "savedByUserFullNameSearchable";
	String SAVED_BY_USER_FULL_NAME ="savedyUserFullName";
	String ASSOCIATED_WITH_USER_SCREEN_NAME = "associatedWithUserScreenName";
	String ASSOCIATED_WITH_USER_EMAIL = "associatedWithUserEmail";
	String ASSOCIATED_WITH_USER_EMAIL_SEARCHABLE = "associatedWithUserEmailSearchable";
	String ASSOCIATED_WITH_USER_FULL_NAME_SEARCHABLE = "associatedWithUserFullNameSearchable";
	String ASSOCIATED_WITH_USER_FULL_NAME ="associatedWithUserFullName";
	String SENT_TO_USER_SCREEN_NAME = "sentToUserScreenName";
	String SENT_TO_USER_EMAIL = "sentToUserEmail";
	String SENT_TO_USER_EMAIL_SEARCHABLE = "sentToUserEmailSearchable";
	String SENT_TO_USER_FULL_NAME_SEARCHABLE = "sentToUserFullNameSearchable";
	String SENT_TO_USER_FULL_NAME ="sentToUserFullName";
	String SENT_TO_USER_ID = "sentToUserId";
	String UPLOADS_FILE_ENTRY_ID = "uploadsFileEntryId";
	String CLASS_NAME_TO_UPDATE = "classNameToUpdate";
	String PREF_INTERNAL_ROLE_IDS = "internalRoleIds";
	String PREF_EXTERNAL_ROLE_IDS = "externalRoleIds";
	String CONV_ID = "convId";
	String NOTE_ID = "noteId";
	String NOTE_TITLE = "noteTitle";
	String NOTE_CONTENT = "noteContent";
	String LOG_ACTIVITY_ID = "logActivityId";
	String LOG_ACTIVITY_TITLE = "logActivityTitle";
	String LOG_ACTIVITY_CONTENT = "logActivityContent";
	String LOG_ACTIVITY_TYPE = "logActivityType";
	String LOG_ACTIVITY_OUTCOME = "logActivityOutcome";
	String LOG_ACTIVITY_DATE = "logActivityDate";
	String LOG_ACTIVITY_TIME = "logActivityTime";
	String SP_LOG_ACTIVITY_ID = "spLogActivityId";
	String PARENT_LOG_ACTIVITY_ID = "parentLogActivityId";
	String SP_PARAM_ACTIVITYHUB_ROOT_FOLDR = "activityhub.root.folder.name";
	String TITLE = "title";
	String USER_NAME = "userName";
	String ACTIVITYHUB_LINK = "startupFriendlyUrl";
	String SP_PARAM_ACTIVITY_HUB_DISPLAY = "activity.hub.display";
}