create table SPPECustomActionInfo (
	uuid_ VARCHAR(75) null,
	spPEActionId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	actionClassName VARCHAR(75) null,
	title VARCHAR(75) null,
	defaultConfiguration LONGTEXT null
);

create table SPPEDummyEntity (
	uuid_ VARCHAR(75) null,
	spPEDummyEntityId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	name VARCHAR(75) null
);

create table SPPEProcess (
	uuid_ VARCHAR(75) null,
	spPEProcessId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	name VARCHAR(75) null,
	definiton LONGTEXT null,
	entityClassId BIGINT(20),
	agentEnabled BOOLEAN,
	agentRoleIds VARCHAR(75) null,
	approveRoleIds VARCHAR(75) null,
	miscData LONGTEXT null,
	diagramData LONGTEXT null,
	entityTitle VARCHAR(75) null,
	approverPageName VARCHAR(75) null,
	userPageName VARCHAR(75) null,
	agentPageName VARCHAR(75) null,
	status INTEGER,
	applicantRoleId BIGINT(20),
	supervisorRoleIds VARCHAR(75) null,
	supervisorPageName VARCHAR(75) null,
	closedReasonVocId BIGINT(20),
	accountCreationEmailEnabled BOOLEAN,
	enableAssignment BOOLEAN,
	editFeeDetails BOOLEAN,
	scheduleModelId BIGINT(20),
	enableSingleSubmission BOOLEAN,
	orientation VARCHAR(75) null,
	showHeader BOOLEAN,
	enableFirstStepProgress BOOLEAN,
	subProductTypeId BIGINT(20),
	productTypeId BIGINT(20),
	singleSubmissionErrorMsg VARCHAR(75) null
);

create table SPPEProcessAudit (
	uuid_ VARCHAR(75) null,
	spPEProcessAuditId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	userId BIGINT(20),
	companyId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	spPEProcessStateId BIGINT(20),
	spPEProcessId BIGINT(20),
	entityClassId BIGINT(20),
	entityId BIGINT(20),
	userIdProcess BIGINT(20),
	statusTypeId BIGINT(20),
	spPEProcessStageId BIGINT(20),
	nodeId BIGINT(20),
	status VARCHAR(75) null,
	userIdSupervisor BIGINT(20),
	userIdAgent BIGINT(20),
	spPEClosedStageId BIGINT(20),
	type_ VARCHAR(75) null,
	doneBy VARCHAR(75) null,
	action VARCHAR(75) null,
	field1 VARCHAR(75) null,
	field2 VARCHAR(75) null,
	field3 VARCHAR(75) null,
	field4 VARCHAR(75) null,
	field5 BIGINT(20),
	storageId BIGINT(20),
	data1 LONGTEXT null,
	data2 LONGTEXT null,
	sourceClassId BIGINT(20),
	sourceEntityID BIGINT(20)
);

create table SPPEProcessStage (
	uuid_ VARCHAR(75) null,
	spPEProcessStageId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	userId BIGINT(20),
	companyId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	name VARCHAR(75) null,
	style LONGTEXT null,
	seqNo BIGINT(20)
);

create table SPPEProcessState (
	uuid_ VARCHAR(75) null,
	spPEProcessStateId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	spPEProcessId BIGINT(20),
	entityClassId BIGINT(20),
	entityId BIGINT(20),
	userIdProcess BIGINT(20),
	userIdCreator BIGINT(20),
	statusTypeId BIGINT(20),
	spPEProcessStageId BIGINT(20),
	status VARCHAR(75) null,
	nodeId BIGINT(20),
	nodeIdLastProcessed BIGINT(20),
	nodeIdLastDisplayed BIGINT(20),
	nodeIdLastDataSubmitted BIGINT(20),
	data_ LONGTEXT null,
	lastErrorCode BIGINT(20),
	lastErrorMsg VARCHAR(75) null,
	lastErrorDate DATETIME null,
	currentStatusTypeApprovers VARCHAR(75) null,
	currentNodeSubmitters VARCHAR(75) null,
	lock_ INTEGER,
	lockDate DATETIME null,
	userIdSupervisor BIGINT(20),
	userIdAgent BIGINT(20),
	closedStageId BIGINT(20),
	closedDate DATETIME null,
	closedReasonCatId BIGINT(20),
	closedDescription VARCHAR(75) null,
	convertedFromProcessStateId BIGINT(20),
	convertedToProcessStateId BIGINT(20),
	activeStatus INTEGER,
	amount VARCHAR(75) null,
	sourceClassId BIGINT(20),
	sourceEntityID BIGINT(20)
);

create table SPPEProcessStatusType (
	uuid_ VARCHAR(75) null,
	spPEProcessStatusTypeId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	spPEProcessId BIGINT(20),
	statusName VARCHAR(75) null,
	seqNo BIGINT(20),
	approveTemplateId BIGINT(20),
	rejectTemplateId BIGINT(20),
	spPEProcessStageId BIGINT(20)
);

create table SPPERule (
	uuid_ VARCHAR(75) null,
	spPERuleId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	spPERuleSetId BIGINT(20),
	name VARCHAR(75) null,
	type_ VARCHAR(75) null,
	definition LONGTEXT null,
	sequenceNO BIGINT(20)
);

create table SPPERuleSet (
	uuid_ VARCHAR(75) null,
	spPERuleSetId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	name VARCHAR(75) null,
	componentType VARCHAR(75) null,
	componentId VARCHAR(75) null,
	status BIGINT(20),
	formVersion VARCHAR(75) null
);

create table SPPESupervisor (
	spPESupervisorId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	filter1 VARCHAR(75) null,
	filter2 VARCHAR(75) null,
	filter3 VARCHAR(75) null,
	filter4 VARCHAR(75) null,
	filter5 VARCHAR(75) null,
	supervisorId BIGINT(20)
);