/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.sppayment.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SPPurchase service. Represents a row in the &quot;SPPurchase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.sppayment.model.impl.SPPurchaseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.sppayment.model.impl.SPPurchaseImpl}.
 * </p>
 *
 * @author pradeep
 * @see SPPurchase
 * @see com.sambaash.platform.srv.sppayment.model.impl.SPPurchaseImpl
 * @see com.sambaash.platform.srv.sppayment.model.impl.SPPurchaseModelImpl
 * @generated
 */
public interface SPPurchaseModel extends BaseModel<SPPurchase>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s p purchase model instance should use the {@link SPPurchase} interface instead.
	 */

	/**
	 * Returns the primary key of this s p purchase.
	 *
	 * @return the primary key of this s p purchase
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s p purchase.
	 *
	 * @param primaryKey the primary key of this s p purchase
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp purchase ID of this s p purchase.
	 *
	 * @return the sp purchase ID of this s p purchase
	 */
	public long getSpPurchaseId();

	/**
	 * Sets the sp purchase ID of this s p purchase.
	 *
	 * @param spPurchaseId the sp purchase ID of this s p purchase
	 */
	public void setSpPurchaseId(long spPurchaseId);

	/**
	 * Returns the group ID of this s p purchase.
	 *
	 * @return the group ID of this s p purchase
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this s p purchase.
	 *
	 * @param groupId the group ID of this s p purchase
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the cart ID of this s p purchase.
	 *
	 * @return the cart ID of this s p purchase
	 */
	public long getCartId();

	/**
	 * Sets the cart ID of this s p purchase.
	 *
	 * @param cartId the cart ID of this s p purchase
	 */
	public void setCartId(long cartId);

	/**
	 * Returns the ext payment ID of this s p purchase.
	 *
	 * @return the ext payment ID of this s p purchase
	 */
	@AutoEscape
	public String getExtPaymentId();

	/**
	 * Sets the ext payment ID of this s p purchase.
	 *
	 * @param extPaymentId the ext payment ID of this s p purchase
	 */
	public void setExtPaymentId(String extPaymentId);

	/**
	 * Returns the ext status of this s p purchase.
	 *
	 * @return the ext status of this s p purchase
	 */
	@AutoEscape
	public String getExtStatus();

	/**
	 * Sets the ext status of this s p purchase.
	 *
	 * @param extStatus the ext status of this s p purchase
	 */
	public void setExtStatus(String extStatus);

	/**
	 * Returns the ext error code of this s p purchase.
	 *
	 * @return the ext error code of this s p purchase
	 */
	public long getExtErrorCode();

	/**
	 * Sets the ext error code of this s p purchase.
	 *
	 * @param extErrorCode the ext error code of this s p purchase
	 */
	public void setExtErrorCode(long extErrorCode);

	/**
	 * Returns the ext error msg of this s p purchase.
	 *
	 * @return the ext error msg of this s p purchase
	 */
	@AutoEscape
	public String getExtErrorMsg();

	/**
	 * Sets the ext error msg of this s p purchase.
	 *
	 * @param extErrorMsg the ext error msg of this s p purchase
	 */
	public void setExtErrorMsg(String extErrorMsg);

	/**
	 * Returns the company ID of this s p purchase.
	 *
	 * @return the company ID of this s p purchase
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this s p purchase.
	 *
	 * @param companyId the company ID of this s p purchase
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this s p purchase.
	 *
	 * @return the user ID of this s p purchase
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this s p purchase.
	 *
	 * @param userId the user ID of this s p purchase
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s p purchase.
	 *
	 * @return the user uuid of this s p purchase
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s p purchase.
	 *
	 * @param userUuid the user uuid of this s p purchase
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this s p purchase.
	 *
	 * @return the user name of this s p purchase
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this s p purchase.
	 *
	 * @param userName the user name of this s p purchase
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this s p purchase.
	 *
	 * @return the create date of this s p purchase
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this s p purchase.
	 *
	 * @param createDate the create date of this s p purchase
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this s p purchase.
	 *
	 * @return the modified date of this s p purchase
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this s p purchase.
	 *
	 * @param modifiedDate the modified date of this s p purchase
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.sppayment.model.SPPurchase spPurchase);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.sppayment.model.SPPurchase> toCacheModel();

	@Override
	public com.sambaash.platform.srv.sppayment.model.SPPurchase toEscapedModel();

	@Override
	public com.sambaash.platform.srv.sppayment.model.SPPurchase toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}