/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.spservices.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MembershipPackagePromotionCode service. Represents a row in the &quot;SPMembershipPackagePromotionCode&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.spservices.model.impl.MembershipPackagePromotionCodeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.spservices.model.impl.MembershipPackagePromotionCodeImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see MembershipPackagePromotionCode
 * @see com.sambaash.platform.srv.spservices.model.impl.MembershipPackagePromotionCodeImpl
 * @see com.sambaash.platform.srv.spservices.model.impl.MembershipPackagePromotionCodeModelImpl
 * @generated
 */
public interface MembershipPackagePromotionCodeModel extends BaseModel<MembershipPackagePromotionCode> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a membership package promotion code model instance should use the {@link MembershipPackagePromotionCode} interface instead.
	 */

	/**
	 * Returns the primary key of this membership package promotion code.
	 *
	 * @return the primary key of this membership package promotion code
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this membership package promotion code.
	 *
	 * @param primaryKey the primary key of this membership package promotion code
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the promotion code_id of this membership package promotion code.
	 *
	 * @return the promotion code_id of this membership package promotion code
	 */
	public long getPromotionCode_id();

	/**
	 * Sets the promotion code_id of this membership package promotion code.
	 *
	 * @param promotionCode_id the promotion code_id of this membership package promotion code
	 */
	public void setPromotionCode_id(long promotionCode_id);

	/**
	 * Returns the membership package_id of this membership package promotion code.
	 *
	 * @return the membership package_id of this membership package promotion code
	 */
	public long getMembershipPackage_id();

	/**
	 * Sets the membership package_id of this membership package promotion code.
	 *
	 * @param membershipPackage_id the membership package_id of this membership package promotion code
	 */
	public void setMembershipPackage_id(long membershipPackage_id);

	/**
	 * Returns the promotion code of this membership package promotion code.
	 *
	 * @return the promotion code of this membership package promotion code
	 */
	@AutoEscape
	public String getPromotionCode();

	/**
	 * Sets the promotion code of this membership package promotion code.
	 *
	 * @param promotionCode the promotion code of this membership package promotion code
	 */
	public void setPromotionCode(String promotionCode);

	/**
	 * Returns the promotion from of this membership package promotion code.
	 *
	 * @return the promotion from of this membership package promotion code
	 */
	public Date getPromotionFrom();

	/**
	 * Sets the promotion from of this membership package promotion code.
	 *
	 * @param promotionFrom the promotion from of this membership package promotion code
	 */
	public void setPromotionFrom(Date promotionFrom);

	/**
	 * Returns the promotion to of this membership package promotion code.
	 *
	 * @return the promotion to of this membership package promotion code
	 */
	public Date getPromotionTo();

	/**
	 * Sets the promotion to of this membership package promotion code.
	 *
	 * @param promotionTo the promotion to of this membership package promotion code
	 */
	public void setPromotionTo(Date promotionTo);

	/**
	 * Returns the discount of this membership package promotion code.
	 *
	 * @return the discount of this membership package promotion code
	 */
	@AutoEscape
	public String getDiscount();

	/**
	 * Sets the discount of this membership package promotion code.
	 *
	 * @param discount the discount of this membership package promotion code
	 */
	public void setDiscount(String discount);

	/**
	 * Returns the extra1 of this membership package promotion code.
	 *
	 * @return the extra1 of this membership package promotion code
	 */
	@AutoEscape
	public String getExtra1();

	/**
	 * Sets the extra1 of this membership package promotion code.
	 *
	 * @param extra1 the extra1 of this membership package promotion code
	 */
	public void setExtra1(String extra1);

	/**
	 * Returns the extra2 of this membership package promotion code.
	 *
	 * @return the extra2 of this membership package promotion code
	 */
	@AutoEscape
	public String getExtra2();

	/**
	 * Sets the extra2 of this membership package promotion code.
	 *
	 * @param extra2 the extra2 of this membership package promotion code
	 */
	public void setExtra2(String extra2);

	/**
	 * Returns the extra3 of this membership package promotion code.
	 *
	 * @return the extra3 of this membership package promotion code
	 */
	@AutoEscape
	public String getExtra3();

	/**
	 * Sets the extra3 of this membership package promotion code.
	 *
	 * @param extra3 the extra3 of this membership package promotion code
	 */
	public void setExtra3(String extra3);

	/**
	 * Returns the extra4 of this membership package promotion code.
	 *
	 * @return the extra4 of this membership package promotion code
	 */
	@AutoEscape
	public String getExtra4();

	/**
	 * Sets the extra4 of this membership package promotion code.
	 *
	 * @param extra4 the extra4 of this membership package promotion code
	 */
	public void setExtra4(String extra4);

	/**
	 * Returns the extra5 of this membership package promotion code.
	 *
	 * @return the extra5 of this membership package promotion code
	 */
	@AutoEscape
	public String getExtra5();

	/**
	 * Sets the extra5 of this membership package promotion code.
	 *
	 * @param extra5 the extra5 of this membership package promotion code
	 */
	public void setExtra5(String extra5);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.spservices.model.MembershipPackagePromotionCode membershipPackagePromotionCode);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.spservices.model.MembershipPackagePromotionCode> toCacheModel();

	@Override
	public com.sambaash.platform.srv.spservices.model.MembershipPackagePromotionCode toEscapedModel();

	@Override
	public com.sambaash.platform.srv.spservices.model.MembershipPackagePromotionCode toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}