/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.spservices.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SPLdapMapping service. Represents a row in the &quot;SPLdapMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.spservices.model.impl.SPLdapMappingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.spservices.model.impl.SPLdapMappingImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see SPLdapMapping
 * @see com.sambaash.platform.srv.spservices.model.impl.SPLdapMappingImpl
 * @see com.sambaash.platform.srv.spservices.model.impl.SPLdapMappingModelImpl
 * @generated
 */
public interface SPLdapMappingModel extends BaseModel<SPLdapMapping>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s p ldap mapping model instance should use the {@link SPLdapMapping} interface instead.
	 */

	/**
	 * Returns the primary key of this s p ldap mapping.
	 *
	 * @return the primary key of this s p ldap mapping
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s p ldap mapping.
	 *
	 * @param primaryKey the primary key of this s p ldap mapping
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp ldap mapping ID of this s p ldap mapping.
	 *
	 * @return the sp ldap mapping ID of this s p ldap mapping
	 */
	public long getSpLdapMappingId();

	/**
	 * Sets the sp ldap mapping ID of this s p ldap mapping.
	 *
	 * @param spLdapMappingId the sp ldap mapping ID of this s p ldap mapping
	 */
	public void setSpLdapMappingId(long spLdapMappingId);

	/**
	 * Returns the group ID of this s p ldap mapping.
	 *
	 * @return the group ID of this s p ldap mapping
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this s p ldap mapping.
	 *
	 * @param groupId the group ID of this s p ldap mapping
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this s p ldap mapping.
	 *
	 * @return the company ID of this s p ldap mapping
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this s p ldap mapping.
	 *
	 * @param companyId the company ID of this s p ldap mapping
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this s p ldap mapping.
	 *
	 * @return the user ID of this s p ldap mapping
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this s p ldap mapping.
	 *
	 * @param userId the user ID of this s p ldap mapping
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s p ldap mapping.
	 *
	 * @return the user uuid of this s p ldap mapping
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s p ldap mapping.
	 *
	 * @param userUuid the user uuid of this s p ldap mapping
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this s p ldap mapping.
	 *
	 * @return the user name of this s p ldap mapping
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this s p ldap mapping.
	 *
	 * @param userName the user name of this s p ldap mapping
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this s p ldap mapping.
	 *
	 * @return the create date of this s p ldap mapping
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this s p ldap mapping.
	 *
	 * @param createDate the create date of this s p ldap mapping
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this s p ldap mapping.
	 *
	 * @return the modified date of this s p ldap mapping
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this s p ldap mapping.
	 *
	 * @param modifiedDate the modified date of this s p ldap mapping
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the country ID of this s p ldap mapping.
	 *
	 * @return the country ID of this s p ldap mapping
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this s p ldap mapping.
	 *
	 * @param countryId the country ID of this s p ldap mapping
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the department ID of this s p ldap mapping.
	 *
	 * @return the department ID of this s p ldap mapping
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this s p ldap mapping.
	 *
	 * @param departmentId the department ID of this s p ldap mapping
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the country department ID of this s p ldap mapping.
	 *
	 * @return the country department ID of this s p ldap mapping
	 */
	public long getCountryDepartmentId();

	/**
	 * Sets the country department ID of this s p ldap mapping.
	 *
	 * @param countryDepartmentId the country department ID of this s p ldap mapping
	 */
	public void setCountryDepartmentId(long countryDepartmentId);

	/**
	 * Returns the ldap country of this s p ldap mapping.
	 *
	 * @return the ldap country of this s p ldap mapping
	 */
	@AutoEscape
	public String getLdapCountry();

	/**
	 * Sets the ldap country of this s p ldap mapping.
	 *
	 * @param ldapCountry the ldap country of this s p ldap mapping
	 */
	public void setLdapCountry(String ldapCountry);

	/**
	 * Returns the ldap department of this s p ldap mapping.
	 *
	 * @return the ldap department of this s p ldap mapping
	 */
	@AutoEscape
	public String getLdapDepartment();

	/**
	 * Sets the ldap department of this s p ldap mapping.
	 *
	 * @param ldapDepartment the ldap department of this s p ldap mapping
	 */
	public void setLdapDepartment(String ldapDepartment);

	/**
	 * Returns the ldap company of this s p ldap mapping.
	 *
	 * @return the ldap company of this s p ldap mapping
	 */
	@AutoEscape
	public String getLdapCompany();

	/**
	 * Sets the ldap company of this s p ldap mapping.
	 *
	 * @param ldapCompany the ldap company of this s p ldap mapping
	 */
	public void setLdapCompany(String ldapCompany);

	/**
	 * Returns the default role ID of this s p ldap mapping.
	 *
	 * @return the default role ID of this s p ldap mapping
	 */
	public long getDefaultRoleId();

	/**
	 * Sets the default role ID of this s p ldap mapping.
	 *
	 * @param defaultRoleId the default role ID of this s p ldap mapping
	 */
	public void setDefaultRoleId(long defaultRoleId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.spservices.model.SPLdapMapping spLdapMapping);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.spservices.model.SPLdapMapping> toCacheModel();

	@Override
	public com.sambaash.platform.srv.spservices.model.SPLdapMapping toEscapedModel();

	@Override
	public com.sambaash.platform.srv.spservices.model.SPLdapMapping toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}