/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.spservices.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SPLikes service. Represents a row in the &quot;SPLikes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.spservices.model.impl.SPLikesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.spservices.model.impl.SPLikesImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see SPLikes
 * @see com.sambaash.platform.srv.spservices.model.impl.SPLikesImpl
 * @see com.sambaash.platform.srv.spservices.model.impl.SPLikesModelImpl
 * @generated
 */
public interface SPLikesModel extends BaseModel<SPLikes>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s p likes model instance should use the {@link SPLikes} interface instead.
	 */

	/**
	 * Returns the primary key of this s p likes.
	 *
	 * @return the primary key of this s p likes
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s p likes.
	 *
	 * @param primaryKey the primary key of this s p likes
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this s p likes.
	 *
	 * @return the uuid of this s p likes
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this s p likes.
	 *
	 * @param uuid the uuid of this s p likes
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sp likes ID of this s p likes.
	 *
	 * @return the sp likes ID of this s p likes
	 */
	public long getSpLikesId();

	/**
	 * Sets the sp likes ID of this s p likes.
	 *
	 * @param spLikesId the sp likes ID of this s p likes
	 */
	public void setSpLikesId(long spLikesId);

	/**
	 * Returns the group ID of this s p likes.
	 *
	 * @return the group ID of this s p likes
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this s p likes.
	 *
	 * @param groupId the group ID of this s p likes
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this s p likes.
	 *
	 * @return the company ID of this s p likes
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this s p likes.
	 *
	 * @param companyId the company ID of this s p likes
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this s p likes.
	 *
	 * @return the user ID of this s p likes
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this s p likes.
	 *
	 * @param userId the user ID of this s p likes
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s p likes.
	 *
	 * @return the user uuid of this s p likes
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s p likes.
	 *
	 * @param userUuid the user uuid of this s p likes
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this s p likes.
	 *
	 * @return the user name of this s p likes
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this s p likes.
	 *
	 * @param userName the user name of this s p likes
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this s p likes.
	 *
	 * @return the create date of this s p likes
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this s p likes.
	 *
	 * @param createDate the create date of this s p likes
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this s p likes.
	 *
	 * @return the modified date of this s p likes
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this s p likes.
	 *
	 * @param modifiedDate the modified date of this s p likes
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the layout set ID of this s p likes.
	 *
	 * @return the layout set ID of this s p likes
	 */
	public long getLayoutSetId();

	/**
	 * Sets the layout set ID of this s p likes.
	 *
	 * @param layoutSetId the layout set ID of this s p likes
	 */
	public void setLayoutSetId(long layoutSetId);

	/**
	 * Returns the action of this s p likes.
	 *
	 * @return the action of this s p likes
	 */
	@AutoEscape
	public String getAction();

	/**
	 * Sets the action of this s p likes.
	 *
	 * @param action the action of this s p likes
	 */
	public void setAction(String action);

	/**
	 * Returns the actor user ID of this s p likes.
	 *
	 * @return the actor user ID of this s p likes
	 */
	public long getActorUserId();

	/**
	 * Sets the actor user ID of this s p likes.
	 *
	 * @param actorUserId the actor user ID of this s p likes
	 */
	public void setActorUserId(long actorUserId);

	/**
	 * Returns the actor user uuid of this s p likes.
	 *
	 * @return the actor user uuid of this s p likes
	 * @throws SystemException if a system exception occurred
	 */
	public String getActorUserUuid() throws SystemException;

	/**
	 * Sets the actor user uuid of this s p likes.
	 *
	 * @param actorUserUuid the actor user uuid of this s p likes
	 */
	public void setActorUserUuid(String actorUserUuid);

	/**
	 * Returns the class ID of this s p likes.
	 *
	 * @return the class ID of this s p likes
	 */
	public long getClassId();

	/**
	 * Sets the class ID of this s p likes.
	 *
	 * @param classId the class ID of this s p likes
	 */
	public void setClassId(long classId);

	/**
	 * Returns the class name of this s p likes.
	 *
	 * @return the class name of this s p likes
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this s p likes.
	 *
	 * @param className the class name of this s p likes
	 */
	public void setClassName(String className);

	/**
	 * Returns the class p k of this s p likes.
	 *
	 * @return the class p k of this s p likes
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this s p likes.
	 *
	 * @param classPK the class p k of this s p likes
	 */
	public void setClassPK(long classPK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.spservices.model.SPLikes spLikes);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.spservices.model.SPLikes> toCacheModel();

	@Override
	public com.sambaash.platform.srv.spservices.model.SPLikes toEscapedModel();

	@Override
	public com.sambaash.platform.srv.spservices.model.SPLikes toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}