/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.legalandcontract.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ClassMaster service. Represents a row in the &quot;SPClassMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.legalandcontract.model.impl.ClassMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.legalandcontract.model.impl.ClassMasterImpl}.
 * </p>
 *
 * @author nareshchebolu
 * @see ClassMaster
 * @see com.sambaash.platform.srv.legalandcontract.model.impl.ClassMasterImpl
 * @see com.sambaash.platform.srv.legalandcontract.model.impl.ClassMasterModelImpl
 * @generated
 */
public interface ClassMasterModel extends BaseModel<ClassMaster>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a class master model instance should use the {@link ClassMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this class master.
	 *
	 * @return the primary key of this class master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this class master.
	 *
	 * @param primaryKey the primary key of this class master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this class master.
	 *
	 * @return the uuid of this class master
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this class master.
	 *
	 * @param uuid the uuid of this class master
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sp class ID of this class master.
	 *
	 * @return the sp class ID of this class master
	 */
	public long getSpClassId();

	/**
	 * Sets the sp class ID of this class master.
	 *
	 * @param spClassId the sp class ID of this class master
	 */
	public void setSpClassId(long spClassId);

	/**
	 * Returns the group ID of this class master.
	 *
	 * @return the group ID of this class master
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this class master.
	 *
	 * @param groupId the group ID of this class master
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this class master.
	 *
	 * @return the company ID of this class master
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this class master.
	 *
	 * @param companyId the company ID of this class master
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this class master.
	 *
	 * @return the user ID of this class master
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this class master.
	 *
	 * @param userId the user ID of this class master
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this class master.
	 *
	 * @return the user uuid of this class master
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this class master.
	 *
	 * @param userUuid the user uuid of this class master
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this class master.
	 *
	 * @return the user name of this class master
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this class master.
	 *
	 * @param userName the user name of this class master
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this class master.
	 *
	 * @return the create date of this class master
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this class master.
	 *
	 * @param createDate the create date of this class master
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this class master.
	 *
	 * @return the modified date of this class master
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this class master.
	 *
	 * @param modifiedDate the modified date of this class master
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the code of this class master.
	 *
	 * @return the code of this class master
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this class master.
	 *
	 * @param code the code of this class master
	 */
	public void setCode(String code);

	/**
	 * Returns the country of this class master.
	 *
	 * @return the country of this class master
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this class master.
	 *
	 * @param country the country of this class master
	 */
	public void setCountry(String country);

	/**
	 * Returns the filed by of this class master.
	 *
	 * @return the filed by of this class master
	 */
	@AutoEscape
	public String getFiledBy();

	/**
	 * Sets the filed by of this class master.
	 *
	 * @param filedBy the filed by of this class master
	 */
	public void setFiledBy(String filedBy);

	/**
	 * Returns the custom field1 of this class master.
	 *
	 * @return the custom field1 of this class master
	 */
	@AutoEscape
	public String getCustomField1();

	/**
	 * Sets the custom field1 of this class master.
	 *
	 * @param customField1 the custom field1 of this class master
	 */
	public void setCustomField1(String customField1);

	/**
	 * Returns the custom field2 of this class master.
	 *
	 * @return the custom field2 of this class master
	 */
	@AutoEscape
	public String getCustomField2();

	/**
	 * Sets the custom field2 of this class master.
	 *
	 * @param customField2 the custom field2 of this class master
	 */
	public void setCustomField2(String customField2);

	/**
	 * Returns the custom date1 of this class master.
	 *
	 * @return the custom date1 of this class master
	 */
	public Date getCustomDate1();

	/**
	 * Sets the custom date1 of this class master.
	 *
	 * @param customDate1 the custom date1 of this class master
	 */
	public void setCustomDate1(Date customDate1);

	/**
	 * Returns the custom date2 of this class master.
	 *
	 * @return the custom date2 of this class master
	 */
	public Date getCustomDate2();

	/**
	 * Sets the custom date2 of this class master.
	 *
	 * @param customDate2 the custom date2 of this class master
	 */
	public void setCustomDate2(Date customDate2);

	/**
	 * Returns the version of this class master.
	 *
	 * @return the version of this class master
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this class master.
	 *
	 * @param version the version of this class master
	 */
	public void setVersion(String version);

	/**
	 * Returns the root sp class ID of this class master.
	 *
	 * @return the root sp class ID of this class master
	 */
	public long getRootSpClassId();

	/**
	 * Sets the root sp class ID of this class master.
	 *
	 * @param rootSpClassId the root sp class ID of this class master
	 */
	public void setRootSpClassId(long rootSpClassId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.legalandcontract.model.ClassMaster classMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.legalandcontract.model.ClassMaster> toCacheModel();

	@Override
	public com.sambaash.platform.srv.legalandcontract.model.ClassMaster toEscapedModel();

	@Override
	public com.sambaash.platform.srv.legalandcontract.model.ClassMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}