/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.legalandcontract.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Trademarks service. Represents a row in the &quot;SPTrademarksMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.legalandcontract.model.impl.TrademarksModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.legalandcontract.model.impl.TrademarksImpl}.
 * </p>
 *
 * @author nareshchebolu
 * @see Trademarks
 * @see com.sambaash.platform.srv.legalandcontract.model.impl.TrademarksImpl
 * @see com.sambaash.platform.srv.legalandcontract.model.impl.TrademarksModelImpl
 * @generated
 */
public interface TrademarksModel extends BaseModel<Trademarks>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a trademarks model instance should use the {@link Trademarks} interface instead.
	 */

	/**
	 * Returns the primary key of this trademarks.
	 *
	 * @return the primary key of this trademarks
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this trademarks.
	 *
	 * @param primaryKey the primary key of this trademarks
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this trademarks.
	 *
	 * @return the uuid of this trademarks
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this trademarks.
	 *
	 * @param uuid the uuid of this trademarks
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sp trademarks ID of this trademarks.
	 *
	 * @return the sp trademarks ID of this trademarks
	 */
	public long getSpTrademarksId();

	/**
	 * Sets the sp trademarks ID of this trademarks.
	 *
	 * @param spTrademarksId the sp trademarks ID of this trademarks
	 */
	public void setSpTrademarksId(long spTrademarksId);

	/**
	 * Returns the group ID of this trademarks.
	 *
	 * @return the group ID of this trademarks
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this trademarks.
	 *
	 * @param groupId the group ID of this trademarks
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this trademarks.
	 *
	 * @return the company ID of this trademarks
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this trademarks.
	 *
	 * @param companyId the company ID of this trademarks
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this trademarks.
	 *
	 * @return the user ID of this trademarks
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this trademarks.
	 *
	 * @param userId the user ID of this trademarks
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this trademarks.
	 *
	 * @return the user uuid of this trademarks
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this trademarks.
	 *
	 * @param userUuid the user uuid of this trademarks
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this trademarks.
	 *
	 * @return the user name of this trademarks
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this trademarks.
	 *
	 * @param userName the user name of this trademarks
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this trademarks.
	 *
	 * @return the create date of this trademarks
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this trademarks.
	 *
	 * @param createDate the create date of this trademarks
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this trademarks.
	 *
	 * @return the modified date of this trademarks
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this trademarks.
	 *
	 * @param modifiedDate the modified date of this trademarks
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the registration number of this trademarks.
	 *
	 * @return the registration number of this trademarks
	 */
	@AutoEscape
	public String getRegistrationNumber();

	/**
	 * Sets the registration number of this trademarks.
	 *
	 * @param registrationNumber the registration number of this trademarks
	 */
	public void setRegistrationNumber(String registrationNumber);

	/**
	 * Returns the application no of this trademarks.
	 *
	 * @return the application no of this trademarks
	 */
	@AutoEscape
	public String getApplicationNo();

	/**
	 * Sets the application no of this trademarks.
	 *
	 * @param applicationNo the application no of this trademarks
	 */
	public void setApplicationNo(String applicationNo);

	/**
	 * Returns the country of this trademarks.
	 *
	 * @return the country of this trademarks
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this trademarks.
	 *
	 * @param country the country of this trademarks
	 */
	public void setCountry(String country);

	/**
	 * Returns the trademark of this trademarks.
	 *
	 * @return the trademark of this trademarks
	 */
	@AutoEscape
	public String getTrademark();

	/**
	 * Sets the trademark of this trademarks.
	 *
	 * @param trademark the trademark of this trademarks
	 */
	public void setTrademark(String trademark);

	/**
	 * Returns the trademark localized of this trademarks.
	 *
	 * @return the trademark localized of this trademarks
	 */
	@AutoEscape
	public String getTrademarkLocalized();

	/**
	 * Sets the trademark localized of this trademarks.
	 *
	 * @param trademarkLocalized the trademark localized of this trademarks
	 */
	public void setTrademarkLocalized(String trademarkLocalized);

	/**
	 * Returns the registered owner of this trademarks.
	 *
	 * @return the registered owner of this trademarks
	 */
	@AutoEscape
	public String getRegisteredOwner();

	/**
	 * Sets the registered owner of this trademarks.
	 *
	 * @param registeredOwner the registered owner of this trademarks
	 */
	public void setRegisteredOwner(String registeredOwner);

	/**
	 * Returns the application date of this trademarks.
	 *
	 * @return the application date of this trademarks
	 */
	public Date getApplicationDate();

	/**
	 * Sets the application date of this trademarks.
	 *
	 * @param applicationDate the application date of this trademarks
	 */
	public void setApplicationDate(Date applicationDate);

	/**
	 * Returns the first registration date of this trademarks.
	 *
	 * @return the first registration date of this trademarks
	 */
	public Date getFirstRegistrationDate();

	/**
	 * Sets the first registration date of this trademarks.
	 *
	 * @param firstRegistrationDate the first registration date of this trademarks
	 */
	public void setFirstRegistrationDate(Date firstRegistrationDate);

	/**
	 * Returns the renewal date of this trademarks.
	 *
	 * @return the renewal date of this trademarks
	 */
	public Date getRenewalDate();

	/**
	 * Sets the renewal date of this trademarks.
	 *
	 * @param renewalDate the renewal date of this trademarks
	 */
	public void setRenewalDate(Date renewalDate);

	/**
	 * Returns the goods services of this trademarks.
	 *
	 * @return the goods services of this trademarks
	 */
	@AutoEscape
	public String getGoodsServices();

	/**
	 * Sets the goods services of this trademarks.
	 *
	 * @param goodsServices the goods services of this trademarks
	 */
	public void setGoodsServices(String goodsServices);

	/**
	 * Returns the pending comments of this trademarks.
	 *
	 * @return the pending comments of this trademarks
	 */
	@AutoEscape
	public String getPendingComments();

	/**
	 * Sets the pending comments of this trademarks.
	 *
	 * @param pendingComments the pending comments of this trademarks
	 */
	public void setPendingComments(String pendingComments);

	/**
	 * Returns the sp agency ID of this trademarks.
	 *
	 * @return the sp agency ID of this trademarks
	 */
	public long getSpAgencyId();

	/**
	 * Sets the sp agency ID of this trademarks.
	 *
	 * @param spAgencyId the sp agency ID of this trademarks
	 */
	public void setSpAgencyId(long spAgencyId);

	/**
	 * Returns the class description of this trademarks.
	 *
	 * @return the class description of this trademarks
	 */
	@AutoEscape
	public String getClassDescription();

	/**
	 * Sets the class description of this trademarks.
	 *
	 * @param classDescription the class description of this trademarks
	 */
	public void setClassDescription(String classDescription);

	/**
	 * Returns the legal conf remarks of this trademarks.
	 *
	 * @return the legal conf remarks of this trademarks
	 */
	@AutoEscape
	public String getLegalConfRemarks();

	/**
	 * Sets the legal conf remarks of this trademarks.
	 *
	 * @param legalConfRemarks the legal conf remarks of this trademarks
	 */
	public void setLegalConfRemarks(String legalConfRemarks);

	/**
	 * Returns the workflow status of this trademarks.
	 *
	 * @return the workflow status of this trademarks
	 */
	public long getWorkflowStatus();

	/**
	 * Sets the workflow status of this trademarks.
	 *
	 * @param workflowStatus the workflow status of this trademarks
	 */
	public void setWorkflowStatus(long workflowStatus);

	/**
	 * Returns the custom field1 of this trademarks.
	 *
	 * @return the custom field1 of this trademarks
	 */
	@AutoEscape
	public String getCustomField1();

	/**
	 * Sets the custom field1 of this trademarks.
	 *
	 * @param customField1 the custom field1 of this trademarks
	 */
	public void setCustomField1(String customField1);

	/**
	 * Returns the custom field2 of this trademarks.
	 *
	 * @return the custom field2 of this trademarks
	 */
	@AutoEscape
	public String getCustomField2();

	/**
	 * Sets the custom field2 of this trademarks.
	 *
	 * @param customField2 the custom field2 of this trademarks
	 */
	public void setCustomField2(String customField2);

	/**
	 * Returns the custom field3 of this trademarks.
	 *
	 * @return the custom field3 of this trademarks
	 */
	@AutoEscape
	public String getCustomField3();

	/**
	 * Sets the custom field3 of this trademarks.
	 *
	 * @param customField3 the custom field3 of this trademarks
	 */
	public void setCustomField3(String customField3);

	/**
	 * Returns the custom date1 of this trademarks.
	 *
	 * @return the custom date1 of this trademarks
	 */
	public Date getCustomDate1();

	/**
	 * Sets the custom date1 of this trademarks.
	 *
	 * @param customDate1 the custom date1 of this trademarks
	 */
	public void setCustomDate1(Date customDate1);

	/**
	 * Returns the custom date2 of this trademarks.
	 *
	 * @return the custom date2 of this trademarks
	 */
	public Date getCustomDate2();

	/**
	 * Sets the custom date2 of this trademarks.
	 *
	 * @param customDate2 the custom date2 of this trademarks
	 */
	public void setCustomDate2(Date customDate2);

	/**
	 * Returns the custom date3 of this trademarks.
	 *
	 * @return the custom date3 of this trademarks
	 */
	public Date getCustomDate3();

	/**
	 * Sets the custom date3 of this trademarks.
	 *
	 * @param customDate3 the custom date3 of this trademarks
	 */
	public void setCustomDate3(Date customDate3);

	/**
	 * Returns the class codes of this trademarks.
	 *
	 * @return the class codes of this trademarks
	 */
	@AutoEscape
	public String getClassCodes();

	/**
	 * Sets the class codes of this trademarks.
	 *
	 * @param classCodes the class codes of this trademarks
	 */
	public void setClassCodes(String classCodes);

	/**
	 * Returns the version of this trademarks.
	 *
	 * @return the version of this trademarks
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this trademarks.
	 *
	 * @param version the version of this trademarks
	 */
	public void setVersion(String version);

	/**
	 * Returns the trademark type of this trademarks.
	 *
	 * @return the trademark type of this trademarks
	 */
	@AutoEscape
	public String getTrademarkType();

	/**
	 * Sets the trademark type of this trademarks.
	 *
	 * @param trademarkType the trademark type of this trademarks
	 */
	public void setTrademarkType(String trademarkType);

	/**
	 * Returns the root sp trademarks ID of this trademarks.
	 *
	 * @return the root sp trademarks ID of this trademarks
	 */
	public long getRootSpTrademarksId();

	/**
	 * Sets the root sp trademarks ID of this trademarks.
	 *
	 * @param rootSpTrademarksId the root sp trademarks ID of this trademarks
	 */
	public void setRootSpTrademarksId(long rootSpTrademarksId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.legalandcontract.model.Trademarks trademarks);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.legalandcontract.model.Trademarks> toCacheModel();

	@Override
	public com.sambaash.platform.srv.legalandcontract.model.Trademarks toEscapedModel();

	@Override
	public com.sambaash.platform.srv.legalandcontract.model.Trademarks toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}