/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FeeDetails service. Represents a row in the &quot;SPFeeDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.model.impl.FeeDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.model.impl.FeeDetailsImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see FeeDetails
 * @see com.sambaash.platform.srv.model.impl.FeeDetailsImpl
 * @see com.sambaash.platform.srv.model.impl.FeeDetailsModelImpl
 * @generated
 */
public interface FeeDetailsModel extends BaseModel<FeeDetails>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fee details model instance should use the {@link FeeDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this fee details.
	 *
	 * @return the primary key of this fee details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fee details.
	 *
	 * @param primaryKey the primary key of this fee details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp fee details ID of this fee details.
	 *
	 * @return the sp fee details ID of this fee details
	 */
	public long getSpFeeDetailsId();

	/**
	 * Sets the sp fee details ID of this fee details.
	 *
	 * @param spFeeDetailsId the sp fee details ID of this fee details
	 */
	public void setSpFeeDetailsId(long spFeeDetailsId);

	/**
	 * Returns the group ID of this fee details.
	 *
	 * @return the group ID of this fee details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this fee details.
	 *
	 * @param groupId the group ID of this fee details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this fee details.
	 *
	 * @return the company ID of this fee details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this fee details.
	 *
	 * @param companyId the company ID of this fee details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this fee details.
	 *
	 * @return the user ID of this fee details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this fee details.
	 *
	 * @param userId the user ID of this fee details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fee details.
	 *
	 * @return the user uuid of this fee details
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this fee details.
	 *
	 * @param userUuid the user uuid of this fee details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fee details.
	 *
	 * @return the user name of this fee details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this fee details.
	 *
	 * @param userName the user name of this fee details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fee details.
	 *
	 * @return the create date of this fee details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this fee details.
	 *
	 * @param createDate the create date of this fee details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fee details.
	 *
	 * @return the modified date of this fee details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fee details.
	 *
	 * @param modifiedDate the modified date of this fee details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fee type of this fee details.
	 *
	 * @return the fee type of this fee details
	 */
	public long getFeeType();

	/**
	 * Sets the fee type of this fee details.
	 *
	 * @param feeType the fee type of this fee details
	 */
	public void setFeeType(long feeType);

	/**
	 * Returns the fee desc of this fee details.
	 *
	 * @return the fee desc of this fee details
	 */
	@AutoEscape
	public String getFeeDesc();

	/**
	 * Sets the fee desc of this fee details.
	 *
	 * @param feeDesc the fee desc of this fee details
	 */
	public void setFeeDesc(String feeDesc);

	/**
	 * Returns the calculation base of this fee details.
	 *
	 * @return the calculation base of this fee details
	 */
	@AutoEscape
	public String getCalculationBase();

	/**
	 * Sets the calculation base of this fee details.
	 *
	 * @param calculationBase the calculation base of this fee details
	 */
	public void setCalculationBase(String calculationBase);

	/**
	 * Returns the amount of this fee details.
	 *
	 * @return the amount of this fee details
	 */
	@AutoEscape
	public String getAmount();

	/**
	 * Sets the amount of this fee details.
	 *
	 * @param amount the amount of this fee details
	 */
	public void setAmount(String amount);

	/**
	 * Returns the display order of this fee details.
	 *
	 * @return the display order of this fee details
	 */
	public long getDisplayOrder();

	/**
	 * Sets the display order of this fee details.
	 *
	 * @param displayOrder the display order of this fee details
	 */
	public void setDisplayOrder(long displayOrder);

	/**
	 * Returns the fund ID of this fee details.
	 *
	 * @return the fund ID of this fee details
	 */
	public long getFundId();

	/**
	 * Sets the fund ID of this fee details.
	 *
	 * @param fundId the fund ID of this fee details
	 */
	public void setFundId(long fundId);

	/**
	 * Returns the sp course ID of this fee details.
	 *
	 * @return the sp course ID of this fee details
	 */
	public long getSpCourseId();

	/**
	 * Sets the sp course ID of this fee details.
	 *
	 * @param spCourseId the sp course ID of this fee details
	 */
	public void setSpCourseId(long spCourseId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.sambaash.platform.srv.model.FeeDetails feeDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.model.FeeDetails> toCacheModel();

	@Override
	public com.sambaash.platform.srv.model.FeeDetails toEscapedModel();

	@Override
	public com.sambaash.platform.srv.model.FeeDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}