/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LearningDuration service. Represents a row in the &quot;SPLearningDuration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.model.impl.LearningDurationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.model.impl.LearningDurationImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see LearningDuration
 * @see com.sambaash.platform.srv.model.impl.LearningDurationImpl
 * @see com.sambaash.platform.srv.model.impl.LearningDurationModelImpl
 * @generated
 */
public interface LearningDurationModel extends BaseModel<LearningDuration>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a learning duration model instance should use the {@link LearningDuration} interface instead.
	 */

	/**
	 * Returns the primary key of this learning duration.
	 *
	 * @return the primary key of this learning duration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this learning duration.
	 *
	 * @param primaryKey the primary key of this learning duration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp learning duration ID of this learning duration.
	 *
	 * @return the sp learning duration ID of this learning duration
	 */
	public long getSpLearningDurationId();

	/**
	 * Sets the sp learning duration ID of this learning duration.
	 *
	 * @param spLearningDurationId the sp learning duration ID of this learning duration
	 */
	public void setSpLearningDurationId(long spLearningDurationId);

	/**
	 * Returns the group ID of this learning duration.
	 *
	 * @return the group ID of this learning duration
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this learning duration.
	 *
	 * @param groupId the group ID of this learning duration
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this learning duration.
	 *
	 * @return the company ID of this learning duration
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this learning duration.
	 *
	 * @param companyId the company ID of this learning duration
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this learning duration.
	 *
	 * @return the user ID of this learning duration
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this learning duration.
	 *
	 * @param userId the user ID of this learning duration
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this learning duration.
	 *
	 * @return the user uuid of this learning duration
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this learning duration.
	 *
	 * @param userUuid the user uuid of this learning duration
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this learning duration.
	 *
	 * @return the user name of this learning duration
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this learning duration.
	 *
	 * @param userName the user name of this learning duration
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this learning duration.
	 *
	 * @return the create date of this learning duration
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this learning duration.
	 *
	 * @param createDate the create date of this learning duration
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this learning duration.
	 *
	 * @return the modified date of this learning duration
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this learning duration.
	 *
	 * @param modifiedDate the modified date of this learning duration
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the sp course ID of this learning duration.
	 *
	 * @return the sp course ID of this learning duration
	 */
	public long getSpCourseId();

	/**
	 * Sets the sp course ID of this learning duration.
	 *
	 * @param spCourseId the sp course ID of this learning duration
	 */
	public void setSpCourseId(long spCourseId);

	/**
	 * Returns the title of this learning duration.
	 *
	 * @return the title of this learning duration
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this learning duration.
	 *
	 * @param title the title of this learning duration
	 */
	public void setTitle(String title);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.model.LearningDuration learningDuration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.model.LearningDuration> toCacheModel();

	@Override
	public com.sambaash.platform.srv.model.LearningDuration toEscapedModel();

	@Override
	public com.sambaash.platform.srv.model.LearningDuration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}