/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Module service. Represents a row in the &quot;SPModule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.model.impl.ModuleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.model.impl.ModuleImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see Module
 * @see com.sambaash.platform.srv.model.impl.ModuleImpl
 * @see com.sambaash.platform.srv.model.impl.ModuleModelImpl
 * @generated
 */
public interface ModuleModel extends BaseModel<Module>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a module model instance should use the {@link Module} interface instead.
	 */

	/**
	 * Returns the primary key of this module.
	 *
	 * @return the primary key of this module
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this module.
	 *
	 * @param primaryKey the primary key of this module
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp module ID of this module.
	 *
	 * @return the sp module ID of this module
	 */
	public long getSpModuleId();

	/**
	 * Sets the sp module ID of this module.
	 *
	 * @param spModuleId the sp module ID of this module
	 */
	public void setSpModuleId(long spModuleId);

	/**
	 * Returns the group ID of this module.
	 *
	 * @return the group ID of this module
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this module.
	 *
	 * @param groupId the group ID of this module
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this module.
	 *
	 * @return the company ID of this module
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this module.
	 *
	 * @param companyId the company ID of this module
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this module.
	 *
	 * @return the user ID of this module
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this module.
	 *
	 * @param userId the user ID of this module
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this module.
	 *
	 * @return the user uuid of this module
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this module.
	 *
	 * @param userUuid the user uuid of this module
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this module.
	 *
	 * @return the user name of this module
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this module.
	 *
	 * @param userName the user name of this module
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this module.
	 *
	 * @return the create date of this module
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this module.
	 *
	 * @param createDate the create date of this module
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this module.
	 *
	 * @return the modified date of this module
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this module.
	 *
	 * @param modifiedDate the modified date of this module
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the country ID of this module.
	 *
	 * @return the country ID of this module
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this module.
	 *
	 * @param countryId the country ID of this module
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the module code of this module.
	 *
	 * @return the module code of this module
	 */
	@AutoEscape
	public String getModuleCode();

	/**
	 * Sets the module code of this module.
	 *
	 * @param moduleCode the module code of this module
	 */
	public void setModuleCode(String moduleCode);

	/**
	 * Returns the module name of this module.
	 *
	 * @return the module name of this module
	 */
	@AutoEscape
	public String getModuleName();

	/**
	 * Sets the module name of this module.
	 *
	 * @param moduleName the module name of this module
	 */
	public void setModuleName(String moduleName);

	/**
	 * Returns the module desc of this module.
	 *
	 * @return the module desc of this module
	 */
	@AutoEscape
	public String getModuleDesc();

	/**
	 * Sets the module desc of this module.
	 *
	 * @param moduleDesc the module desc of this module
	 */
	public void setModuleDesc(String moduleDesc);

	/**
	 * Returns the module type of this module.
	 *
	 * @return the module type of this module
	 */
	public long getModuleType();

	/**
	 * Sets the module type of this module.
	 *
	 * @param moduleType the module type of this module
	 */
	public void setModuleType(long moduleType);

	/**
	 * Returns the credit value of this module.
	 *
	 * @return the credit value of this module
	 */
	public long getCreditValue();

	/**
	 * Sets the credit value of this module.
	 *
	 * @param creditValue the credit value of this module
	 */
	public void setCreditValue(long creditValue);

	/**
	 * Returns the module duration of this module.
	 *
	 * @return the module duration of this module
	 */
	@AutoEscape
	public String getModuleDuration();

	/**
	 * Sets the module duration of this module.
	 *
	 * @param moduleDuration the module duration of this module
	 */
	public void setModuleDuration(String moduleDuration);

	/**
	 * Returns the no of sessions of this module.
	 *
	 * @return the no of sessions of this module
	 */
	public long getNoOfSessions();

	/**
	 * Sets the no of sessions of this module.
	 *
	 * @param noOfSessions the no of sessions of this module
	 */
	public void setNoOfSessions(long noOfSessions);

	/**
	 * Returns the general desc of this module.
	 *
	 * @return the general desc of this module
	 */
	@AutoEscape
	public String getGeneralDesc();

	/**
	 * Sets the general desc of this module.
	 *
	 * @param generalDesc the general desc of this module
	 */
	public void setGeneralDesc(String generalDesc);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.sambaash.platform.srv.model.Module module);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.model.Module> toCacheModel();

	@Override
	public com.sambaash.platform.srv.model.Module toEscapedModel();

	@Override
	public com.sambaash.platform.srv.model.Module toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}