/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProductSupervisor service. Represents a row in the &quot;SPProductSupervisor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.model.impl.ProductSupervisorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.model.impl.ProductSupervisorImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see ProductSupervisor
 * @see com.sambaash.platform.srv.model.impl.ProductSupervisorImpl
 * @see com.sambaash.platform.srv.model.impl.ProductSupervisorModelImpl
 * @generated
 */
public interface ProductSupervisorModel extends BaseModel<ProductSupervisor>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product supervisor model instance should use the {@link ProductSupervisor} interface instead.
	 */

	/**
	 * Returns the primary key of this product supervisor.
	 *
	 * @return the primary key of this product supervisor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product supervisor.
	 *
	 * @param primaryKey the primary key of this product supervisor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp product supervisor ID of this product supervisor.
	 *
	 * @return the sp product supervisor ID of this product supervisor
	 */
	public long getSpProductSupervisorId();

	/**
	 * Sets the sp product supervisor ID of this product supervisor.
	 *
	 * @param spProductSupervisorId the sp product supervisor ID of this product supervisor
	 */
	public void setSpProductSupervisorId(long spProductSupervisorId);

	/**
	 * Returns the group ID of this product supervisor.
	 *
	 * @return the group ID of this product supervisor
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this product supervisor.
	 *
	 * @param groupId the group ID of this product supervisor
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this product supervisor.
	 *
	 * @return the company ID of this product supervisor
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this product supervisor.
	 *
	 * @param companyId the company ID of this product supervisor
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product supervisor.
	 *
	 * @return the user ID of this product supervisor
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this product supervisor.
	 *
	 * @param userId the user ID of this product supervisor
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product supervisor.
	 *
	 * @return the user uuid of this product supervisor
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this product supervisor.
	 *
	 * @param userUuid the user uuid of this product supervisor
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this product supervisor.
	 *
	 * @return the user name of this product supervisor
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this product supervisor.
	 *
	 * @param userName the user name of this product supervisor
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this product supervisor.
	 *
	 * @return the create date of this product supervisor
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this product supervisor.
	 *
	 * @param createDate the create date of this product supervisor
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product supervisor.
	 *
	 * @return the modified date of this product supervisor
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product supervisor.
	 *
	 * @param modifiedDate the modified date of this product supervisor
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the country name of this product supervisor.
	 *
	 * @return the country name of this product supervisor
	 */
	@AutoEscape
	public String getCountryName();

	/**
	 * Sets the country name of this product supervisor.
	 *
	 * @param countryName the country name of this product supervisor
	 */
	public void setCountryName(String countryName);

	/**
	 * Returns the country ID of this product supervisor.
	 *
	 * @return the country ID of this product supervisor
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this product supervisor.
	 *
	 * @param countryId the country ID of this product supervisor
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the product ID of this product supervisor.
	 *
	 * @return the product ID of this product supervisor
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product supervisor.
	 *
	 * @param productId the product ID of this product supervisor
	 */
	public void setProductId(long productId);

	/**
	 * Returns the supervisor ID of this product supervisor.
	 *
	 * @return the supervisor ID of this product supervisor
	 */
	public long getSupervisorId();

	/**
	 * Sets the supervisor ID of this product supervisor.
	 *
	 * @param supervisorId the supervisor ID of this product supervisor
	 */
	public void setSupervisorId(long supervisorId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.model.ProductSupervisor productSupervisor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.model.ProductSupervisor> toCacheModel();

	@Override
	public com.sambaash.platform.srv.model.ProductSupervisor toEscapedModel();

	@Override
	public com.sambaash.platform.srv.model.ProductSupervisor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}