/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StudentCourseFeeInstmnt service. Represents a row in the &quot;SPStudentCourseFeeInstmnt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.model.impl.StudentCourseFeeInstmntModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.model.impl.StudentCourseFeeInstmntImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see StudentCourseFeeInstmnt
 * @see com.sambaash.platform.srv.model.impl.StudentCourseFeeInstmntImpl
 * @see com.sambaash.platform.srv.model.impl.StudentCourseFeeInstmntModelImpl
 * @generated
 */
public interface StudentCourseFeeInstmntModel extends BaseModel<StudentCourseFeeInstmnt>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student course fee instmnt model instance should use the {@link StudentCourseFeeInstmnt} interface instead.
	 */

	/**
	 * Returns the primary key of this student course fee instmnt.
	 *
	 * @return the primary key of this student course fee instmnt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student course fee instmnt.
	 *
	 * @param primaryKey the primary key of this student course fee instmnt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp student course fee instmnt ID of this student course fee instmnt.
	 *
	 * @return the sp student course fee instmnt ID of this student course fee instmnt
	 */
	public long getSpStudentCourseFeeInstmntId();

	/**
	 * Sets the sp student course fee instmnt ID of this student course fee instmnt.
	 *
	 * @param spStudentCourseFeeInstmntId the sp student course fee instmnt ID of this student course fee instmnt
	 */
	public void setSpStudentCourseFeeInstmntId(long spStudentCourseFeeInstmntId);

	/**
	 * Returns the group ID of this student course fee instmnt.
	 *
	 * @return the group ID of this student course fee instmnt
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this student course fee instmnt.
	 *
	 * @param groupId the group ID of this student course fee instmnt
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this student course fee instmnt.
	 *
	 * @return the company ID of this student course fee instmnt
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this student course fee instmnt.
	 *
	 * @param companyId the company ID of this student course fee instmnt
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this student course fee instmnt.
	 *
	 * @return the user ID of this student course fee instmnt
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this student course fee instmnt.
	 *
	 * @param userId the user ID of this student course fee instmnt
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this student course fee instmnt.
	 *
	 * @return the user uuid of this student course fee instmnt
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this student course fee instmnt.
	 *
	 * @param userUuid the user uuid of this student course fee instmnt
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this student course fee instmnt.
	 *
	 * @return the user name of this student course fee instmnt
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this student course fee instmnt.
	 *
	 * @param userName the user name of this student course fee instmnt
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this student course fee instmnt.
	 *
	 * @return the create date of this student course fee instmnt
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this student course fee instmnt.
	 *
	 * @param createDate the create date of this student course fee instmnt
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this student course fee instmnt.
	 *
	 * @return the modified date of this student course fee instmnt
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this student course fee instmnt.
	 *
	 * @param modifiedDate the modified date of this student course fee instmnt
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the sp p e process state ID of this student course fee instmnt.
	 *
	 * @return the sp p e process state ID of this student course fee instmnt
	 */
	public long getSpPEProcessStateId();

	/**
	 * Sets the sp p e process state ID of this student course fee instmnt.
	 *
	 * @param spPEProcessStateId the sp p e process state ID of this student course fee instmnt
	 */
	public void setSpPEProcessStateId(long spPEProcessStateId);

	/**
	 * Returns the insmnt no of this student course fee instmnt.
	 *
	 * @return the insmnt no of this student course fee instmnt
	 */
	public int getInsmntNo();

	/**
	 * Sets the insmnt no of this student course fee instmnt.
	 *
	 * @param insmntNo the insmnt no of this student course fee instmnt
	 */
	public void setInsmntNo(int insmntNo);

	/**
	 * Returns the amount of this student course fee instmnt.
	 *
	 * @return the amount of this student course fee instmnt
	 */
	@AutoEscape
	public String getAmount();

	/**
	 * Sets the amount of this student course fee instmnt.
	 *
	 * @param amount the amount of this student course fee instmnt
	 */
	public void setAmount(String amount);

	/**
	 * Returns the date of this student course fee instmnt.
	 *
	 * @return the date of this student course fee instmnt
	 */
	public Date getDate();

	/**
	 * Sets the date of this student course fee instmnt.
	 *
	 * @param date the date of this student course fee instmnt
	 */
	public void setDate(Date date);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.model.StudentCourseFeeInstmnt studentCourseFeeInstmnt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.model.StudentCourseFeeInstmnt> toCacheModel();

	@Override
	public com.sambaash.platform.srv.model.StudentCourseFeeInstmnt toEscapedModel();

	@Override
	public com.sambaash.platform.srv.model.StudentCourseFeeInstmnt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}