/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StudyOption service. Represents a row in the &quot;SPCourseStudyOption&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.model.impl.StudyOptionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.model.impl.StudyOptionImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see StudyOption
 * @see com.sambaash.platform.srv.model.impl.StudyOptionImpl
 * @see com.sambaash.platform.srv.model.impl.StudyOptionModelImpl
 * @generated
 */
public interface StudyOptionModel extends BaseModel<StudyOption>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a study option model instance should use the {@link StudyOption} interface instead.
	 */

	/**
	 * Returns the primary key of this study option.
	 *
	 * @return the primary key of this study option
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this study option.
	 *
	 * @param primaryKey the primary key of this study option
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp study option ID of this study option.
	 *
	 * @return the sp study option ID of this study option
	 */
	public long getSpStudyOptionId();

	/**
	 * Sets the sp study option ID of this study option.
	 *
	 * @param spStudyOptionId the sp study option ID of this study option
	 */
	public void setSpStudyOptionId(long spStudyOptionId);

	/**
	 * Returns the group ID of this study option.
	 *
	 * @return the group ID of this study option
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this study option.
	 *
	 * @param groupId the group ID of this study option
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this study option.
	 *
	 * @return the company ID of this study option
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this study option.
	 *
	 * @param companyId the company ID of this study option
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this study option.
	 *
	 * @return the user ID of this study option
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this study option.
	 *
	 * @param userId the user ID of this study option
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this study option.
	 *
	 * @return the user uuid of this study option
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this study option.
	 *
	 * @param userUuid the user uuid of this study option
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this study option.
	 *
	 * @return the user name of this study option
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this study option.
	 *
	 * @param userName the user name of this study option
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this study option.
	 *
	 * @return the create date of this study option
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this study option.
	 *
	 * @param createDate the create date of this study option
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this study option.
	 *
	 * @return the modified date of this study option
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this study option.
	 *
	 * @param modifiedDate the modified date of this study option
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the sp course ID of this study option.
	 *
	 * @return the sp course ID of this study option
	 */
	public long getSpCourseId();

	/**
	 * Sets the sp course ID of this study option.
	 *
	 * @param spCourseId the sp course ID of this study option
	 */
	public void setSpCourseId(long spCourseId);

	/**
	 * Returns the title of this study option.
	 *
	 * @return the title of this study option
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this study option.
	 *
	 * @param title the title of this study option
	 */
	public void setTitle(String title);

	/**
	 * Returns the desc of this study option.
	 *
	 * @return the desc of this study option
	 */
	@AutoEscape
	public String getDesc();

	/**
	 * Sets the desc of this study option.
	 *
	 * @param desc the desc of this study option
	 */
	public void setDesc(String desc);

	/**
	 * Returns the cover image file entry ID of this study option.
	 *
	 * @return the cover image file entry ID of this study option
	 */
	public long getCoverImageFileEntryId();

	/**
	 * Sets the cover image file entry ID of this study option.
	 *
	 * @param coverImageFileEntryId the cover image file entry ID of this study option
	 */
	public void setCoverImageFileEntryId(long coverImageFileEntryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.model.StudyOption studyOption);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.model.StudyOption> toCacheModel();

	@Override
	public com.sambaash.platform.srv.model.StudyOption toEscapedModel();

	@Override
	public com.sambaash.platform.srv.model.StudyOption toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}