/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StudentCourseFee service. Represents a row in the &quot;SPStudentCourseFee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.model.impl.StudentCourseFeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.model.impl.StudentCourseFeeImpl}.
 * </p>
 *
 * @author gauravvijayvergia
 * @see StudentCourseFee
 * @see com.sambaash.platform.srv.model.impl.StudentCourseFeeImpl
 * @see com.sambaash.platform.srv.model.impl.StudentCourseFeeModelImpl
 * @generated
 */
public interface StudentCourseFeeModel extends BaseModel<StudentCourseFee>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student course fee model instance should use the {@link StudentCourseFee} interface instead.
	 */

	/**
	 * Returns the primary key of this student course fee.
	 *
	 * @return the primary key of this student course fee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student course fee.
	 *
	 * @param primaryKey the primary key of this student course fee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp student course fee ID of this student course fee.
	 *
	 * @return the sp student course fee ID of this student course fee
	 */
	public long getSpStudentCourseFeeId();

	/**
	 * Sets the sp student course fee ID of this student course fee.
	 *
	 * @param spStudentCourseFeeId the sp student course fee ID of this student course fee
	 */
	public void setSpStudentCourseFeeId(long spStudentCourseFeeId);

	/**
	 * Returns the group ID of this student course fee.
	 *
	 * @return the group ID of this student course fee
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this student course fee.
	 *
	 * @param groupId the group ID of this student course fee
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this student course fee.
	 *
	 * @return the company ID of this student course fee
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this student course fee.
	 *
	 * @param companyId the company ID of this student course fee
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this student course fee.
	 *
	 * @return the user ID of this student course fee
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this student course fee.
	 *
	 * @param userId the user ID of this student course fee
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this student course fee.
	 *
	 * @return the user uuid of this student course fee
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this student course fee.
	 *
	 * @param userUuid the user uuid of this student course fee
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this student course fee.
	 *
	 * @return the user name of this student course fee
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this student course fee.
	 *
	 * @param userName the user name of this student course fee
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this student course fee.
	 *
	 * @return the create date of this student course fee
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this student course fee.
	 *
	 * @param createDate the create date of this student course fee
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this student course fee.
	 *
	 * @return the modified date of this student course fee
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this student course fee.
	 *
	 * @param modifiedDate the modified date of this student course fee
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the sp p e process state ID of this student course fee.
	 *
	 * @return the sp p e process state ID of this student course fee
	 */
	public long getSpPEProcessStateId();

	/**
	 * Sets the sp p e process state ID of this student course fee.
	 *
	 * @param spPEProcessStateId the sp p e process state ID of this student course fee
	 */
	public void setSpPEProcessStateId(long spPEProcessStateId);

	/**
	 * Returns the fee type of this student course fee.
	 *
	 * @return the fee type of this student course fee
	 */
	@AutoEscape
	public String getFeeType();

	/**
	 * Sets the fee type of this student course fee.
	 *
	 * @param feeType the fee type of this student course fee
	 */
	public void setFeeType(String feeType);

	/**
	 * Returns the amount of this student course fee.
	 *
	 * @return the amount of this student course fee
	 */
	@AutoEscape
	public String getAmount();

	/**
	 * Sets the amount of this student course fee.
	 *
	 * @param amount the amount of this student course fee
	 */
	public void setAmount(String amount);

	/**
	 * Returns the order of this student course fee.
	 *
	 * @return the order of this student course fee
	 */
	public int getOrder();

	/**
	 * Sets the order of this student course fee.
	 *
	 * @param order the order of this student course fee
	 */
	public void setOrder(int order);

	/**
	 * Returns the formula of this student course fee.
	 *
	 * @return the formula of this student course fee
	 */
	@AutoEscape
	public String getFormula();

	/**
	 * Sets the formula of this student course fee.
	 *
	 * @param formula the formula of this student course fee
	 */
	public void setFormula(String formula);

	/**
	 * Returns the label of this student course fee.
	 *
	 * @return the label of this student course fee
	 */
	@AutoEscape
	public String getLabel();

	/**
	 * Sets the label of this student course fee.
	 *
	 * @param label the label of this student course fee
	 */
	public void setLabel(String label);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.model.StudentCourseFee studentCourseFee);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.model.StudentCourseFee> toCacheModel();

	@Override
	public com.sambaash.platform.srv.model.StudentCourseFee toEscapedModel();

	@Override
	public com.sambaash.platform.srv.model.StudentCourseFee toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}