package com.sambaash.platform.startupprofile;

public interface DBConstants {

	Long REF_TYPE_ORGANIZATION_ID = 1L;
	Long REF_TYPE_PERSON_ID = 2L;

	Long RELATION_FILLED_BY = 201L;
	Long RELATION_FOUNDER = 202L;
	Long RELATION_BOARD_AND_ADVISORY = 203L;
	Long RELATION_COMPETITOR = 104L;
	Long RELATION_INVESTOR_COMPANY = 105L;
	Long RELATION_INVESTOR_PERSON = 206L;
	Long RELATION_TEAM_MEMBER = 207L;
	
	Long RELATION_SUBSIDIARY = 300L;
}