/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.startupprofile.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.startupprofile.model.ATODocument;
import com.sambaash.platform.srv.startupprofile.model.ATODocumentModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ATODocument service. Represents a row in the &quot;SPATODocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.startupprofile.model.ATODocumentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ATODocumentImpl}.
 * </p>
 *
 * @author pradeep
 * @see ATODocumentImpl
 * @see com.sambaash.platform.srv.startupprofile.model.ATODocument
 * @see com.sambaash.platform.srv.startupprofile.model.ATODocumentModel
 * @generated
 */
public class ATODocumentModelImpl extends BaseModelImpl<ATODocument>
	implements ATODocumentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a a t o document model instance should use the {@link com.sambaash.platform.srv.startupprofile.model.ATODocument} interface instead.
	 */
	public static final String TABLE_NAME = "SPATODocument";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "atoDocumentId", Types.BIGINT },
			{ "organizationId", Types.BIGINT },
			{ "documentType", Types.VARCHAR },
			{ "documentFileId", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SPATODocument (uuid_ VARCHAR(75) null,atoDocumentId BIGINT(20) not null primary key,organizationId BIGINT(20),documentType VARCHAR(75) null,documentFileId VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SPATODocument";
	public static final String ORDER_BY_JPQL = " ORDER BY atoDocument.atoDocumentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPATODocument.atoDocumentId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.startupprofile.model.ATODocument"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.startupprofile.model.ATODocument"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.startupprofile.model.ATODocument"),
			true);
	public static long DOCUMENTTYPE_COLUMN_BITMASK = 1L;
	public static long ORGANIZATIONID_COLUMN_BITMASK = 2L;
	public static long UUID_COLUMN_BITMASK = 4L;
	public static long ATODOCUMENTID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.startupprofile.model.ATODocument"));

	public ATODocumentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _atoDocumentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAtoDocumentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _atoDocumentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ATODocument.class;
	}

	@Override
	public String getModelClassName() {
		return ATODocument.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("atoDocumentId", getAtoDocumentId());
		attributes.put("organizationId", getOrganizationId());
		attributes.put("documentType", getDocumentType());
		attributes.put("documentFileId", getDocumentFileId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long atoDocumentId = (Long)attributes.get("atoDocumentId");

		if (atoDocumentId != null) {
			setAtoDocumentId(atoDocumentId);
		}

		Long organizationId = (Long)attributes.get("organizationId");

		if (organizationId != null) {
			setOrganizationId(organizationId);
		}

		String documentType = (String)attributes.get("documentType");

		if (documentType != null) {
			setDocumentType(documentType);
		}

		String documentFileId = (String)attributes.get("documentFileId");

		if (documentFileId != null) {
			setDocumentFileId(documentFileId);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getAtoDocumentId() {
		return _atoDocumentId;
	}

	@Override
	public void setAtoDocumentId(long atoDocumentId) {
		_atoDocumentId = atoDocumentId;
	}

	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		_columnBitmask |= ORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalOrganizationId) {
			_setOriginalOrganizationId = true;

			_originalOrganizationId = _organizationId;
		}

		_organizationId = organizationId;
	}

	public long getOriginalOrganizationId() {
		return _originalOrganizationId;
	}

	@Override
	public String getDocumentType() {
		if (_documentType == null) {
			return StringPool.BLANK;
		}
		else {
			return _documentType;
		}
	}

	@Override
	public void setDocumentType(String documentType) {
		_columnBitmask |= DOCUMENTTYPE_COLUMN_BITMASK;

		if (_originalDocumentType == null) {
			_originalDocumentType = _documentType;
		}

		_documentType = documentType;
	}

	public String getOriginalDocumentType() {
		return GetterUtil.getString(_originalDocumentType);
	}

	@Override
	public String getDocumentFileId() {
		if (_documentFileId == null) {
			return StringPool.BLANK;
		}
		else {
			return _documentFileId;
		}
	}

	@Override
	public void setDocumentFileId(String documentFileId) {
		_documentFileId = documentFileId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ATODocument.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ATODocument toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ATODocument)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ATODocumentImpl atoDocumentImpl = new ATODocumentImpl();

		atoDocumentImpl.setUuid(getUuid());
		atoDocumentImpl.setAtoDocumentId(getAtoDocumentId());
		atoDocumentImpl.setOrganizationId(getOrganizationId());
		atoDocumentImpl.setDocumentType(getDocumentType());
		atoDocumentImpl.setDocumentFileId(getDocumentFileId());

		atoDocumentImpl.resetOriginalValues();

		return atoDocumentImpl;
	}

	@Override
	public int compareTo(ATODocument atoDocument) {
		long primaryKey = atoDocument.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ATODocument)) {
			return false;
		}

		ATODocument atoDocument = (ATODocument)obj;

		long primaryKey = atoDocument.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ATODocumentModelImpl atoDocumentModelImpl = this;

		atoDocumentModelImpl._originalUuid = atoDocumentModelImpl._uuid;

		atoDocumentModelImpl._originalOrganizationId = atoDocumentModelImpl._organizationId;

		atoDocumentModelImpl._setOriginalOrganizationId = false;

		atoDocumentModelImpl._originalDocumentType = atoDocumentModelImpl._documentType;

		atoDocumentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ATODocument> toCacheModel() {
		ATODocumentCacheModel atoDocumentCacheModel = new ATODocumentCacheModel();

		atoDocumentCacheModel.uuid = getUuid();

		String uuid = atoDocumentCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			atoDocumentCacheModel.uuid = null;
		}

		atoDocumentCacheModel.atoDocumentId = getAtoDocumentId();

		atoDocumentCacheModel.organizationId = getOrganizationId();

		atoDocumentCacheModel.documentType = getDocumentType();

		String documentType = atoDocumentCacheModel.documentType;

		if ((documentType != null) && (documentType.length() == 0)) {
			atoDocumentCacheModel.documentType = null;
		}

		atoDocumentCacheModel.documentFileId = getDocumentFileId();

		String documentFileId = atoDocumentCacheModel.documentFileId;

		if ((documentFileId != null) && (documentFileId.length() == 0)) {
			atoDocumentCacheModel.documentFileId = null;
		}

		return atoDocumentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", atoDocumentId=");
		sb.append(getAtoDocumentId());
		sb.append(", organizationId=");
		sb.append(getOrganizationId());
		sb.append(", documentType=");
		sb.append(getDocumentType());
		sb.append(", documentFileId=");
		sb.append(getDocumentFileId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.sambaash.platform.srv.startupprofile.model.ATODocument");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>atoDocumentId</column-name><column-value><![CDATA[");
		sb.append(getAtoDocumentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationId</column-name><column-value><![CDATA[");
		sb.append(getOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentType</column-name><column-value><![CDATA[");
		sb.append(getDocumentType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentFileId</column-name><column-value><![CDATA[");
		sb.append(getDocumentFileId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ATODocument.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ATODocument.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _atoDocumentId;
	private long _organizationId;
	private long _originalOrganizationId;
	private boolean _setOriginalOrganizationId;
	private String _documentType;
	private String _originalDocumentType;
	private String _documentFileId;
	private long _columnBitmask;
	private ATODocument _escapedModel;
}