/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.startupprofile.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.startupprofile.model.Guidelines;
import com.sambaash.platform.srv.startupprofile.model.GuidelinesModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Guidelines service. Represents a row in the &quot;SPGuidelines&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.startupprofile.model.GuidelinesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GuidelinesImpl}.
 * </p>
 *
 * @author pradeep
 * @see GuidelinesImpl
 * @see com.sambaash.platform.srv.startupprofile.model.Guidelines
 * @see com.sambaash.platform.srv.startupprofile.model.GuidelinesModel
 * @generated
 */
public class GuidelinesModelImpl extends BaseModelImpl<Guidelines>
	implements GuidelinesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a guidelines model instance should use the {@link com.sambaash.platform.srv.startupprofile.model.Guidelines} interface instead.
	 */
	public static final String TABLE_NAME = "SPGuidelines";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "guidelineId", Types.BIGINT },
			{ "organizationId", Types.BIGINT },
			{ "principleId", Types.BIGINT },
			{ "guideline1", Types.BOOLEAN },
			{ "guideline2", Types.BOOLEAN },
			{ "guideline3", Types.BOOLEAN },
			{ "guideline4", Types.BOOLEAN },
			{ "guideline5", Types.BOOLEAN },
			{ "guideline6", Types.BOOLEAN },
			{ "guideline7", Types.BOOLEAN },
			{ "guideline8", Types.BOOLEAN },
			{ "moreInfo", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SPGuidelines (uuid_ VARCHAR(75) null,guidelineId BIGINT(20) not null primary key,organizationId BIGINT(20),principleId BIGINT(20),guideline1 BOOLEAN,guideline2 BOOLEAN,guideline3 BOOLEAN,guideline4 BOOLEAN,guideline5 BOOLEAN,guideline6 BOOLEAN,guideline7 BOOLEAN,guideline8 BOOLEAN,moreInfo VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SPGuidelines";
	public static final String ORDER_BY_JPQL = " ORDER BY guidelines.guidelineId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPGuidelines.guidelineId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.startupprofile.model.Guidelines"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.startupprofile.model.Guidelines"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.startupprofile.model.Guidelines"),
			true);
	public static long ORGANIZATIONID_COLUMN_BITMASK = 1L;
	public static long PRINCIPLEID_COLUMN_BITMASK = 2L;
	public static long UUID_COLUMN_BITMASK = 4L;
	public static long GUIDELINEID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.startupprofile.model.Guidelines"));

	public GuidelinesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _guidelineId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGuidelineId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _guidelineId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Guidelines.class;
	}

	@Override
	public String getModelClassName() {
		return Guidelines.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("guidelineId", getGuidelineId());
		attributes.put("organizationId", getOrganizationId());
		attributes.put("principleId", getPrincipleId());
		attributes.put("guideline1", getGuideline1());
		attributes.put("guideline2", getGuideline2());
		attributes.put("guideline3", getGuideline3());
		attributes.put("guideline4", getGuideline4());
		attributes.put("guideline5", getGuideline5());
		attributes.put("guideline6", getGuideline6());
		attributes.put("guideline7", getGuideline7());
		attributes.put("guideline8", getGuideline8());
		attributes.put("moreInfo", getMoreInfo());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long guidelineId = (Long)attributes.get("guidelineId");

		if (guidelineId != null) {
			setGuidelineId(guidelineId);
		}

		Long organizationId = (Long)attributes.get("organizationId");

		if (organizationId != null) {
			setOrganizationId(organizationId);
		}

		Long principleId = (Long)attributes.get("principleId");

		if (principleId != null) {
			setPrincipleId(principleId);
		}

		Boolean guideline1 = (Boolean)attributes.get("guideline1");

		if (guideline1 != null) {
			setGuideline1(guideline1);
		}

		Boolean guideline2 = (Boolean)attributes.get("guideline2");

		if (guideline2 != null) {
			setGuideline2(guideline2);
		}

		Boolean guideline3 = (Boolean)attributes.get("guideline3");

		if (guideline3 != null) {
			setGuideline3(guideline3);
		}

		Boolean guideline4 = (Boolean)attributes.get("guideline4");

		if (guideline4 != null) {
			setGuideline4(guideline4);
		}

		Boolean guideline5 = (Boolean)attributes.get("guideline5");

		if (guideline5 != null) {
			setGuideline5(guideline5);
		}

		Boolean guideline6 = (Boolean)attributes.get("guideline6");

		if (guideline6 != null) {
			setGuideline6(guideline6);
		}

		Boolean guideline7 = (Boolean)attributes.get("guideline7");

		if (guideline7 != null) {
			setGuideline7(guideline7);
		}

		Boolean guideline8 = (Boolean)attributes.get("guideline8");

		if (guideline8 != null) {
			setGuideline8(guideline8);
		}

		String moreInfo = (String)attributes.get("moreInfo");

		if (moreInfo != null) {
			setMoreInfo(moreInfo);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getGuidelineId() {
		return _guidelineId;
	}

	@Override
	public void setGuidelineId(long guidelineId) {
		_guidelineId = guidelineId;
	}

	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		_columnBitmask |= ORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalOrganizationId) {
			_setOriginalOrganizationId = true;

			_originalOrganizationId = _organizationId;
		}

		_organizationId = organizationId;
	}

	public long getOriginalOrganizationId() {
		return _originalOrganizationId;
	}

	@Override
	public long getPrincipleId() {
		return _principleId;
	}

	@Override
	public void setPrincipleId(long principleId) {
		_columnBitmask |= PRINCIPLEID_COLUMN_BITMASK;

		if (!_setOriginalPrincipleId) {
			_setOriginalPrincipleId = true;

			_originalPrincipleId = _principleId;
		}

		_principleId = principleId;
	}

	public long getOriginalPrincipleId() {
		return _originalPrincipleId;
	}

	@Override
	public boolean getGuideline1() {
		return _guideline1;
	}

	@Override
	public boolean isGuideline1() {
		return _guideline1;
	}

	@Override
	public void setGuideline1(boolean guideline1) {
		_guideline1 = guideline1;
	}

	@Override
	public boolean getGuideline2() {
		return _guideline2;
	}

	@Override
	public boolean isGuideline2() {
		return _guideline2;
	}

	@Override
	public void setGuideline2(boolean guideline2) {
		_guideline2 = guideline2;
	}

	@Override
	public boolean getGuideline3() {
		return _guideline3;
	}

	@Override
	public boolean isGuideline3() {
		return _guideline3;
	}

	@Override
	public void setGuideline3(boolean guideline3) {
		_guideline3 = guideline3;
	}

	@Override
	public boolean getGuideline4() {
		return _guideline4;
	}

	@Override
	public boolean isGuideline4() {
		return _guideline4;
	}

	@Override
	public void setGuideline4(boolean guideline4) {
		_guideline4 = guideline4;
	}

	@Override
	public boolean getGuideline5() {
		return _guideline5;
	}

	@Override
	public boolean isGuideline5() {
		return _guideline5;
	}

	@Override
	public void setGuideline5(boolean guideline5) {
		_guideline5 = guideline5;
	}

	@Override
	public boolean getGuideline6() {
		return _guideline6;
	}

	@Override
	public boolean isGuideline6() {
		return _guideline6;
	}

	@Override
	public void setGuideline6(boolean guideline6) {
		_guideline6 = guideline6;
	}

	@Override
	public boolean getGuideline7() {
		return _guideline7;
	}

	@Override
	public boolean isGuideline7() {
		return _guideline7;
	}

	@Override
	public void setGuideline7(boolean guideline7) {
		_guideline7 = guideline7;
	}

	@Override
	public boolean getGuideline8() {
		return _guideline8;
	}

	@Override
	public boolean isGuideline8() {
		return _guideline8;
	}

	@Override
	public void setGuideline8(boolean guideline8) {
		_guideline8 = guideline8;
	}

	@Override
	public String getMoreInfo() {
		if (_moreInfo == null) {
			return StringPool.BLANK;
		}
		else {
			return _moreInfo;
		}
	}

	@Override
	public void setMoreInfo(String moreInfo) {
		_moreInfo = moreInfo;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Guidelines.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Guidelines toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Guidelines)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GuidelinesImpl guidelinesImpl = new GuidelinesImpl();

		guidelinesImpl.setUuid(getUuid());
		guidelinesImpl.setGuidelineId(getGuidelineId());
		guidelinesImpl.setOrganizationId(getOrganizationId());
		guidelinesImpl.setPrincipleId(getPrincipleId());
		guidelinesImpl.setGuideline1(getGuideline1());
		guidelinesImpl.setGuideline2(getGuideline2());
		guidelinesImpl.setGuideline3(getGuideline3());
		guidelinesImpl.setGuideline4(getGuideline4());
		guidelinesImpl.setGuideline5(getGuideline5());
		guidelinesImpl.setGuideline6(getGuideline6());
		guidelinesImpl.setGuideline7(getGuideline7());
		guidelinesImpl.setGuideline8(getGuideline8());
		guidelinesImpl.setMoreInfo(getMoreInfo());

		guidelinesImpl.resetOriginalValues();

		return guidelinesImpl;
	}

	@Override
	public int compareTo(Guidelines guidelines) {
		long primaryKey = guidelines.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Guidelines)) {
			return false;
		}

		Guidelines guidelines = (Guidelines)obj;

		long primaryKey = guidelines.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		GuidelinesModelImpl guidelinesModelImpl = this;

		guidelinesModelImpl._originalUuid = guidelinesModelImpl._uuid;

		guidelinesModelImpl._originalOrganizationId = guidelinesModelImpl._organizationId;

		guidelinesModelImpl._setOriginalOrganizationId = false;

		guidelinesModelImpl._originalPrincipleId = guidelinesModelImpl._principleId;

		guidelinesModelImpl._setOriginalPrincipleId = false;

		guidelinesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Guidelines> toCacheModel() {
		GuidelinesCacheModel guidelinesCacheModel = new GuidelinesCacheModel();

		guidelinesCacheModel.uuid = getUuid();

		String uuid = guidelinesCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			guidelinesCacheModel.uuid = null;
		}

		guidelinesCacheModel.guidelineId = getGuidelineId();

		guidelinesCacheModel.organizationId = getOrganizationId();

		guidelinesCacheModel.principleId = getPrincipleId();

		guidelinesCacheModel.guideline1 = getGuideline1();

		guidelinesCacheModel.guideline2 = getGuideline2();

		guidelinesCacheModel.guideline3 = getGuideline3();

		guidelinesCacheModel.guideline4 = getGuideline4();

		guidelinesCacheModel.guideline5 = getGuideline5();

		guidelinesCacheModel.guideline6 = getGuideline6();

		guidelinesCacheModel.guideline7 = getGuideline7();

		guidelinesCacheModel.guideline8 = getGuideline8();

		guidelinesCacheModel.moreInfo = getMoreInfo();

		String moreInfo = guidelinesCacheModel.moreInfo;

		if ((moreInfo != null) && (moreInfo.length() == 0)) {
			guidelinesCacheModel.moreInfo = null;
		}

		return guidelinesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", guidelineId=");
		sb.append(getGuidelineId());
		sb.append(", organizationId=");
		sb.append(getOrganizationId());
		sb.append(", principleId=");
		sb.append(getPrincipleId());
		sb.append(", guideline1=");
		sb.append(getGuideline1());
		sb.append(", guideline2=");
		sb.append(getGuideline2());
		sb.append(", guideline3=");
		sb.append(getGuideline3());
		sb.append(", guideline4=");
		sb.append(getGuideline4());
		sb.append(", guideline5=");
		sb.append(getGuideline5());
		sb.append(", guideline6=");
		sb.append(getGuideline6());
		sb.append(", guideline7=");
		sb.append(getGuideline7());
		sb.append(", guideline8=");
		sb.append(getGuideline8());
		sb.append(", moreInfo=");
		sb.append(getMoreInfo());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.sambaash.platform.srv.startupprofile.model.Guidelines");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>guidelineId</column-name><column-value><![CDATA[");
		sb.append(getGuidelineId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationId</column-name><column-value><![CDATA[");
		sb.append(getOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>principleId</column-name><column-value><![CDATA[");
		sb.append(getPrincipleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>guideline1</column-name><column-value><![CDATA[");
		sb.append(getGuideline1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>guideline2</column-name><column-value><![CDATA[");
		sb.append(getGuideline2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>guideline3</column-name><column-value><![CDATA[");
		sb.append(getGuideline3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>guideline4</column-name><column-value><![CDATA[");
		sb.append(getGuideline4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>guideline5</column-name><column-value><![CDATA[");
		sb.append(getGuideline5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>guideline6</column-name><column-value><![CDATA[");
		sb.append(getGuideline6());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>guideline7</column-name><column-value><![CDATA[");
		sb.append(getGuideline7());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>guideline8</column-name><column-value><![CDATA[");
		sb.append(getGuideline8());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moreInfo</column-name><column-value><![CDATA[");
		sb.append(getMoreInfo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Guidelines.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Guidelines.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _guidelineId;
	private long _organizationId;
	private long _originalOrganizationId;
	private boolean _setOriginalOrganizationId;
	private long _principleId;
	private long _originalPrincipleId;
	private boolean _setOriginalPrincipleId;
	private boolean _guideline1;
	private boolean _guideline2;
	private boolean _guideline3;
	private boolean _guideline4;
	private boolean _guideline5;
	private boolean _guideline6;
	private boolean _guideline7;
	private boolean _guideline8;
	private String _moreInfo;
	private long _columnBitmask;
	private Guidelines _escapedModel;
}