/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.filter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SPSearchFilter service. Represents a row in the &quot;SPSearchFilter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.filter.model.impl.SPSearchFilterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.filter.model.impl.SPSearchFilterImpl}.
 * </p>
 *
 * @author harini
 * @see SPSearchFilter
 * @see com.sambaash.platform.srv.filter.model.impl.SPSearchFilterImpl
 * @see com.sambaash.platform.srv.filter.model.impl.SPSearchFilterModelImpl
 * @generated
 */
public interface SPSearchFilterModel extends BaseModel<SPSearchFilter>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s p search filter model instance should use the {@link SPSearchFilter} interface instead.
	 */

	/**
	 * Returns the primary key of this s p search filter.
	 *
	 * @return the primary key of this s p search filter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s p search filter.
	 *
	 * @param primaryKey the primary key of this s p search filter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this s p search filter.
	 *
	 * @return the uuid of this s p search filter
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this s p search filter.
	 *
	 * @param uuid the uuid of this s p search filter
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sp search filter ID of this s p search filter.
	 *
	 * @return the sp search filter ID of this s p search filter
	 */
	public long getSpSearchFilterId();

	/**
	 * Sets the sp search filter ID of this s p search filter.
	 *
	 * @param spSearchFilterId the sp search filter ID of this s p search filter
	 */
	public void setSpSearchFilterId(long spSearchFilterId);

	/**
	 * Returns the group ID of this s p search filter.
	 *
	 * @return the group ID of this s p search filter
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this s p search filter.
	 *
	 * @param groupId the group ID of this s p search filter
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this s p search filter.
	 *
	 * @return the company ID of this s p search filter
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this s p search filter.
	 *
	 * @param companyId the company ID of this s p search filter
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this s p search filter.
	 *
	 * @return the user ID of this s p search filter
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this s p search filter.
	 *
	 * @param userId the user ID of this s p search filter
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s p search filter.
	 *
	 * @return the user uuid of this s p search filter
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s p search filter.
	 *
	 * @param userUuid the user uuid of this s p search filter
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this s p search filter.
	 *
	 * @return the user name of this s p search filter
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this s p search filter.
	 *
	 * @param userName the user name of this s p search filter
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this s p search filter.
	 *
	 * @return the create date of this s p search filter
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this s p search filter.
	 *
	 * @param createDate the create date of this s p search filter
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this s p search filter.
	 *
	 * @return the modified date of this s p search filter
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this s p search filter.
	 *
	 * @param modifiedDate the modified date of this s p search filter
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the filter name of this s p search filter.
	 *
	 * @return the filter name of this s p search filter
	 */
	@AutoEscape
	public String getFilterName();

	/**
	 * Sets the filter name of this s p search filter.
	 *
	 * @param filterName the filter name of this s p search filter
	 */
	public void setFilterName(String filterName);

	/**
	 * Returns the filter parameter of this s p search filter.
	 *
	 * @return the filter parameter of this s p search filter
	 */
	@AutoEscape
	public String getFilterParameter();

	/**
	 * Sets the filter parameter of this s p search filter.
	 *
	 * @param filterParameter the filter parameter of this s p search filter
	 */
	public void setFilterParameter(String filterParameter);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.filter.model.SPSearchFilter spSearchFilter);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.filter.model.SPSearchFilter> toCacheModel();

	@Override
	public com.sambaash.platform.srv.filter.model.SPSearchFilter toEscapedModel();

	@Override
	public com.sambaash.platform.srv.filter.model.SPSearchFilter toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}