/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.processbuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PEDummyEntity service. Represents a row in the &quot;SPPEDummyEntity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.processbuilder.model.impl.PEDummyEntityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.processbuilder.model.impl.PEDummyEntityImpl}.
 * </p>
 *
 * @author nareshchebolu
 * @see PEDummyEntity
 * @see com.sambaash.platform.srv.processbuilder.model.impl.PEDummyEntityImpl
 * @see com.sambaash.platform.srv.processbuilder.model.impl.PEDummyEntityModelImpl
 * @generated
 */
public interface PEDummyEntityModel extends BaseModel<PEDummyEntity>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a p e dummy entity model instance should use the {@link PEDummyEntity} interface instead.
	 */

	/**
	 * Returns the primary key of this p e dummy entity.
	 *
	 * @return the primary key of this p e dummy entity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this p e dummy entity.
	 *
	 * @param primaryKey the primary key of this p e dummy entity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this p e dummy entity.
	 *
	 * @return the uuid of this p e dummy entity
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this p e dummy entity.
	 *
	 * @param uuid the uuid of this p e dummy entity
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sp p e dummy entity ID of this p e dummy entity.
	 *
	 * @return the sp p e dummy entity ID of this p e dummy entity
	 */
	public long getSpPEDummyEntityId();

	/**
	 * Sets the sp p e dummy entity ID of this p e dummy entity.
	 *
	 * @param spPEDummyEntityId the sp p e dummy entity ID of this p e dummy entity
	 */
	public void setSpPEDummyEntityId(long spPEDummyEntityId);

	/**
	 * Returns the group ID of this p e dummy entity.
	 *
	 * @return the group ID of this p e dummy entity
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this p e dummy entity.
	 *
	 * @param groupId the group ID of this p e dummy entity
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this p e dummy entity.
	 *
	 * @return the company ID of this p e dummy entity
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this p e dummy entity.
	 *
	 * @param companyId the company ID of this p e dummy entity
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this p e dummy entity.
	 *
	 * @return the user ID of this p e dummy entity
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this p e dummy entity.
	 *
	 * @param userId the user ID of this p e dummy entity
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this p e dummy entity.
	 *
	 * @return the user uuid of this p e dummy entity
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this p e dummy entity.
	 *
	 * @param userUuid the user uuid of this p e dummy entity
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this p e dummy entity.
	 *
	 * @return the user name of this p e dummy entity
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this p e dummy entity.
	 *
	 * @param userName the user name of this p e dummy entity
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this p e dummy entity.
	 *
	 * @return the create date of this p e dummy entity
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this p e dummy entity.
	 *
	 * @param createDate the create date of this p e dummy entity
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this p e dummy entity.
	 *
	 * @return the modified date of this p e dummy entity
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this p e dummy entity.
	 *
	 * @param modifiedDate the modified date of this p e dummy entity
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this p e dummy entity.
	 *
	 * @return the name of this p e dummy entity
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this p e dummy entity.
	 *
	 * @param name the name of this p e dummy entity
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.processbuilder.model.PEDummyEntity peDummyEntity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.processbuilder.model.PEDummyEntity> toCacheModel();

	@Override
	public com.sambaash.platform.srv.processbuilder.model.PEDummyEntity toEscapedModel();

	@Override
	public com.sambaash.platform.srv.processbuilder.model.PEDummyEntity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}