/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.processbuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PESupervisor service. Represents a row in the &quot;SPPESupervisor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.processbuilder.model.impl.PESupervisorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.processbuilder.model.impl.PESupervisorImpl}.
 * </p>
 *
 * @author nareshchebolu
 * @see PESupervisor
 * @see com.sambaash.platform.srv.processbuilder.model.impl.PESupervisorImpl
 * @see com.sambaash.platform.srv.processbuilder.model.impl.PESupervisorModelImpl
 * @generated
 */
public interface PESupervisorModel extends BaseModel<PESupervisor>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a p e supervisor model instance should use the {@link PESupervisor} interface instead.
	 */

	/**
	 * Returns the primary key of this p e supervisor.
	 *
	 * @return the primary key of this p e supervisor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this p e supervisor.
	 *
	 * @param primaryKey the primary key of this p e supervisor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp p e supervisor ID of this p e supervisor.
	 *
	 * @return the sp p e supervisor ID of this p e supervisor
	 */
	public long getSpPESupervisorId();

	/**
	 * Sets the sp p e supervisor ID of this p e supervisor.
	 *
	 * @param spPESupervisorId the sp p e supervisor ID of this p e supervisor
	 */
	public void setSpPESupervisorId(long spPESupervisorId);

	/**
	 * Returns the group ID of this p e supervisor.
	 *
	 * @return the group ID of this p e supervisor
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this p e supervisor.
	 *
	 * @param groupId the group ID of this p e supervisor
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this p e supervisor.
	 *
	 * @return the company ID of this p e supervisor
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this p e supervisor.
	 *
	 * @param companyId the company ID of this p e supervisor
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this p e supervisor.
	 *
	 * @return the user ID of this p e supervisor
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this p e supervisor.
	 *
	 * @param userId the user ID of this p e supervisor
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this p e supervisor.
	 *
	 * @return the user uuid of this p e supervisor
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this p e supervisor.
	 *
	 * @param userUuid the user uuid of this p e supervisor
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this p e supervisor.
	 *
	 * @return the user name of this p e supervisor
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this p e supervisor.
	 *
	 * @param userName the user name of this p e supervisor
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this p e supervisor.
	 *
	 * @return the create date of this p e supervisor
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this p e supervisor.
	 *
	 * @param createDate the create date of this p e supervisor
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this p e supervisor.
	 *
	 * @return the modified date of this p e supervisor
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this p e supervisor.
	 *
	 * @param modifiedDate the modified date of this p e supervisor
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the filter1 of this p e supervisor.
	 *
	 * @return the filter1 of this p e supervisor
	 */
	@AutoEscape
	public String getFilter1();

	/**
	 * Sets the filter1 of this p e supervisor.
	 *
	 * @param filter1 the filter1 of this p e supervisor
	 */
	public void setFilter1(String filter1);

	/**
	 * Returns the filter2 of this p e supervisor.
	 *
	 * @return the filter2 of this p e supervisor
	 */
	@AutoEscape
	public String getFilter2();

	/**
	 * Sets the filter2 of this p e supervisor.
	 *
	 * @param filter2 the filter2 of this p e supervisor
	 */
	public void setFilter2(String filter2);

	/**
	 * Returns the filter3 of this p e supervisor.
	 *
	 * @return the filter3 of this p e supervisor
	 */
	@AutoEscape
	public String getFilter3();

	/**
	 * Sets the filter3 of this p e supervisor.
	 *
	 * @param filter3 the filter3 of this p e supervisor
	 */
	public void setFilter3(String filter3);

	/**
	 * Returns the filter4 of this p e supervisor.
	 *
	 * @return the filter4 of this p e supervisor
	 */
	@AutoEscape
	public String getFilter4();

	/**
	 * Sets the filter4 of this p e supervisor.
	 *
	 * @param filter4 the filter4 of this p e supervisor
	 */
	public void setFilter4(String filter4);

	/**
	 * Returns the filter5 of this p e supervisor.
	 *
	 * @return the filter5 of this p e supervisor
	 */
	@AutoEscape
	public String getFilter5();

	/**
	 * Sets the filter5 of this p e supervisor.
	 *
	 * @param filter5 the filter5 of this p e supervisor
	 */
	public void setFilter5(String filter5);

	/**
	 * Returns the supervisor ID of this p e supervisor.
	 *
	 * @return the supervisor ID of this p e supervisor
	 */
	public long getSupervisorId();

	/**
	 * Sets the supervisor ID of this p e supervisor.
	 *
	 * @param supervisorId the supervisor ID of this p e supervisor
	 */
	public void setSupervisorId(long supervisorId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.processbuilder.model.PESupervisor peSupervisor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.processbuilder.model.PESupervisor> toCacheModel();

	@Override
	public com.sambaash.platform.srv.processbuilder.model.PESupervisor toEscapedModel();

	@Override
	public com.sambaash.platform.srv.processbuilder.model.PESupervisor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}