create table Calendar (
	uuid_ VARCHAR(75) null,
	calendarId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	resourceBlockId BIGINT(20),
	calendarResourceId BIGINT(20),
	name STRING null,
	description STRING null,
	color INTEGER,
	defaultCalendar BOOLEAN,
	enableComments BOOLEAN,
	enableRatings BOOLEAN
);

create table CalendarBooking (
	uuid_ VARCHAR(75) null,
	calendarBookingId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	resourceBlockId BIGINT(20),
	calendarId BIGINT(20),
	calendarResourceId BIGINT(20),
	parentCalendarBookingId BIGINT(20),
	title STRING null,
	description LONGTEXT null,
	location STRING null,
	startTime BIGINT(20),
	endTime BIGINT(20),
	allDay BOOLEAN,
	recurrence STRING null,
	firstReminder BIGINT(20),
	firstReminderType VARCHAR(75) null,
	secondReminder BIGINT(20),
	secondReminderType VARCHAR(75) null,
	status INTEGER,
	statusByUserId BIGINT(20),
	statusByUserName VARCHAR(75) null,
	statusDate DATETIME null
);

create table CalendarNotificationTemplate (
	uuid_ VARCHAR(75) null,
	calendarNotificationTemplateId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	calendarId BIGINT(20),
	notificationType VARCHAR(75) null,
	notificationTypeSettings VARCHAR(75) null,
	notificationTemplateType VARCHAR(75) null,
	subject VARCHAR(75) null,
	body LONGTEXT null
);

create table CalendarResource (
	uuid_ VARCHAR(75) null,
	calendarResourceId BIGINT(20) not null primary key,
	groupId BIGINT(20),
	companyId BIGINT(20),
	userId BIGINT(20),
	userName VARCHAR(75) null,
	createDate DATETIME null,
	modifiedDate DATETIME null,
	resourceBlockId BIGINT(20),
	classNameId BIGINT(20),
	classPK BIGINT(20),
	classUuid VARCHAR(75) null,
	code_ VARCHAR(75) null,
	name STRING null,
	description STRING null,
	active_ BOOLEAN
);