/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.extendedprofile.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.sambaash.platform.srv.extendedprofile.model.SPCertification;
import com.sambaash.platform.srv.extendedprofile.model.SPCertificationModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SPCertification service. Represents a row in the &quot;SPCertification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.sambaash.platform.srv.extendedprofile.model.SPCertificationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SPCertificationImpl}.
 * </p>
 *
 * @author harini
 * @see SPCertificationImpl
 * @see com.sambaash.platform.srv.extendedprofile.model.SPCertification
 * @see com.sambaash.platform.srv.extendedprofile.model.SPCertificationModel
 * @generated
 */
public class SPCertificationModelImpl extends BaseModelImpl<SPCertification>
	implements SPCertificationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a s p certification model instance should use the {@link com.sambaash.platform.srv.extendedprofile.model.SPCertification} interface instead.
	 */
	public static final String TABLE_NAME = "SPCertification";
	public static final Object[][] TABLE_COLUMNS = {
			{ "classPk", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "certificationId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table SPCertification (classPk BIGINT(20) not null primary key,groupId BIGINT(20),companyId BIGINT(20),userId BIGINT(20),userName VARCHAR(75) null,createDate DATETIME null,modifiedDate DATETIME null,certificationId BIGINT(20))";
	public static final String TABLE_SQL_DROP = "drop table SPCertification";
	public static final String ORDER_BY_JPQL = " ORDER BY spCertification.modifiedDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SPCertification.modifiedDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.sambaash.platform.srv.extendedprofile.model.SPCertification"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.sambaash.platform.srv.extendedprofile.model.SPCertification"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.sambaash.platform.srv.extendedprofile.model.SPCertification"),
			true);
	public static long CERTIFICATIONID_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;
	public static long MODIFIEDDATE_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.sambaash.platform.srv.extendedprofile.model.SPCertification"));

	public SPCertificationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _classPk;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setClassPk(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _classPk;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SPCertification.class;
	}

	@Override
	public String getModelClassName() {
		return SPCertification.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("classPk", getClassPk());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("certificationId", getCertificationId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long classPk = (Long)attributes.get("classPk");

		if (classPk != null) {
			setClassPk(classPk);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long certificationId = (Long)attributes.get("certificationId");

		if (certificationId != null) {
			setCertificationId(certificationId);
		}
	}

	@Override
	public long getClassPk() {
		return _classPk;
	}

	@Override
	public void setClassPk(long classPk) {
		_classPk = classPk;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCertificationId() {
		return _certificationId;
	}

	@Override
	public void setCertificationId(long certificationId) {
		_columnBitmask |= CERTIFICATIONID_COLUMN_BITMASK;

		if (!_setOriginalCertificationId) {
			_setOriginalCertificationId = true;

			_originalCertificationId = _certificationId;
		}

		_certificationId = certificationId;
	}

	public long getOriginalCertificationId() {
		return _originalCertificationId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			SPCertification.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SPCertification toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SPCertification)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SPCertificationImpl spCertificationImpl = new SPCertificationImpl();

		spCertificationImpl.setClassPk(getClassPk());
		spCertificationImpl.setGroupId(getGroupId());
		spCertificationImpl.setCompanyId(getCompanyId());
		spCertificationImpl.setUserId(getUserId());
		spCertificationImpl.setUserName(getUserName());
		spCertificationImpl.setCreateDate(getCreateDate());
		spCertificationImpl.setModifiedDate(getModifiedDate());
		spCertificationImpl.setCertificationId(getCertificationId());

		spCertificationImpl.resetOriginalValues();

		return spCertificationImpl;
	}

	@Override
	public int compareTo(SPCertification spCertification) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedDate(),
				spCertification.getModifiedDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SPCertification)) {
			return false;
		}

		SPCertification spCertification = (SPCertification)obj;

		long primaryKey = spCertification.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SPCertificationModelImpl spCertificationModelImpl = this;

		spCertificationModelImpl._originalUserId = spCertificationModelImpl._userId;

		spCertificationModelImpl._setOriginalUserId = false;

		spCertificationModelImpl._originalCertificationId = spCertificationModelImpl._certificationId;

		spCertificationModelImpl._setOriginalCertificationId = false;

		spCertificationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SPCertification> toCacheModel() {
		SPCertificationCacheModel spCertificationCacheModel = new SPCertificationCacheModel();

		spCertificationCacheModel.classPk = getClassPk();

		spCertificationCacheModel.groupId = getGroupId();

		spCertificationCacheModel.companyId = getCompanyId();

		spCertificationCacheModel.userId = getUserId();

		spCertificationCacheModel.userName = getUserName();

		String userName = spCertificationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			spCertificationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			spCertificationCacheModel.createDate = createDate.getTime();
		}
		else {
			spCertificationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			spCertificationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			spCertificationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		spCertificationCacheModel.certificationId = getCertificationId();

		return spCertificationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{classPk=");
		sb.append(getClassPk());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", certificationId=");
		sb.append(getCertificationId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append(
			"com.sambaash.platform.srv.extendedprofile.model.SPCertification");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>classPk</column-name><column-value><![CDATA[");
		sb.append(getClassPk());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificationId</column-name><column-value><![CDATA[");
		sb.append(getCertificationId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SPCertification.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SPCertification.class
		};
	private long _classPk;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _certificationId;
	private long _originalCertificationId;
	private boolean _setOriginalCertificationId;
	private long _columnBitmask;
	private SPCertification _escapedModel;
}