/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.startupprofile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Accreditation service. Represents a row in the &quot;SPAccreditation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.startupprofile.model.impl.AccreditationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.startupprofile.model.impl.AccreditationImpl}.
 * </p>
 *
 * @author pradeep
 * @see Accreditation
 * @see com.sambaash.platform.srv.startupprofile.model.impl.AccreditationImpl
 * @see com.sambaash.platform.srv.startupprofile.model.impl.AccreditationModelImpl
 * @generated
 */
public interface AccreditationModel extends BaseModel<Accreditation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a accreditation model instance should use the {@link Accreditation} interface instead.
	 */

	/**
	 * Returns the primary key of this accreditation.
	 *
	 * @return the primary key of this accreditation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this accreditation.
	 *
	 * @param primaryKey the primary key of this accreditation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this accreditation.
	 *
	 * @return the uuid of this accreditation
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this accreditation.
	 *
	 * @param uuid the uuid of this accreditation
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the accreditation ID of this accreditation.
	 *
	 * @return the accreditation ID of this accreditation
	 */
	public long getAccreditationId();

	/**
	 * Sets the accreditation ID of this accreditation.
	 *
	 * @param accreditationId the accreditation ID of this accreditation
	 */
	public void setAccreditationId(long accreditationId);

	/**
	 * Returns the organization ID of this accreditation.
	 *
	 * @return the organization ID of this accreditation
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this accreditation.
	 *
	 * @param organizationId the organization ID of this accreditation
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the aselected of this accreditation.
	 *
	 * @return the aselected of this accreditation
	 */
	public boolean getAselected();

	/**
	 * Returns <code>true</code> if this accreditation is aselected.
	 *
	 * @return <code>true</code> if this accreditation is aselected; <code>false</code> otherwise
	 */
	public boolean isAselected();

	/**
	 * Sets whether this accreditation is aselected.
	 *
	 * @param aselected the aselected of this accreditation
	 */
	public void setAselected(boolean aselected);

	/**
	 * Returns the avalue of this accreditation.
	 *
	 * @return the avalue of this accreditation
	 */
	@AutoEscape
	public String getAvalue();

	/**
	 * Sets the avalue of this accreditation.
	 *
	 * @param avalue the avalue of this accreditation
	 */
	public void setAvalue(String avalue);

	/**
	 * Returns the bselected of this accreditation.
	 *
	 * @return the bselected of this accreditation
	 */
	public boolean getBselected();

	/**
	 * Returns <code>true</code> if this accreditation is bselected.
	 *
	 * @return <code>true</code> if this accreditation is bselected; <code>false</code> otherwise
	 */
	public boolean isBselected();

	/**
	 * Sets whether this accreditation is bselected.
	 *
	 * @param bselected the bselected of this accreditation
	 */
	public void setBselected(boolean bselected);

	/**
	 * Returns the bvalue of this accreditation.
	 *
	 * @return the bvalue of this accreditation
	 */
	@AutoEscape
	public String getBvalue();

	/**
	 * Sets the bvalue of this accreditation.
	 *
	 * @param bvalue the bvalue of this accreditation
	 */
	public void setBvalue(String bvalue);

	/**
	 * Returns the cselected of this accreditation.
	 *
	 * @return the cselected of this accreditation
	 */
	public boolean getCselected();

	/**
	 * Returns <code>true</code> if this accreditation is cselected.
	 *
	 * @return <code>true</code> if this accreditation is cselected; <code>false</code> otherwise
	 */
	public boolean isCselected();

	/**
	 * Sets whether this accreditation is cselected.
	 *
	 * @param cselected the cselected of this accreditation
	 */
	public void setCselected(boolean cselected);

	/**
	 * Returns the cvalue of this accreditation.
	 *
	 * @return the cvalue of this accreditation
	 */
	@AutoEscape
	public String getCvalue();

	/**
	 * Sets the cvalue of this accreditation.
	 *
	 * @param cvalue the cvalue of this accreditation
	 */
	public void setCvalue(String cvalue);

	/**
	 * Returns the ccompany name of this accreditation.
	 *
	 * @return the ccompany name of this accreditation
	 */
	@AutoEscape
	public String getCcompanyName();

	/**
	 * Sets the ccompany name of this accreditation.
	 *
	 * @param ccompanyName the ccompany name of this accreditation
	 */
	public void setCcompanyName(String ccompanyName);

	/**
	 * Returns the csamepolicy of this accreditation.
	 *
	 * @return the csamepolicy of this accreditation
	 */
	public boolean getCsamepolicy();

	/**
	 * Returns <code>true</code> if this accreditation is csamepolicy.
	 *
	 * @return <code>true</code> if this accreditation is csamepolicy; <code>false</code> otherwise
	 */
	public boolean isCsamepolicy();

	/**
	 * Sets whether this accreditation is csamepolicy.
	 *
	 * @param csamepolicy the csamepolicy of this accreditation
	 */
	public void setCsamepolicy(boolean csamepolicy);

	/**
	 * Returns the celaborate of this accreditation.
	 *
	 * @return the celaborate of this accreditation
	 */
	@AutoEscape
	public String getCelaborate();

	/**
	 * Sets the celaborate of this accreditation.
	 *
	 * @param celaborate the celaborate of this accreditation
	 */
	public void setCelaborate(String celaborate);

	/**
	 * Returns the dselected of this accreditation.
	 *
	 * @return the dselected of this accreditation
	 */
	public boolean getDselected();

	/**
	 * Returns <code>true</code> if this accreditation is dselected.
	 *
	 * @return <code>true</code> if this accreditation is dselected; <code>false</code> otherwise
	 */
	public boolean isDselected();

	/**
	 * Sets whether this accreditation is dselected.
	 *
	 * @param dselected the dselected of this accreditation
	 */
	public void setDselected(boolean dselected);

	/**
	 * Returns the dvalue of this accreditation.
	 *
	 * @return the dvalue of this accreditation
	 */
	@AutoEscape
	public String getDvalue();

	/**
	 * Sets the dvalue of this accreditation.
	 *
	 * @param dvalue the dvalue of this accreditation
	 */
	public void setDvalue(String dvalue);

	/**
	 * Returns the accreditation status of this accreditation.
	 *
	 * @return the accreditation status of this accreditation
	 */
	@AutoEscape
	public String getAccreditationStatus();

	/**
	 * Sets the accreditation status of this accreditation.
	 *
	 * @param accreditationStatus the accreditation status of this accreditation
	 */
	public void setAccreditationStatus(String accreditationStatus);

	/**
	 * Returns the date of accreditation of this accreditation.
	 *
	 * @return the date of accreditation of this accreditation
	 */
	public Date getDateOfAccreditation();

	/**
	 * Sets the date of accreditation of this accreditation.
	 *
	 * @param dateOfAccreditation the date of accreditation of this accreditation
	 */
	public void setDateOfAccreditation(Date dateOfAccreditation);

	/**
	 * Returns the date of expiry of this accreditation.
	 *
	 * @return the date of expiry of this accreditation
	 */
	public Date getDateOfExpiry();

	/**
	 * Sets the date of expiry of this accreditation.
	 *
	 * @param dateOfExpiry the date of expiry of this accreditation
	 */
	public void setDateOfExpiry(Date dateOfExpiry);

	/**
	 * Returns the latest payment date of this accreditation.
	 *
	 * @return the latest payment date of this accreditation
	 */
	public Date getLatestPaymentDate();

	/**
	 * Sets the latest payment date of this accreditation.
	 *
	 * @param latestPaymentDate the latest payment date of this accreditation
	 */
	public void setLatestPaymentDate(Date latestPaymentDate);

	/**
	 * Returns the start date of reaccreditation of this accreditation.
	 *
	 * @return the start date of reaccreditation of this accreditation
	 */
	public Date getStartDateOfReaccreditation();

	/**
	 * Sets the start date of reaccreditation of this accreditation.
	 *
	 * @param startDateOfReaccreditation the start date of reaccreditation of this accreditation
	 */
	public void setStartDateOfReaccreditation(Date startDateOfReaccreditation);

	/**
	 * Returns the date of reaccdt review of this accreditation.
	 *
	 * @return the date of reaccdt review of this accreditation
	 */
	public Date getDateOfReaccdtReview();

	/**
	 * Sets the date of reaccdt review of this accreditation.
	 *
	 * @param dateOfReaccdtReview the date of reaccdt review of this accreditation
	 */
	public void setDateOfReaccdtReview(Date dateOfReaccdtReview);

	/**
	 * Returns the accreditation by of this accreditation.
	 *
	 * @return the accreditation by of this accreditation
	 */
	@AutoEscape
	public String getAccreditationBy();

	/**
	 * Sets the accreditation by of this accreditation.
	 *
	 * @param AccreditationBy the accreditation by of this accreditation
	 */
	public void setAccreditationBy(String AccreditationBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.startupprofile.model.Accreditation accreditation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.startupprofile.model.Accreditation> toCacheModel();

	@Override
	public com.sambaash.platform.srv.startupprofile.model.Accreditation toEscapedModel();

	@Override
	public com.sambaash.platform.srv.startupprofile.model.Accreditation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}