/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.startupprofile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Organization service. Represents a row in the &quot;SPOrganization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.startupprofile.model.impl.OrganizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.startupprofile.model.impl.OrganizationImpl}.
 * </p>
 *
 * @author pradeep
 * @see Organization
 * @see com.sambaash.platform.srv.startupprofile.model.impl.OrganizationImpl
 * @see com.sambaash.platform.srv.startupprofile.model.impl.OrganizationModelImpl
 * @generated
 */
public interface OrganizationModel extends BaseModel<Organization>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a organization model instance should use the {@link Organization} interface instead.
	 */

	/**
	 * Returns the primary key of this organization.
	 *
	 * @return the primary key of this organization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this organization.
	 *
	 * @param primaryKey the primary key of this organization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this organization.
	 *
	 * @return the uuid of this organization
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this organization.
	 *
	 * @param uuid the uuid of this organization
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the organization ID of this organization.
	 *
	 * @return the organization ID of this organization
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this organization.
	 *
	 * @param organizationId the organization ID of this organization
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the name of this organization.
	 *
	 * @return the name of this organization
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this organization.
	 *
	 * @param name the name of this organization
	 */
	public void setName(String name);

	/**
	 * Returns the corporate code of this organization.
	 *
	 * @return the corporate code of this organization
	 */
	@AutoEscape
	public String getCorporateCode();

	/**
	 * Sets the corporate code of this organization.
	 *
	 * @param corporateCode the corporate code of this organization
	 */
	public void setCorporateCode(String corporateCode);

	/**
	 * Returns the corporate type of this organization.
	 *
	 * @return the corporate type of this organization
	 */
	@AutoEscape
	public String getCorporateType();

	/**
	 * Sets the corporate type of this organization.
	 *
	 * @param corporateType the corporate type of this organization
	 */
	public void setCorporateType(String corporateType);

	/**
	 * Returns the corporate category of this organization.
	 *
	 * @return the corporate category of this organization
	 */
	@AutoEscape
	public String getCorporateCategory();

	/**
	 * Sets the corporate category of this organization.
	 *
	 * @param corporateCategory the corporate category of this organization
	 */
	public void setCorporateCategory(String corporateCategory);

	/**
	 * Returns the api path of this organization.
	 *
	 * @return the api path of this organization
	 */
	@AutoEscape
	public String getApiPath();

	/**
	 * Sets the api path of this organization.
	 *
	 * @param apiPath the api path of this organization
	 */
	public void setApiPath(String apiPath);

	/**
	 * Returns the categories of this organization.
	 *
	 * @return the categories of this organization
	 */
	@AutoEscape
	public String getCategories();

	/**
	 * Sets the categories of this organization.
	 *
	 * @param categories the categories of this organization
	 */
	public void setCategories(String categories);

	/**
	 * Returns the founded on of this organization.
	 *
	 * @return the founded on of this organization
	 */
	@AutoEscape
	public String getFoundedOn();

	/**
	 * Sets the founded on of this organization.
	 *
	 * @param foundedOn the founded on of this organization
	 */
	public void setFoundedOn(String foundedOn);

	/**
	 * Returns the no of employees of this organization.
	 *
	 * @return the no of employees of this organization
	 */
	public int getNoOfEmployees();

	/**
	 * Sets the no of employees of this organization.
	 *
	 * @param noOfEmployees the no of employees of this organization
	 */
	public void setNoOfEmployees(int noOfEmployees);

	/**
	 * Returns the email ID of this organization.
	 *
	 * @return the email ID of this organization
	 */
	@AutoEscape
	public String getEmailId();

	/**
	 * Sets the email ID of this organization.
	 *
	 * @param emailId the email ID of this organization
	 */
	public void setEmailId(String emailId);

	/**
	 * Returns the website of this organization.
	 *
	 * @return the website of this organization
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this organization.
	 *
	 * @param website the website of this organization
	 */
	public void setWebsite(String website);

	/**
	 * Returns the facebook of this organization.
	 *
	 * @return the facebook of this organization
	 */
	@AutoEscape
	public String getFacebook();

	/**
	 * Sets the facebook of this organization.
	 *
	 * @param facebook the facebook of this organization
	 */
	public void setFacebook(String facebook);

	/**
	 * Returns the twitter of this organization.
	 *
	 * @return the twitter of this organization
	 */
	@AutoEscape
	public String getTwitter();

	/**
	 * Sets the twitter of this organization.
	 *
	 * @param twitter the twitter of this organization
	 */
	public void setTwitter(String twitter);

	/**
	 * Returns the linked in of this organization.
	 *
	 * @return the linked in of this organization
	 */
	@AutoEscape
	public String getLinkedIn();

	/**
	 * Sets the linked in of this organization.
	 *
	 * @param linkedIn the linked in of this organization
	 */
	public void setLinkedIn(String linkedIn);

	/**
	 * Returns the crunchbase of this organization.
	 *
	 * @return the crunchbase of this organization
	 */
	@AutoEscape
	public String getCrunchbase();

	/**
	 * Sets the crunchbase of this organization.
	 *
	 * @param crunchbase the crunchbase of this organization
	 */
	public void setCrunchbase(String crunchbase);

	/**
	 * Returns the mobile of this organization.
	 *
	 * @return the mobile of this organization
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this organization.
	 *
	 * @param mobile the mobile of this organization
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the total funds of this organization.
	 *
	 * @return the total funds of this organization
	 */
	@AutoEscape
	public String getTotalFunds();

	/**
	 * Sets the total funds of this organization.
	 *
	 * @param totalFunds the total funds of this organization
	 */
	public void setTotalFunds(String totalFunds);

	/**
	 * Returns the uen of this organization.
	 *
	 * @return the uen of this organization
	 */
	@AutoEscape
	public String getUen();

	/**
	 * Sets the uen of this organization.
	 *
	 * @param uen the uen of this organization
	 */
	public void setUen(String uen);

	/**
	 * Returns the description of this organization.
	 *
	 * @return the description of this organization
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this organization.
	 *
	 * @param description the description of this organization
	 */
	public void setDescription(String description);

	/**
	 * Returns the short pitch of this organization.
	 *
	 * @return the short pitch of this organization
	 */
	@AutoEscape
	public String getShortPitch();

	/**
	 * Sets the short pitch of this organization.
	 *
	 * @param shortPitch the short pitch of this organization
	 */
	public void setShortPitch(String shortPitch);

	/**
	 * Returns the lifecycle stage of this organization.
	 *
	 * @return the lifecycle stage of this organization
	 */
	@AutoEscape
	public String getLifecycleStage();

	/**
	 * Sets the lifecycle stage of this organization.
	 *
	 * @param lifecycleStage the lifecycle stage of this organization
	 */
	public void setLifecycleStage(String lifecycleStage);

	/**
	 * Returns the capital raised of this organization.
	 *
	 * @return the capital raised of this organization
	 */
	@AutoEscape
	public String getCapitalRaised();

	/**
	 * Sets the capital raised of this organization.
	 *
	 * @param capitalRaised the capital raised of this organization
	 */
	public void setCapitalRaised(String capitalRaised);

	/**
	 * Returns the is incorporated of this organization.
	 *
	 * @return the is incorporated of this organization
	 */
	public boolean getIsIncorporated();

	/**
	 * Returns <code>true</code> if this organization is is incorporated.
	 *
	 * @return <code>true</code> if this organization is is incorporated; <code>false</code> otherwise
	 */
	public boolean isIsIncorporated();

	/**
	 * Sets whether this organization is is incorporated.
	 *
	 * @param isIncorporated the is incorporated of this organization
	 */
	public void setIsIncorporated(boolean isIncorporated);

	/**
	 * Returns the stock symbol of this organization.
	 *
	 * @return the stock symbol of this organization
	 */
	@AutoEscape
	public String getStockSymbol();

	/**
	 * Sets the stock symbol of this organization.
	 *
	 * @param stockSymbol the stock symbol of this organization
	 */
	public void setStockSymbol(String stockSymbol);

	/**
	 * Returns the image url of this organization.
	 *
	 * @return the image url of this organization
	 */
	@AutoEscape
	public String getImageUrl();

	/**
	 * Sets the image url of this organization.
	 *
	 * @param imageUrl the image url of this organization
	 */
	public void setImageUrl(String imageUrl);

	/**
	 * Returns the videos of this organization.
	 *
	 * @return the videos of this organization
	 */
	@AutoEscape
	public String getVideos();

	/**
	 * Sets the videos of this organization.
	 *
	 * @param videos the videos of this organization
	 */
	public void setVideos(String videos);

	/**
	 * Returns the profile outline of this organization.
	 *
	 * @return the profile outline of this organization
	 */
	@AutoEscape
	public String getProfileOutline();

	/**
	 * Sets the profile outline of this organization.
	 *
	 * @param profileOutline the profile outline of this organization
	 */
	public void setProfileOutline(String profileOutline);

	/**
	 * Returns the raising funds of this organization.
	 *
	 * @return the raising funds of this organization
	 */
	@AutoEscape
	public String getRaisingFunds();

	/**
	 * Sets the raising funds of this organization.
	 *
	 * @param raisingFunds the raising funds of this organization
	 */
	public void setRaisingFunds(String raisingFunds);

	/**
	 * Returns the extras of this organization.
	 *
	 * @return the extras of this organization
	 */
	@AutoEscape
	public String getExtras();

	/**
	 * Sets the extras of this organization.
	 *
	 * @param extras the extras of this organization
	 */
	public void setExtras(String extras);

	/**
	 * Returns the unique desc of this organization.
	 *
	 * @return the unique desc of this organization
	 */
	@AutoEscape
	public String getUniqueDesc();

	/**
	 * Sets the unique desc of this organization.
	 *
	 * @param uniqueDesc the unique desc of this organization
	 */
	public void setUniqueDesc(String uniqueDesc);

	/**
	 * Returns the links of this organization.
	 *
	 * @return the links of this organization
	 */
	@AutoEscape
	public String getLinks();

	/**
	 * Sets the links of this organization.
	 *
	 * @param links the links of this organization
	 */
	public void setLinks(String links);

	/**
	 * Returns the is base org of this organization.
	 *
	 * @return the is base org of this organization
	 */
	public boolean getIsBaseOrg();

	/**
	 * Returns <code>true</code> if this organization is is base org.
	 *
	 * @return <code>true</code> if this organization is is base org; <code>false</code> otherwise
	 */
	public boolean isIsBaseOrg();

	/**
	 * Sets whether this organization is is base org.
	 *
	 * @param isBaseOrg the is base org of this organization
	 */
	public void setIsBaseOrg(boolean isBaseOrg);

	/**
	 * Returns the completeness of this organization.
	 *
	 * @return the completeness of this organization
	 */
	public boolean getCompleteness();

	/**
	 * Returns <code>true</code> if this organization is completeness.
	 *
	 * @return <code>true</code> if this organization is completeness; <code>false</code> otherwise
	 */
	public boolean isCompleteness();

	/**
	 * Sets whether this organization is completeness.
	 *
	 * @param completeness the completeness of this organization
	 */
	public void setCompleteness(boolean completeness);

	/**
	 * Returns the group ID of this organization.
	 *
	 * @return the group ID of this organization
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this organization.
	 *
	 * @param groupId the group ID of this organization
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this organization.
	 *
	 * @return the company ID of this organization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this organization.
	 *
	 * @param companyId the company ID of this organization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this organization.
	 *
	 * @return the user ID of this organization
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this organization.
	 *
	 * @param userId the user ID of this organization
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this organization.
	 *
	 * @return the user uuid of this organization
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this organization.
	 *
	 * @param userUuid the user uuid of this organization
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this organization.
	 *
	 * @return the user name of this organization
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this organization.
	 *
	 * @param userName the user name of this organization
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this organization.
	 *
	 * @return the create date of this organization
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this organization.
	 *
	 * @param createDate the create date of this organization
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this organization.
	 *
	 * @return the modified date of this organization
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this organization.
	 *
	 * @param modifiedDate the modified date of this organization
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the active of this organization.
	 *
	 * @return the active of this organization
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this organization is active.
	 *
	 * @return <code>true</code> if this organization is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this organization is active.
	 *
	 * @param active the active of this organization
	 */
	public void setActive(boolean active);

	/**
	 * Returns the logo ID of this organization.
	 *
	 * @return the logo ID of this organization
	 */
	public long getLogoId();

	/**
	 * Sets the logo ID of this organization.
	 *
	 * @param logoId the logo ID of this organization
	 */
	public void setLogoId(long logoId);

	/**
	 * Returns the methodology type of this organization.
	 *
	 * @return the methodology type of this organization
	 */
	public long getMethodologyType();

	/**
	 * Sets the methodology type of this organization.
	 *
	 * @param methodologyType the methodology type of this organization
	 */
	public void setMethodologyType(long methodologyType);

	/**
	 * Returns the methodology sub type of this organization.
	 *
	 * @return the methodology sub type of this organization
	 */
	public long getMethodologySubType();

	/**
	 * Sets the methodology sub type of this organization.
	 *
	 * @param methodologySubType the methodology sub type of this organization
	 */
	public void setMethodologySubType(long methodologySubType);

	/**
	 * Returns the stage of this organization.
	 *
	 * @return the stage of this organization
	 */
	public int getStage();

	/**
	 * Sets the stage of this organization.
	 *
	 * @param stage the stage of this organization
	 */
	public void setStage(int stage);

	/**
	 * Returns the feedback of this organization.
	 *
	 * @return the feedback of this organization
	 */
	@AutoEscape
	public String getFeedback();

	/**
	 * Sets the feedback of this organization.
	 *
	 * @param feedback the feedback of this organization
	 */
	public void setFeedback(String feedback);

	/**
	 * Returns the video links of this organization.
	 *
	 * @return the video links of this organization
	 */
	@AutoEscape
	public String getVideoLinks();

	/**
	 * Sets the video links of this organization.
	 *
	 * @param videoLinks the video links of this organization
	 */
	public void setVideoLinks(String videoLinks);

	/**
	 * Returns the projects worked on of this organization.
	 *
	 * @return the projects worked on of this organization
	 */
	@AutoEscape
	public String getProjectsWorkedOn();

	/**
	 * Sets the projects worked on of this organization.
	 *
	 * @param projectsWorkedOn the projects worked on of this organization
	 */
	public void setProjectsWorkedOn(String projectsWorkedOn);

	/**
	 * Returns the show in blackbook of this organization.
	 *
	 * @return the show in blackbook of this organization
	 */
	public boolean getShowInBlackbook();

	/**
	 * Returns <code>true</code> if this organization is show in blackbook.
	 *
	 * @return <code>true</code> if this organization is show in blackbook; <code>false</code> otherwise
	 */
	public boolean isShowInBlackbook();

	/**
	 * Sets whether this organization is show in blackbook.
	 *
	 * @param showInBlackbook the show in blackbook of this organization
	 */
	public void setShowInBlackbook(boolean showInBlackbook);

	/**
	 * Returns the fax number of this organization.
	 *
	 * @return the fax number of this organization
	 */
	@AutoEscape
	public String getFaxNumber();

	/**
	 * Sets the fax number of this organization.
	 *
	 * @param faxNumber the fax number of this organization
	 */
	public void setFaxNumber(String faxNumber);

	/**
	 * Returns the contact name of this organization.
	 *
	 * @return the contact name of this organization
	 */
	@AutoEscape
	public String getContactName();

	/**
	 * Sets the contact name of this organization.
	 *
	 * @param contactName the contact name of this organization
	 */
	public void setContactName(String contactName);

	/**
	 * Returns the contact designation of this organization.
	 *
	 * @return the contact designation of this organization
	 */
	@AutoEscape
	public String getContactDesignation();

	/**
	 * Sets the contact designation of this organization.
	 *
	 * @param contactDesignation the contact designation of this organization
	 */
	public void setContactDesignation(String contactDesignation);

	/**
	 * Returns the pipeline status of this organization.
	 *
	 * @return the pipeline status of this organization
	 */
	public int getPipelineStatus();

	/**
	 * Sets the pipeline status of this organization.
	 *
	 * @param pipelineStatus the pipeline status of this organization
	 */
	public void setPipelineStatus(int pipelineStatus);

	/**
	 * Returns the business dev manager of this organization.
	 *
	 * @return the business dev manager of this organization
	 */
	public int getBusinessDevManager();

	/**
	 * Sets the business dev manager of this organization.
	 *
	 * @param businessDevManager the business dev manager of this organization
	 */
	public void setBusinessDevManager(int businessDevManager);

	/**
	 * Returns the prev business dev manager of this organization.
	 *
	 * @return the prev business dev manager of this organization
	 */
	public int getPrevBusinessDevManager();

	/**
	 * Sets the prev business dev manager of this organization.
	 *
	 * @param prevBusinessDevManager the prev business dev manager of this organization
	 */
	public void setPrevBusinessDevManager(int prevBusinessDevManager);

	/**
	 * Returns the is a t o of this organization.
	 *
	 * @return the is a t o of this organization
	 */
	public boolean getIsATO();

	/**
	 * Returns <code>true</code> if this organization is is a t o.
	 *
	 * @return <code>true</code> if this organization is is a t o; <code>false</code> otherwise
	 */
	public boolean isIsATO();

	/**
	 * Sets whether this organization is is a t o.
	 *
	 * @param isATO the is a t o of this organization
	 */
	public void setIsATO(boolean isATO);

	/**
	 * Returns the approval date of this organization.
	 *
	 * @return the approval date of this organization
	 */
	public Date getApprovalDate();

	/**
	 * Sets the approval date of this organization.
	 *
	 * @param approvalDate the approval date of this organization
	 */
	public void setApprovalDate(Date approvalDate);

	/**
	 * Returns the status of this organization.
	 *
	 * @return the status of this organization
	 */
	public int getStatus();

	/**
	 * Sets the status of this organization.
	 *
	 * @param status the status of this organization
	 */
	public void setStatus(int status);

	/**
	 * Returns the listed co of this organization.
	 *
	 * @return the listed co of this organization
	 */
	@AutoEscape
	public String getListedCo();

	/**
	 * Sets the listed co of this organization.
	 *
	 * @param listedCo the listed co of this organization
	 */
	public void setListedCo(String listedCo);

	/**
	 * Returns the no of potential candidates of this organization.
	 *
	 * @return the no of potential candidates of this organization
	 */
	public long getNoOfPotentialCandidates();

	/**
	 * Sets the no of potential candidates of this organization.
	 *
	 * @param noOfPotentialCandidates the no of potential candidates of this organization
	 */
	public void setNoOfPotentialCandidates(long noOfPotentialCandidates);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.startupprofile.model.Organization organization);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.startupprofile.model.Organization> toCacheModel();

	@Override
	public com.sambaash.platform.srv.startupprofile.model.Organization toEscapedModel();

	@Override
	public com.sambaash.platform.srv.startupprofile.model.Organization toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}