/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.sambaash.platform.srv.startupprofile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SPOrgContactUs service. Represents a row in the &quot;SPOrgContactUs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sambaash.platform.srv.startupprofile.model.impl.SPOrgContactUsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sambaash.platform.srv.startupprofile.model.impl.SPOrgContactUsImpl}.
 * </p>
 *
 * @author pradeep
 * @see SPOrgContactUs
 * @see com.sambaash.platform.srv.startupprofile.model.impl.SPOrgContactUsImpl
 * @see com.sambaash.platform.srv.startupprofile.model.impl.SPOrgContactUsModelImpl
 * @generated
 */
public interface SPOrgContactUsModel extends BaseModel<SPOrgContactUs> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s p org contact us model instance should use the {@link SPOrgContactUs} interface instead.
	 */

	/**
	 * Returns the primary key of this s p org contact us.
	 *
	 * @return the primary key of this s p org contact us
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s p org contact us.
	 *
	 * @param primaryKey the primary key of this s p org contact us
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sp contact us ID of this s p org contact us.
	 *
	 * @return the sp contact us ID of this s p org contact us
	 */
	public long getSpContactUsId();

	/**
	 * Sets the sp contact us ID of this s p org contact us.
	 *
	 * @param spContactUsId the sp contact us ID of this s p org contact us
	 */
	public void setSpContactUsId(long spContactUsId);

	/**
	 * Returns the group ID of this s p org contact us.
	 *
	 * @return the group ID of this s p org contact us
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this s p org contact us.
	 *
	 * @param groupId the group ID of this s p org contact us
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the organization ID of this s p org contact us.
	 *
	 * @return the organization ID of this s p org contact us
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this s p org contact us.
	 *
	 * @param organizationId the organization ID of this s p org contact us
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the user ID of this s p org contact us.
	 *
	 * @return the user ID of this s p org contact us
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this s p org contact us.
	 *
	 * @param userId the user ID of this s p org contact us
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s p org contact us.
	 *
	 * @return the user uuid of this s p org contact us
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s p org contact us.
	 *
	 * @param userUuid the user uuid of this s p org contact us
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this s p org contact us.
	 *
	 * @return the user name of this s p org contact us
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this s p org contact us.
	 *
	 * @param userName the user name of this s p org contact us
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this s p org contact us.
	 *
	 * @return the create date of this s p org contact us
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this s p org contact us.
	 *
	 * @param createDate the create date of this s p org contact us
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this s p org contact us.
	 *
	 * @return the modified date of this s p org contact us
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this s p org contact us.
	 *
	 * @param modifiedDate the modified date of this s p org contact us
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the salutation of this s p org contact us.
	 *
	 * @return the salutation of this s p org contact us
	 */
	@AutoEscape
	public String getSalutation();

	/**
	 * Sets the salutation of this s p org contact us.
	 *
	 * @param salutation the salutation of this s p org contact us
	 */
	public void setSalutation(String salutation);

	/**
	 * Returns the person of this s p org contact us.
	 *
	 * @return the person of this s p org contact us
	 */
	@AutoEscape
	public String getPerson();

	/**
	 * Sets the person of this s p org contact us.
	 *
	 * @param person the person of this s p org contact us
	 */
	public void setPerson(String person);

	/**
	 * Returns the first name of this s p org contact us.
	 *
	 * @return the first name of this s p org contact us
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this s p org contact us.
	 *
	 * @param firstName the first name of this s p org contact us
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this s p org contact us.
	 *
	 * @return the last name of this s p org contact us
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this s p org contact us.
	 *
	 * @param lastName the last name of this s p org contact us
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the designation of this s p org contact us.
	 *
	 * @return the designation of this s p org contact us
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this s p org contact us.
	 *
	 * @param designation the designation of this s p org contact us
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the qualification of this s p org contact us.
	 *
	 * @return the qualification of this s p org contact us
	 */
	@AutoEscape
	public String getQualification();

	/**
	 * Sets the qualification of this s p org contact us.
	 *
	 * @param qualification the qualification of this s p org contact us
	 */
	public void setQualification(String qualification);

	/**
	 * Returns the qualification date of this s p org contact us.
	 *
	 * @return the qualification date of this s p org contact us
	 */
	@AutoEscape
	public String getQualificationDate();

	/**
	 * Sets the qualification date of this s p org contact us.
	 *
	 * @param qualificationDate the qualification date of this s p org contact us
	 */
	public void setQualificationDate(String qualificationDate);

	/**
	 * Returns the email address of this s p org contact us.
	 *
	 * @return the email address of this s p org contact us
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this s p org contact us.
	 *
	 * @param emailAddress the email address of this s p org contact us
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the department of this s p org contact us.
	 *
	 * @return the department of this s p org contact us
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this s p org contact us.
	 *
	 * @param department the department of this s p org contact us
	 */
	public void setDepartment(String department);

	/**
	 * Returns the mobile number of this s p org contact us.
	 *
	 * @return the mobile number of this s p org contact us
	 */
	public long getMobileNumber();

	/**
	 * Sets the mobile number of this s p org contact us.
	 *
	 * @param mobileNumber the mobile number of this s p org contact us
	 */
	public void setMobileNumber(long mobileNumber);

	/**
	 * Returns the telephone number of this s p org contact us.
	 *
	 * @return the telephone number of this s p org contact us
	 */
	public long getTelephoneNumber();

	/**
	 * Sets the telephone number of this s p org contact us.
	 *
	 * @param telephoneNumber the telephone number of this s p org contact us
	 */
	public void setTelephoneNumber(long telephoneNumber);

	/**
	 * Returns the fax number of this s p org contact us.
	 *
	 * @return the fax number of this s p org contact us
	 */
	public long getFaxNumber();

	/**
	 * Sets the fax number of this s p org contact us.
	 *
	 * @param faxNumber the fax number of this s p org contact us
	 */
	public void setFaxNumber(long faxNumber);

	/**
	 * Returns the billing contact of this s p org contact us.
	 *
	 * @return the billing contact of this s p org contact us
	 */
	public boolean getBillingContact();

	/**
	 * Returns <code>true</code> if this s p org contact us is billing contact.
	 *
	 * @return <code>true</code> if this s p org contact us is billing contact; <code>false</code> otherwise
	 */
	public boolean isBillingContact();

	/**
	 * Sets whether this s p org contact us is billing contact.
	 *
	 * @param billingContact the billing contact of this s p org contact us
	 */
	public void setBillingContact(boolean billingContact);

	/**
	 * Returns the operations contact of this s p org contact us.
	 *
	 * @return the operations contact of this s p org contact us
	 */
	public boolean getOperationsContact();

	/**
	 * Returns <code>true</code> if this s p org contact us is operations contact.
	 *
	 * @return <code>true</code> if this s p org contact us is operations contact; <code>false</code> otherwise
	 */
	public boolean isOperationsContact();

	/**
	 * Sets whether this s p org contact us is operations contact.
	 *
	 * @param operationsContact the operations contact of this s p org contact us
	 */
	public void setOperationsContact(boolean operationsContact);

	/**
	 * Returns the active of this s p org contact us.
	 *
	 * @return the active of this s p org contact us
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this s p org contact us is active.
	 *
	 * @return <code>true</code> if this s p org contact us is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this s p org contact us is active.
	 *
	 * @param active the active of this s p org contact us
	 */
	public void setActive(boolean active);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.sambaash.platform.srv.startupprofile.model.SPOrgContactUs spOrgContactUs);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.sambaash.platform.srv.startupprofile.model.SPOrgContactUs> toCacheModel();

	@Override
	public com.sambaash.platform.srv.startupprofile.model.SPOrgContactUs toEscapedModel();

	@Override
	public com.sambaash.platform.srv.startupprofile.model.SPOrgContactUs toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}